/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Retrieves a paginated list of Tournament_drafts Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Tournament_drafts Collection
 */
export const getCollectionsTournamentDraftsRecordsQueryPageDefault = 1;

export const getCollectionsTournamentDraftsRecordsQueryPerPageDefault = 30;
export const getCollectionsTournamentDraftsRecordsQueryPerPageMax = 500;

export const getCollectionsTournamentDraftsRecordsQuerySkipTotalDefault = false;

export const GetCollectionsTournamentDraftsRecordsQueryParams = zod.object({
  "filter": zod.string().optional().describe('Filtering expression (e.g., \'created > \"2022-01-01\"\')'),
  "sort": zod.string().optional().describe('Comma-separated list of fields to sort by. Prefix with \'-\' for descending order.'),
  "page": zod.number().min(1).default(getCollectionsTournamentDraftsRecordsQueryPageDefault).describe('Page number (starting from 1)'),
  "perPage": zod.number().min(1).max(getCollectionsTournamentDraftsRecordsQueryPerPageMax).default(getCollectionsTournamentDraftsRecordsQueryPerPageDefault).describe('Number of records per page (max 500)'),
  "skipTotal": zod.boolean().default(getCollectionsTournamentDraftsRecordsQuerySkipTotalDefault).describe('Set to true to skip the total count (improves performance for large collections)'),
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsTournamentDraftsRecordsResponse = zod.object({
  "page": zod.number().optional(),
  "perPage": zod.number().optional(),
  "totalItems": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "items": zod.array(zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "title": zod.string(),
  "format": zod.string().optional(),
  "rules": zod.string().optional(),
  "max_teams": zod.number().optional(),
  "scheduled_at": zod.iso.datetime({"offset":true}).optional(),
  "notes": zod.string().optional(),
  "publish_to_tournament": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean().optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})).optional()
})

/**
 * @summary Create Tournament_drafts Collection Record
 */
export const PostCollectionsTournamentDraftsRecordsBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "title": zod.string(),
  "format": zod.string().optional(),
  "rules": zod.string().optional(),
  "max_teams": zod.number().optional(),
  "scheduled_at": zod.iso.datetime({"offset":true}).optional(),
  "notes": zod.string().optional(),
  "publish_to_tournament": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean().optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const PostCollectionsTournamentDraftsRecordsResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "title": zod.string(),
  "format": zod.string().optional(),
  "rules": zod.string().optional(),
  "max_teams": zod.number().optional(),
  "scheduled_at": zod.iso.datetime({"offset":true}).optional(),
  "notes": zod.string().optional(),
  "publish_to_tournament": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean().optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Get Tournament_drafts Collection by ID
 */
export const GetCollectionsTournamentDraftsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const GetCollectionsTournamentDraftsRecordsIdQueryParams = zod.object({
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsTournamentDraftsRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "title": zod.string(),
  "format": zod.string().optional(),
  "rules": zod.string().optional(),
  "max_teams": zod.number().optional(),
  "scheduled_at": zod.iso.datetime({"offset":true}).optional(),
  "notes": zod.string().optional(),
  "publish_to_tournament": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean().optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Update Tournament_drafts Collection Record
 */
export const PatchCollectionsTournamentDraftsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const PatchCollectionsTournamentDraftsRecordsIdBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "title": zod.string(),
  "format": zod.string().optional(),
  "rules": zod.string().optional(),
  "max_teams": zod.number().optional(),
  "scheduled_at": zod.iso.datetime({"offset":true}).optional(),
  "notes": zod.string().optional(),
  "publish_to_tournament": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean().optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const PatchCollectionsTournamentDraftsRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "title": zod.string(),
  "format": zod.string().optional(),
  "rules": zod.string().optional(),
  "max_teams": zod.number().optional(),
  "scheduled_at": zod.iso.datetime({"offset":true}).optional(),
  "notes": zod.string().optional(),
  "publish_to_tournament": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean().optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Delete Tournament_drafts Collection Record
 */
export const DeleteCollectionsTournamentDraftsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const DeleteCollectionsTournamentDraftsRecordsIdResponse = zod.void()

