/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCollectionsTournamentsRecords200,
  GetCollectionsTournamentsRecordsIdParams,
  GetCollectionsTournamentsRecordsParams,
  TournamentsRecord
} from '../model';

import { customInstance } from '../../../lib/api/mutator/custom-instance.ts';
import type { ErrorType , BodyType } from '../../../lib/api/mutator/custom-instance.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getCollectionsTournamentsRecordsResponse200 = {
  data: GetCollectionsTournamentsRecords200
  status: 200
}

export type getCollectionsTournamentsRecordsResponseSuccess = (getCollectionsTournamentsRecordsResponse200) & {
  headers: Headers;
};
;

export type getCollectionsTournamentsRecordsResponse = (getCollectionsTournamentsRecordsResponseSuccess)

export const getGetCollectionsTournamentsRecordsUrl = (params?: GetCollectionsTournamentsRecordsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collections/tournaments/records?${stringifiedParams}` : `/collections/tournaments/records`
}

/**
 * Retrieves a paginated list of Tournaments Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Tournaments Collection
 */
export const getCollectionsTournamentsRecords = async (params?: GetCollectionsTournamentsRecordsParams, options?: RequestInit): Promise<getCollectionsTournamentsRecordsResponse> => {

  return customInstance<getCollectionsTournamentsRecordsResponse>(getGetCollectionsTournamentsRecordsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsTournamentsRecordsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTournamentsRecords>>, TError,{params?: GetCollectionsTournamentsRecordsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTournamentsRecords>>, TError,{params?: GetCollectionsTournamentsRecordsParams}, TContext> => {

const mutationKey = ['getCollectionsTournamentsRecords'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsTournamentsRecords>>, {params?: GetCollectionsTournamentsRecordsParams}> = (props) => {
          const {params} = props ?? {};

          return  getCollectionsTournamentsRecords(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsTournamentsRecordsMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsTournamentsRecords>>>

    export type GetCollectionsTournamentsRecordsMutationError = ErrorType<unknown>

    /**
 * @summary List Tournaments Collection
 */
export const useGetCollectionsTournamentsRecords = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTournamentsRecords>>, TError,{params?: GetCollectionsTournamentsRecordsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsTournamentsRecords>>,
        TError,
        {params?: GetCollectionsTournamentsRecordsParams},
        TContext
      > => {
      return useMutation(getGetCollectionsTournamentsRecordsMutationOptions(options), queryClient);
    }
    export type postCollectionsTournamentsRecordsResponse200 = {
  data: TournamentsRecord
  status: 200
}

export type postCollectionsTournamentsRecordsResponseSuccess = (postCollectionsTournamentsRecordsResponse200) & {
  headers: Headers;
};
;

export type postCollectionsTournamentsRecordsResponse = (postCollectionsTournamentsRecordsResponseSuccess)

export const getPostCollectionsTournamentsRecordsUrl = () => {




  return `/collections/tournaments/records`
}

/**
 * @summary Create Tournaments Collection Record
 */
export const postCollectionsTournamentsRecords = async (tournamentsRecord?: TournamentsRecord, options?: RequestInit): Promise<postCollectionsTournamentsRecordsResponse> => {

  return customInstance<postCollectionsTournamentsRecordsResponse>(getPostCollectionsTournamentsRecordsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(tournamentsRecord)
  }
);}





export const getPostCollectionsTournamentsRecordsQueryKey = (tournamentsRecord?: BodyType<TournamentsRecord>,) => {
    return [
    'POST', `/collections/tournaments/records`, tournamentsRecord
    ] as const;
    }


export const getPostCollectionsTournamentsRecordsQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>, TError = ErrorType<unknown>>(tournamentsRecord?: BodyType<TournamentsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsTournamentsRecordsQueryKey(tournamentsRecord);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>> = ({ signal }) => postCollectionsTournamentsRecords(tournamentsRecord, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsTournamentsRecordsQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>>
export type PostCollectionsTournamentsRecordsQueryError = ErrorType<unknown>


export function usePostCollectionsTournamentsRecords<TData = Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>, TError = ErrorType<unknown>>(
 tournamentsRecord: undefined |  BodyType<TournamentsRecord>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsTournamentsRecords<TData = Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>, TError = ErrorType<unknown>>(
 tournamentsRecord?: BodyType<TournamentsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsTournamentsRecords<TData = Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>, TError = ErrorType<unknown>>(
 tournamentsRecord?: BodyType<TournamentsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create Tournaments Collection Record
 */

export function usePostCollectionsTournamentsRecords<TData = Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>, TError = ErrorType<unknown>>(
 tournamentsRecord?: BodyType<TournamentsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTournamentsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsTournamentsRecordsQueryOptions(tournamentsRecord,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getCollectionsTournamentsRecordsIdResponse200 = {
  data: TournamentsRecord
  status: 200
}

export type getCollectionsTournamentsRecordsIdResponseSuccess = (getCollectionsTournamentsRecordsIdResponse200) & {
  headers: Headers;
};
;

export type getCollectionsTournamentsRecordsIdResponse = (getCollectionsTournamentsRecordsIdResponseSuccess)

export const getGetCollectionsTournamentsRecordsIdUrl = (id: string,
    params?: GetCollectionsTournamentsRecordsIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collections/tournaments/records/${id}?${stringifiedParams}` : `/collections/tournaments/records/${id}`
}

/**
 * @summary Get Tournaments Collection by ID
 */
export const getCollectionsTournamentsRecordsId = async (id: string,
    params?: GetCollectionsTournamentsRecordsIdParams, options?: RequestInit): Promise<getCollectionsTournamentsRecordsIdResponse> => {

  return customInstance<getCollectionsTournamentsRecordsIdResponse>(getGetCollectionsTournamentsRecordsIdUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsTournamentsRecordsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTournamentsRecordsId>>, TError,{id: string;params?: GetCollectionsTournamentsRecordsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTournamentsRecordsId>>, TError,{id: string;params?: GetCollectionsTournamentsRecordsIdParams}, TContext> => {

const mutationKey = ['getCollectionsTournamentsRecordsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsTournamentsRecordsId>>, {id: string;params?: GetCollectionsTournamentsRecordsIdParams}> = (props) => {
          const {id,params} = props ?? {};

          return  getCollectionsTournamentsRecordsId(id,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsTournamentsRecordsIdMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsTournamentsRecordsId>>>

    export type GetCollectionsTournamentsRecordsIdMutationError = ErrorType<unknown>

    /**
 * @summary Get Tournaments Collection by ID
 */
export const useGetCollectionsTournamentsRecordsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTournamentsRecordsId>>, TError,{id: string;params?: GetCollectionsTournamentsRecordsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsTournamentsRecordsId>>,
        TError,
        {id: string;params?: GetCollectionsTournamentsRecordsIdParams},
        TContext
      > => {
      return useMutation(getGetCollectionsTournamentsRecordsIdMutationOptions(options), queryClient);
    }
    export type patchCollectionsTournamentsRecordsIdResponse200 = {
  data: TournamentsRecord
  status: 200
}

export type patchCollectionsTournamentsRecordsIdResponseSuccess = (patchCollectionsTournamentsRecordsIdResponse200) & {
  headers: Headers;
};
;

export type patchCollectionsTournamentsRecordsIdResponse = (patchCollectionsTournamentsRecordsIdResponseSuccess)

export const getPatchCollectionsTournamentsRecordsIdUrl = (id: string,) => {




  return `/collections/tournaments/records/${id}`
}

/**
 * @summary Update Tournaments Collection Record
 */
export const patchCollectionsTournamentsRecordsId = async (id: string,
    tournamentsRecord?: TournamentsRecord, options?: RequestInit): Promise<patchCollectionsTournamentsRecordsIdResponse> => {

  return customInstance<patchCollectionsTournamentsRecordsIdResponse>(getPatchCollectionsTournamentsRecordsIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(tournamentsRecord)
  }
);}





export const getPatchCollectionsTournamentsRecordsIdQueryKey = (id: string,
    tournamentsRecord?: BodyType<TournamentsRecord>,) => {
    return [
    'PATCH', `/collections/tournaments/records/${id}`, tournamentsRecord
    ] as const;
    }


export const getPatchCollectionsTournamentsRecordsIdQueryOptions = <TData = Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>, TError = ErrorType<unknown>>(id: string,
    tournamentsRecord?: BodyType<TournamentsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPatchCollectionsTournamentsRecordsIdQueryKey(id,tournamentsRecord);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>> = ({ signal }) => patchCollectionsTournamentsRecordsId(id,tournamentsRecord, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PatchCollectionsTournamentsRecordsIdQueryResult = NonNullable<Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>>
export type PatchCollectionsTournamentsRecordsIdQueryError = ErrorType<unknown>


export function usePatchCollectionsTournamentsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    tournamentsRecord: undefined |  BodyType<TournamentsRecord>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatchCollectionsTournamentsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    tournamentsRecord?: BodyType<TournamentsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatchCollectionsTournamentsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    tournamentsRecord?: BodyType<TournamentsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update Tournaments Collection Record
 */

export function usePatchCollectionsTournamentsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    tournamentsRecord?: BodyType<TournamentsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTournamentsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPatchCollectionsTournamentsRecordsIdQueryOptions(id,tournamentsRecord,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteCollectionsTournamentsRecordsIdResponse204 = {
  data: void
  status: 204
}

export type deleteCollectionsTournamentsRecordsIdResponseSuccess = (deleteCollectionsTournamentsRecordsIdResponse204) & {
  headers: Headers;
};
;

export type deleteCollectionsTournamentsRecordsIdResponse = (deleteCollectionsTournamentsRecordsIdResponseSuccess)

export const getDeleteCollectionsTournamentsRecordsIdUrl = (id: string,) => {




  return `/collections/tournaments/records/${id}`
}

/**
 * @summary Delete Tournaments Collection Record
 */
export const deleteCollectionsTournamentsRecordsId = async (id: string, options?: RequestInit): Promise<deleteCollectionsTournamentsRecordsIdResponse> => {

  return customInstance<deleteCollectionsTournamentsRecordsIdResponse>(getDeleteCollectionsTournamentsRecordsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteCollectionsTournamentsRecordsIdQueryKey = (id: string,) => {
    return [
    'DELETE', `/collections/tournaments/records/${id}`
    ] as const;
    }


export const getDeleteCollectionsTournamentsRecordsIdQueryOptions = <TData = Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteCollectionsTournamentsRecordsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>> = ({ signal }) => deleteCollectionsTournamentsRecordsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteCollectionsTournamentsRecordsIdQueryResult = NonNullable<Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>>
export type DeleteCollectionsTournamentsRecordsIdQueryError = ErrorType<unknown>


export function useDeleteCollectionsTournamentsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteCollectionsTournamentsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteCollectionsTournamentsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete Tournaments Collection Record
 */

export function useDeleteCollectionsTournamentsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTournamentsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteCollectionsTournamentsRecordsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






