/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Retrieves a paginated list of Tournaments Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Tournaments Collection
 */
export const getCollectionsTournamentsRecordsQueryPageDefault = 1;

export const getCollectionsTournamentsRecordsQueryPerPageDefault = 30;
export const getCollectionsTournamentsRecordsQueryPerPageMax = 500;

export const getCollectionsTournamentsRecordsQuerySkipTotalDefault = false;

export const GetCollectionsTournamentsRecordsQueryParams = zod.object({
  "filter": zod.string().optional().describe('Filtering expression (e.g., \'created > \"2022-01-01\"\')'),
  "sort": zod.string().optional().describe('Comma-separated list of fields to sort by. Prefix with \'-\' for descending order.'),
  "page": zod.number().min(1).default(getCollectionsTournamentsRecordsQueryPageDefault).describe('Page number (starting from 1)'),
  "perPage": zod.number().min(1).max(getCollectionsTournamentsRecordsQueryPerPageMax).default(getCollectionsTournamentsRecordsQueryPerPageDefault).describe('Number of records per page (max 500)'),
  "skipTotal": zod.boolean().default(getCollectionsTournamentsRecordsQuerySkipTotalDefault).describe('Set to true to skip the total count (improves performance for large collections)'),
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsTournamentsRecordsResponse = zod.object({
  "page": zod.number().optional(),
  "perPage": zod.number().optional(),
  "totalItems": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "items": zod.array(zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "title": zod.string(),
  "slug": zod.string().optional(),
  "description": zod.string().optional(),
  "venue": zod.string().optional(),
  "start_at": zod.iso.datetime({"offset":true}).optional(),
  "end_at": zod.iso.datetime({"offset":true}).optional(),
  "status": zod.enum(['draft', 'upcoming', 'live', 'completed', 'archived']),
  "registration_enabled": zod.boolean(),
  "registration_open_at": zod.iso.datetime({"offset":true}).optional(),
  "registration_close_at": zod.iso.datetime({"offset":true}).optional(),
  "max_teams": zod.number().optional(),
  "min_team_size": zod.number(),
  "max_team_size": zod.number(),
  "bracket_count": zod.number(),
  "bracket_format": zod.enum(['single_elimination']),
  "match_best_of": zod.number(),
  "archived": zod.boolean(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})).optional()
})

/**
 * @summary Create Tournaments Collection Record
 */
export const PostCollectionsTournamentsRecordsBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "title": zod.string(),
  "slug": zod.string().optional(),
  "description": zod.string().optional(),
  "venue": zod.string().optional(),
  "start_at": zod.iso.datetime({"offset":true}).optional(),
  "end_at": zod.iso.datetime({"offset":true}).optional(),
  "status": zod.enum(['draft', 'upcoming', 'live', 'completed', 'archived']),
  "registration_enabled": zod.boolean(),
  "registration_open_at": zod.iso.datetime({"offset":true}).optional(),
  "registration_close_at": zod.iso.datetime({"offset":true}).optional(),
  "max_teams": zod.number().optional(),
  "min_team_size": zod.number(),
  "max_team_size": zod.number(),
  "bracket_count": zod.number(),
  "bracket_format": zod.enum(['single_elimination']),
  "match_best_of": zod.number(),
  "archived": zod.boolean(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const PostCollectionsTournamentsRecordsResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "title": zod.string(),
  "slug": zod.string().optional(),
  "description": zod.string().optional(),
  "venue": zod.string().optional(),
  "start_at": zod.iso.datetime({"offset":true}).optional(),
  "end_at": zod.iso.datetime({"offset":true}).optional(),
  "status": zod.enum(['draft', 'upcoming', 'live', 'completed', 'archived']),
  "registration_enabled": zod.boolean(),
  "registration_open_at": zod.iso.datetime({"offset":true}).optional(),
  "registration_close_at": zod.iso.datetime({"offset":true}).optional(),
  "max_teams": zod.number().optional(),
  "min_team_size": zod.number(),
  "max_team_size": zod.number(),
  "bracket_count": zod.number(),
  "bracket_format": zod.enum(['single_elimination']),
  "match_best_of": zod.number(),
  "archived": zod.boolean(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Get Tournaments Collection by ID
 */
export const GetCollectionsTournamentsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const GetCollectionsTournamentsRecordsIdQueryParams = zod.object({
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsTournamentsRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "title": zod.string(),
  "slug": zod.string().optional(),
  "description": zod.string().optional(),
  "venue": zod.string().optional(),
  "start_at": zod.iso.datetime({"offset":true}).optional(),
  "end_at": zod.iso.datetime({"offset":true}).optional(),
  "status": zod.enum(['draft', 'upcoming', 'live', 'completed', 'archived']),
  "registration_enabled": zod.boolean(),
  "registration_open_at": zod.iso.datetime({"offset":true}).optional(),
  "registration_close_at": zod.iso.datetime({"offset":true}).optional(),
  "max_teams": zod.number().optional(),
  "min_team_size": zod.number(),
  "max_team_size": zod.number(),
  "bracket_count": zod.number(),
  "bracket_format": zod.enum(['single_elimination']),
  "match_best_of": zod.number(),
  "archived": zod.boolean(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Update Tournaments Collection Record
 */
export const PatchCollectionsTournamentsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const PatchCollectionsTournamentsRecordsIdBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "title": zod.string(),
  "slug": zod.string().optional(),
  "description": zod.string().optional(),
  "venue": zod.string().optional(),
  "start_at": zod.iso.datetime({"offset":true}).optional(),
  "end_at": zod.iso.datetime({"offset":true}).optional(),
  "status": zod.enum(['draft', 'upcoming', 'live', 'completed', 'archived']),
  "registration_enabled": zod.boolean(),
  "registration_open_at": zod.iso.datetime({"offset":true}).optional(),
  "registration_close_at": zod.iso.datetime({"offset":true}).optional(),
  "max_teams": zod.number().optional(),
  "min_team_size": zod.number(),
  "max_team_size": zod.number(),
  "bracket_count": zod.number(),
  "bracket_format": zod.enum(['single_elimination']),
  "match_best_of": zod.number(),
  "archived": zod.boolean(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const PatchCollectionsTournamentsRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "title": zod.string(),
  "slug": zod.string().optional(),
  "description": zod.string().optional(),
  "venue": zod.string().optional(),
  "start_at": zod.iso.datetime({"offset":true}).optional(),
  "end_at": zod.iso.datetime({"offset":true}).optional(),
  "status": zod.enum(['draft', 'upcoming', 'live', 'completed', 'archived']),
  "registration_enabled": zod.boolean(),
  "registration_open_at": zod.iso.datetime({"offset":true}).optional(),
  "registration_close_at": zod.iso.datetime({"offset":true}).optional(),
  "max_teams": zod.number().optional(),
  "min_team_size": zod.number(),
  "max_team_size": zod.number(),
  "bracket_count": zod.number(),
  "bracket_format": zod.enum(['single_elimination']),
  "match_best_of": zod.number(),
  "archived": zod.boolean(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Delete Tournaments Collection Record
 */
export const DeleteCollectionsTournamentsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const DeleteCollectionsTournamentsRecordsIdResponse = zod.void()

