/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AdminsRecord,
  PostCollectionsAdminsAuthRefresh200,
  PostCollectionsAdminsAuthWithOauth2200,
  PostCollectionsAdminsAuthWithOauth2Body,
  PostCollectionsAdminsAuthWithPassword200,
  PostCollectionsAdminsAuthWithPasswordBody,
  PostCollectionsAdminsConfirmEmailChange200,
  PostCollectionsAdminsConfirmEmailChangeBody,
  PostCollectionsAdminsConfirmPasswordReset200,
  PostCollectionsAdminsConfirmPasswordResetBody,
  PostCollectionsAdminsConfirmVerification200,
  PostCollectionsAdminsConfirmVerificationBody,
  PostCollectionsAdminsRecords200,
  PostCollectionsAdminsRecordsBody,
  PostCollectionsAdminsRequestEmailChange200,
  PostCollectionsAdminsRequestEmailChangeBody,
  PostCollectionsAdminsRequestPasswordReset200,
  PostCollectionsAdminsRequestPasswordResetBody,
  PostCollectionsAdminsRequestVerification200,
  PostCollectionsAdminsRequestVerificationBody
} from '../model';

import { customInstance } from '../../../lib/api/mutator/custom-instance.ts';
import type { ErrorType , BodyType } from '../../../lib/api/mutator/custom-instance.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type postCollectionsAdminsRecordsResponse200 = {
  data: PostCollectionsAdminsRecords200
  status: 200
}

export type postCollectionsAdminsRecordsResponseSuccess = (postCollectionsAdminsRecordsResponse200) & {
  headers: Headers;
};
;

export type postCollectionsAdminsRecordsResponse = (postCollectionsAdminsRecordsResponseSuccess)

export const getPostCollectionsAdminsRecordsUrl = () => {




  return `/collections/admins/records`
}

/**
 * @summary Register new Admins Collection
 */
export const postCollectionsAdminsRecords = async (postCollectionsAdminsRecordsBody?: PostCollectionsAdminsRecordsBody, options?: RequestInit): Promise<postCollectionsAdminsRecordsResponse> => {

  return customInstance<postCollectionsAdminsRecordsResponse>(getPostCollectionsAdminsRecordsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postCollectionsAdminsRecordsBody)
  }
);}





export const getPostCollectionsAdminsRecordsQueryKey = (postCollectionsAdminsRecordsBody?: BodyType<PostCollectionsAdminsRecordsBody>,) => {
    return [
    'POST', `/collections/admins/records`, postCollectionsAdminsRecordsBody
    ] as const;
    }


export const getPostCollectionsAdminsRecordsQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsAdminsRecords>>, TError = ErrorType<unknown>>(postCollectionsAdminsRecordsBody?: BodyType<PostCollectionsAdminsRecordsBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsAdminsRecordsQueryKey(postCollectionsAdminsRecordsBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsAdminsRecords>>> = ({ signal }) => postCollectionsAdminsRecords(postCollectionsAdminsRecordsBody, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRecords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsAdminsRecordsQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsAdminsRecords>>>
export type PostCollectionsAdminsRecordsQueryError = ErrorType<unknown>


export function usePostCollectionsAdminsRecords<TData = Awaited<ReturnType<typeof postCollectionsAdminsRecords>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRecordsBody: undefined |  BodyType<PostCollectionsAdminsRecordsBody>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRecords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsRecords>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsRecords<TData = Awaited<ReturnType<typeof postCollectionsAdminsRecords>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRecordsBody?: BodyType<PostCollectionsAdminsRecordsBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRecords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsRecords>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsRecords<TData = Awaited<ReturnType<typeof postCollectionsAdminsRecords>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRecordsBody?: BodyType<PostCollectionsAdminsRecordsBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Register new Admins Collection
 */

export function usePostCollectionsAdminsRecords<TData = Awaited<ReturnType<typeof postCollectionsAdminsRecords>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRecordsBody?: BodyType<PostCollectionsAdminsRecordsBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsAdminsRecordsQueryOptions(postCollectionsAdminsRecordsBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getCollectionsAdminsRecordsIdResponse200 = {
  data: AdminsRecord
  status: 200
}

export type getCollectionsAdminsRecordsIdResponseSuccess = (getCollectionsAdminsRecordsIdResponse200) & {
  headers: Headers;
};
;

export type getCollectionsAdminsRecordsIdResponse = (getCollectionsAdminsRecordsIdResponseSuccess)

export const getGetCollectionsAdminsRecordsIdUrl = (id: string,) => {




  return `/collections/admins/records/${id}`
}

/**
 * @summary Get Admins Collection by ID
 */
export const getCollectionsAdminsRecordsId = async (id: string, options?: RequestInit): Promise<getCollectionsAdminsRecordsIdResponse> => {

  return customInstance<getCollectionsAdminsRecordsIdResponse>(getGetCollectionsAdminsRecordsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsAdminsRecordsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsAdminsRecordsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsAdminsRecordsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['getCollectionsAdminsRecordsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsAdminsRecordsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  getCollectionsAdminsRecordsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsAdminsRecordsIdMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsAdminsRecordsId>>>

    export type GetCollectionsAdminsRecordsIdMutationError = ErrorType<unknown>

    /**
 * @summary Get Admins Collection by ID
 */
export const useGetCollectionsAdminsRecordsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsAdminsRecordsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsAdminsRecordsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getGetCollectionsAdminsRecordsIdMutationOptions(options), queryClient);
    }
    export type patchCollectionsAdminsRecordsIdResponse200 = {
  data: AdminsRecord
  status: 200
}

export type patchCollectionsAdminsRecordsIdResponseSuccess = (patchCollectionsAdminsRecordsIdResponse200) & {
  headers: Headers;
};
;

export type patchCollectionsAdminsRecordsIdResponse = (patchCollectionsAdminsRecordsIdResponseSuccess)

export const getPatchCollectionsAdminsRecordsIdUrl = (id: string,) => {




  return `/collections/admins/records/${id}`
}

/**
 * @summary Update Admins Collection Record
 */
export const patchCollectionsAdminsRecordsId = async (id: string,
    adminsRecord?: AdminsRecord, options?: RequestInit): Promise<patchCollectionsAdminsRecordsIdResponse> => {

  return customInstance<patchCollectionsAdminsRecordsIdResponse>(getPatchCollectionsAdminsRecordsIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(adminsRecord)
  }
);}





export const getPatchCollectionsAdminsRecordsIdQueryKey = (id: string,
    adminsRecord?: BodyType<AdminsRecord>,) => {
    return [
    'PATCH', `/collections/admins/records/${id}`, adminsRecord
    ] as const;
    }


export const getPatchCollectionsAdminsRecordsIdQueryOptions = <TData = Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>, TError = ErrorType<unknown>>(id: string,
    adminsRecord?: BodyType<AdminsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPatchCollectionsAdminsRecordsIdQueryKey(id,adminsRecord);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>> = ({ signal }) => patchCollectionsAdminsRecordsId(id,adminsRecord, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PatchCollectionsAdminsRecordsIdQueryResult = NonNullable<Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>>
export type PatchCollectionsAdminsRecordsIdQueryError = ErrorType<unknown>


export function usePatchCollectionsAdminsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    adminsRecord: undefined |  BodyType<AdminsRecord>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatchCollectionsAdminsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    adminsRecord?: BodyType<AdminsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatchCollectionsAdminsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    adminsRecord?: BodyType<AdminsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update Admins Collection Record
 */

export function usePatchCollectionsAdminsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    adminsRecord?: BodyType<AdminsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsAdminsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPatchCollectionsAdminsRecordsIdQueryOptions(id,adminsRecord,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteCollectionsAdminsRecordsIdResponse204 = {
  data: void
  status: 204
}

export type deleteCollectionsAdminsRecordsIdResponseSuccess = (deleteCollectionsAdminsRecordsIdResponse204) & {
  headers: Headers;
};
;

export type deleteCollectionsAdminsRecordsIdResponse = (deleteCollectionsAdminsRecordsIdResponseSuccess)

export const getDeleteCollectionsAdminsRecordsIdUrl = (id: string,) => {




  return `/collections/admins/records/${id}`
}

/**
 * @summary Delete Admins Collection Record
 */
export const deleteCollectionsAdminsRecordsId = async (id: string, options?: RequestInit): Promise<deleteCollectionsAdminsRecordsIdResponse> => {

  return customInstance<deleteCollectionsAdminsRecordsIdResponse>(getDeleteCollectionsAdminsRecordsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteCollectionsAdminsRecordsIdQueryKey = (id: string,) => {
    return [
    'DELETE', `/collections/admins/records/${id}`
    ] as const;
    }


export const getDeleteCollectionsAdminsRecordsIdQueryOptions = <TData = Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteCollectionsAdminsRecordsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>> = ({ signal }) => deleteCollectionsAdminsRecordsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteCollectionsAdminsRecordsIdQueryResult = NonNullable<Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>>
export type DeleteCollectionsAdminsRecordsIdQueryError = ErrorType<unknown>


export function useDeleteCollectionsAdminsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteCollectionsAdminsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteCollectionsAdminsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete Admins Collection Record
 */

export function useDeleteCollectionsAdminsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsAdminsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteCollectionsAdminsRecordsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postCollectionsAdminsAuthWithPasswordResponse200 = {
  data: PostCollectionsAdminsAuthWithPassword200
  status: 200
}

export type postCollectionsAdminsAuthWithPasswordResponseSuccess = (postCollectionsAdminsAuthWithPasswordResponse200) & {
  headers: Headers;
};
;

export type postCollectionsAdminsAuthWithPasswordResponse = (postCollectionsAdminsAuthWithPasswordResponseSuccess)

export const getPostCollectionsAdminsAuthWithPasswordUrl = () => {




  return `/collections/admins/auth-with-password`
}

/**
 * @summary Authenticate Admins Collection with password
 */
export const postCollectionsAdminsAuthWithPassword = async (postCollectionsAdminsAuthWithPasswordBody?: PostCollectionsAdminsAuthWithPasswordBody, options?: RequestInit): Promise<postCollectionsAdminsAuthWithPasswordResponse> => {

  return customInstance<postCollectionsAdminsAuthWithPasswordResponse>(getPostCollectionsAdminsAuthWithPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postCollectionsAdminsAuthWithPasswordBody)
  }
);}





export const getPostCollectionsAdminsAuthWithPasswordQueryKey = (postCollectionsAdminsAuthWithPasswordBody?: BodyType<PostCollectionsAdminsAuthWithPasswordBody>,) => {
    return [
    'POST', `/collections/admins/auth-with-password`, postCollectionsAdminsAuthWithPasswordBody
    ] as const;
    }


export const getPostCollectionsAdminsAuthWithPasswordQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>, TError = ErrorType<unknown>>(postCollectionsAdminsAuthWithPasswordBody?: BodyType<PostCollectionsAdminsAuthWithPasswordBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsAdminsAuthWithPasswordQueryKey(postCollectionsAdminsAuthWithPasswordBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>> = ({ signal }) => postCollectionsAdminsAuthWithPassword(postCollectionsAdminsAuthWithPasswordBody, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsAdminsAuthWithPasswordQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>>
export type PostCollectionsAdminsAuthWithPasswordQueryError = ErrorType<unknown>


export function usePostCollectionsAdminsAuthWithPassword<TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsAuthWithPasswordBody: undefined |  BodyType<PostCollectionsAdminsAuthWithPasswordBody>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsAuthWithPassword<TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsAuthWithPasswordBody?: BodyType<PostCollectionsAdminsAuthWithPasswordBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsAuthWithPassword<TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsAuthWithPasswordBody?: BodyType<PostCollectionsAdminsAuthWithPasswordBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Authenticate Admins Collection with password
 */

export function usePostCollectionsAdminsAuthWithPassword<TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsAuthWithPasswordBody?: BodyType<PostCollectionsAdminsAuthWithPasswordBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithPassword>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsAdminsAuthWithPasswordQueryOptions(postCollectionsAdminsAuthWithPasswordBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postCollectionsAdminsRequestVerificationResponse200 = {
  data: PostCollectionsAdminsRequestVerification200
  status: 200
}

export type postCollectionsAdminsRequestVerificationResponseSuccess = (postCollectionsAdminsRequestVerificationResponse200) & {
  headers: Headers;
};
;

export type postCollectionsAdminsRequestVerificationResponse = (postCollectionsAdminsRequestVerificationResponseSuccess)

export const getPostCollectionsAdminsRequestVerificationUrl = () => {




  return `/collections/admins/request-verification`
}

/**
 * @summary Request Admins Collection verification
 */
export const postCollectionsAdminsRequestVerification = async (postCollectionsAdminsRequestVerificationBody?: PostCollectionsAdminsRequestVerificationBody, options?: RequestInit): Promise<postCollectionsAdminsRequestVerificationResponse> => {

  return customInstance<postCollectionsAdminsRequestVerificationResponse>(getPostCollectionsAdminsRequestVerificationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postCollectionsAdminsRequestVerificationBody)
  }
);}





export const getPostCollectionsAdminsRequestVerificationQueryKey = (postCollectionsAdminsRequestVerificationBody?: BodyType<PostCollectionsAdminsRequestVerificationBody>,) => {
    return [
    'POST', `/collections/admins/request-verification`, postCollectionsAdminsRequestVerificationBody
    ] as const;
    }


export const getPostCollectionsAdminsRequestVerificationQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>, TError = ErrorType<unknown>>(postCollectionsAdminsRequestVerificationBody?: BodyType<PostCollectionsAdminsRequestVerificationBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsAdminsRequestVerificationQueryKey(postCollectionsAdminsRequestVerificationBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>> = ({ signal }) => postCollectionsAdminsRequestVerification(postCollectionsAdminsRequestVerificationBody, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsAdminsRequestVerificationQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>>
export type PostCollectionsAdminsRequestVerificationQueryError = ErrorType<unknown>


export function usePostCollectionsAdminsRequestVerification<TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRequestVerificationBody: undefined |  BodyType<PostCollectionsAdminsRequestVerificationBody>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsRequestVerification<TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRequestVerificationBody?: BodyType<PostCollectionsAdminsRequestVerificationBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsRequestVerification<TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRequestVerificationBody?: BodyType<PostCollectionsAdminsRequestVerificationBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Request Admins Collection verification
 */

export function usePostCollectionsAdminsRequestVerification<TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRequestVerificationBody?: BodyType<PostCollectionsAdminsRequestVerificationBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestVerification>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsAdminsRequestVerificationQueryOptions(postCollectionsAdminsRequestVerificationBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postCollectionsAdminsConfirmVerificationResponse200 = {
  data: PostCollectionsAdminsConfirmVerification200
  status: 200
}

export type postCollectionsAdminsConfirmVerificationResponseSuccess = (postCollectionsAdminsConfirmVerificationResponse200) & {
  headers: Headers;
};
;

export type postCollectionsAdminsConfirmVerificationResponse = (postCollectionsAdminsConfirmVerificationResponseSuccess)

export const getPostCollectionsAdminsConfirmVerificationUrl = () => {




  return `/collections/admins/confirm-verification`
}

/**
 * @summary Confirm Admins Collection verification
 */
export const postCollectionsAdminsConfirmVerification = async (postCollectionsAdminsConfirmVerificationBody?: PostCollectionsAdminsConfirmVerificationBody, options?: RequestInit): Promise<postCollectionsAdminsConfirmVerificationResponse> => {

  return customInstance<postCollectionsAdminsConfirmVerificationResponse>(getPostCollectionsAdminsConfirmVerificationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postCollectionsAdminsConfirmVerificationBody)
  }
);}





export const getPostCollectionsAdminsConfirmVerificationQueryKey = (postCollectionsAdminsConfirmVerificationBody?: BodyType<PostCollectionsAdminsConfirmVerificationBody>,) => {
    return [
    'POST', `/collections/admins/confirm-verification`, postCollectionsAdminsConfirmVerificationBody
    ] as const;
    }


export const getPostCollectionsAdminsConfirmVerificationQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>, TError = ErrorType<unknown>>(postCollectionsAdminsConfirmVerificationBody?: BodyType<PostCollectionsAdminsConfirmVerificationBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsAdminsConfirmVerificationQueryKey(postCollectionsAdminsConfirmVerificationBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>> = ({ signal }) => postCollectionsAdminsConfirmVerification(postCollectionsAdminsConfirmVerificationBody, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsAdminsConfirmVerificationQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>>
export type PostCollectionsAdminsConfirmVerificationQueryError = ErrorType<unknown>


export function usePostCollectionsAdminsConfirmVerification<TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsConfirmVerificationBody: undefined |  BodyType<PostCollectionsAdminsConfirmVerificationBody>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsConfirmVerification<TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsConfirmVerificationBody?: BodyType<PostCollectionsAdminsConfirmVerificationBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsConfirmVerification<TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsConfirmVerificationBody?: BodyType<PostCollectionsAdminsConfirmVerificationBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Confirm Admins Collection verification
 */

export function usePostCollectionsAdminsConfirmVerification<TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsConfirmVerificationBody?: BodyType<PostCollectionsAdminsConfirmVerificationBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmVerification>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsAdminsConfirmVerificationQueryOptions(postCollectionsAdminsConfirmVerificationBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postCollectionsAdminsRequestPasswordResetResponse200 = {
  data: PostCollectionsAdminsRequestPasswordReset200
  status: 200
}

export type postCollectionsAdminsRequestPasswordResetResponseSuccess = (postCollectionsAdminsRequestPasswordResetResponse200) & {
  headers: Headers;
};
;

export type postCollectionsAdminsRequestPasswordResetResponse = (postCollectionsAdminsRequestPasswordResetResponseSuccess)

export const getPostCollectionsAdminsRequestPasswordResetUrl = () => {




  return `/collections/admins/request-password-reset`
}

/**
 * @summary Request Admins Collection password reset
 */
export const postCollectionsAdminsRequestPasswordReset = async (postCollectionsAdminsRequestPasswordResetBody?: PostCollectionsAdminsRequestPasswordResetBody, options?: RequestInit): Promise<postCollectionsAdminsRequestPasswordResetResponse> => {

  return customInstance<postCollectionsAdminsRequestPasswordResetResponse>(getPostCollectionsAdminsRequestPasswordResetUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postCollectionsAdminsRequestPasswordResetBody)
  }
);}





export const getPostCollectionsAdminsRequestPasswordResetQueryKey = (postCollectionsAdminsRequestPasswordResetBody?: BodyType<PostCollectionsAdminsRequestPasswordResetBody>,) => {
    return [
    'POST', `/collections/admins/request-password-reset`, postCollectionsAdminsRequestPasswordResetBody
    ] as const;
    }


export const getPostCollectionsAdminsRequestPasswordResetQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>, TError = ErrorType<unknown>>(postCollectionsAdminsRequestPasswordResetBody?: BodyType<PostCollectionsAdminsRequestPasswordResetBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsAdminsRequestPasswordResetQueryKey(postCollectionsAdminsRequestPasswordResetBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>> = ({ signal }) => postCollectionsAdminsRequestPasswordReset(postCollectionsAdminsRequestPasswordResetBody, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsAdminsRequestPasswordResetQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>>
export type PostCollectionsAdminsRequestPasswordResetQueryError = ErrorType<unknown>


export function usePostCollectionsAdminsRequestPasswordReset<TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRequestPasswordResetBody: undefined |  BodyType<PostCollectionsAdminsRequestPasswordResetBody>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsRequestPasswordReset<TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRequestPasswordResetBody?: BodyType<PostCollectionsAdminsRequestPasswordResetBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsRequestPasswordReset<TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRequestPasswordResetBody?: BodyType<PostCollectionsAdminsRequestPasswordResetBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Request Admins Collection password reset
 */

export function usePostCollectionsAdminsRequestPasswordReset<TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRequestPasswordResetBody?: BodyType<PostCollectionsAdminsRequestPasswordResetBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestPasswordReset>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsAdminsRequestPasswordResetQueryOptions(postCollectionsAdminsRequestPasswordResetBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postCollectionsAdminsConfirmPasswordResetResponse200 = {
  data: PostCollectionsAdminsConfirmPasswordReset200
  status: 200
}

export type postCollectionsAdminsConfirmPasswordResetResponseSuccess = (postCollectionsAdminsConfirmPasswordResetResponse200) & {
  headers: Headers;
};
;

export type postCollectionsAdminsConfirmPasswordResetResponse = (postCollectionsAdminsConfirmPasswordResetResponseSuccess)

export const getPostCollectionsAdminsConfirmPasswordResetUrl = () => {




  return `/collections/admins/confirm-password-reset`
}

/**
 * @summary Confirm Admins Collection password reset
 */
export const postCollectionsAdminsConfirmPasswordReset = async (postCollectionsAdminsConfirmPasswordResetBody?: PostCollectionsAdminsConfirmPasswordResetBody, options?: RequestInit): Promise<postCollectionsAdminsConfirmPasswordResetResponse> => {

  return customInstance<postCollectionsAdminsConfirmPasswordResetResponse>(getPostCollectionsAdminsConfirmPasswordResetUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postCollectionsAdminsConfirmPasswordResetBody)
  }
);}





export const getPostCollectionsAdminsConfirmPasswordResetQueryKey = (postCollectionsAdminsConfirmPasswordResetBody?: BodyType<PostCollectionsAdminsConfirmPasswordResetBody>,) => {
    return [
    'POST', `/collections/admins/confirm-password-reset`, postCollectionsAdminsConfirmPasswordResetBody
    ] as const;
    }


export const getPostCollectionsAdminsConfirmPasswordResetQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>, TError = ErrorType<unknown>>(postCollectionsAdminsConfirmPasswordResetBody?: BodyType<PostCollectionsAdminsConfirmPasswordResetBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsAdminsConfirmPasswordResetQueryKey(postCollectionsAdminsConfirmPasswordResetBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>> = ({ signal }) => postCollectionsAdminsConfirmPasswordReset(postCollectionsAdminsConfirmPasswordResetBody, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsAdminsConfirmPasswordResetQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>>
export type PostCollectionsAdminsConfirmPasswordResetQueryError = ErrorType<unknown>


export function usePostCollectionsAdminsConfirmPasswordReset<TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsConfirmPasswordResetBody: undefined |  BodyType<PostCollectionsAdminsConfirmPasswordResetBody>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsConfirmPasswordReset<TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsConfirmPasswordResetBody?: BodyType<PostCollectionsAdminsConfirmPasswordResetBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsConfirmPasswordReset<TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsConfirmPasswordResetBody?: BodyType<PostCollectionsAdminsConfirmPasswordResetBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Confirm Admins Collection password reset
 */

export function usePostCollectionsAdminsConfirmPasswordReset<TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsConfirmPasswordResetBody?: BodyType<PostCollectionsAdminsConfirmPasswordResetBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmPasswordReset>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsAdminsConfirmPasswordResetQueryOptions(postCollectionsAdminsConfirmPasswordResetBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postCollectionsAdminsRequestEmailChangeResponse200 = {
  data: PostCollectionsAdminsRequestEmailChange200
  status: 200
}

export type postCollectionsAdminsRequestEmailChangeResponseSuccess = (postCollectionsAdminsRequestEmailChangeResponse200) & {
  headers: Headers;
};
;

export type postCollectionsAdminsRequestEmailChangeResponse = (postCollectionsAdminsRequestEmailChangeResponseSuccess)

export const getPostCollectionsAdminsRequestEmailChangeUrl = () => {




  return `/collections/admins/request-email-change`
}

/**
 * @summary Request Admins Collection email change
 */
export const postCollectionsAdminsRequestEmailChange = async (postCollectionsAdminsRequestEmailChangeBody?: PostCollectionsAdminsRequestEmailChangeBody, options?: RequestInit): Promise<postCollectionsAdminsRequestEmailChangeResponse> => {

  return customInstance<postCollectionsAdminsRequestEmailChangeResponse>(getPostCollectionsAdminsRequestEmailChangeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postCollectionsAdminsRequestEmailChangeBody)
  }
);}





export const getPostCollectionsAdminsRequestEmailChangeQueryKey = (postCollectionsAdminsRequestEmailChangeBody?: BodyType<PostCollectionsAdminsRequestEmailChangeBody>,) => {
    return [
    'POST', `/collections/admins/request-email-change`, postCollectionsAdminsRequestEmailChangeBody
    ] as const;
    }


export const getPostCollectionsAdminsRequestEmailChangeQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>, TError = ErrorType<unknown>>(postCollectionsAdminsRequestEmailChangeBody?: BodyType<PostCollectionsAdminsRequestEmailChangeBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsAdminsRequestEmailChangeQueryKey(postCollectionsAdminsRequestEmailChangeBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>> = ({ signal }) => postCollectionsAdminsRequestEmailChange(postCollectionsAdminsRequestEmailChangeBody, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsAdminsRequestEmailChangeQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>>
export type PostCollectionsAdminsRequestEmailChangeQueryError = ErrorType<unknown>


export function usePostCollectionsAdminsRequestEmailChange<TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRequestEmailChangeBody: undefined |  BodyType<PostCollectionsAdminsRequestEmailChangeBody>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsRequestEmailChange<TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRequestEmailChangeBody?: BodyType<PostCollectionsAdminsRequestEmailChangeBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsRequestEmailChange<TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRequestEmailChangeBody?: BodyType<PostCollectionsAdminsRequestEmailChangeBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Request Admins Collection email change
 */

export function usePostCollectionsAdminsRequestEmailChange<TData = Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsRequestEmailChangeBody?: BodyType<PostCollectionsAdminsRequestEmailChangeBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsRequestEmailChange>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsAdminsRequestEmailChangeQueryOptions(postCollectionsAdminsRequestEmailChangeBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postCollectionsAdminsConfirmEmailChangeResponse200 = {
  data: PostCollectionsAdminsConfirmEmailChange200
  status: 200
}

export type postCollectionsAdminsConfirmEmailChangeResponseSuccess = (postCollectionsAdminsConfirmEmailChangeResponse200) & {
  headers: Headers;
};
;

export type postCollectionsAdminsConfirmEmailChangeResponse = (postCollectionsAdminsConfirmEmailChangeResponseSuccess)

export const getPostCollectionsAdminsConfirmEmailChangeUrl = () => {




  return `/collections/admins/confirm-email-change`
}

/**
 * @summary Confirm Admins Collection email change
 */
export const postCollectionsAdminsConfirmEmailChange = async (postCollectionsAdminsConfirmEmailChangeBody?: PostCollectionsAdminsConfirmEmailChangeBody, options?: RequestInit): Promise<postCollectionsAdminsConfirmEmailChangeResponse> => {

  return customInstance<postCollectionsAdminsConfirmEmailChangeResponse>(getPostCollectionsAdminsConfirmEmailChangeUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postCollectionsAdminsConfirmEmailChangeBody)
  }
);}





export const getPostCollectionsAdminsConfirmEmailChangeQueryKey = (postCollectionsAdminsConfirmEmailChangeBody?: BodyType<PostCollectionsAdminsConfirmEmailChangeBody>,) => {
    return [
    'POST', `/collections/admins/confirm-email-change`, postCollectionsAdminsConfirmEmailChangeBody
    ] as const;
    }


export const getPostCollectionsAdminsConfirmEmailChangeQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>, TError = ErrorType<unknown>>(postCollectionsAdminsConfirmEmailChangeBody?: BodyType<PostCollectionsAdminsConfirmEmailChangeBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsAdminsConfirmEmailChangeQueryKey(postCollectionsAdminsConfirmEmailChangeBody);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>> = ({ signal }) => postCollectionsAdminsConfirmEmailChange(postCollectionsAdminsConfirmEmailChangeBody, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsAdminsConfirmEmailChangeQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>>
export type PostCollectionsAdminsConfirmEmailChangeQueryError = ErrorType<unknown>


export function usePostCollectionsAdminsConfirmEmailChange<TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsConfirmEmailChangeBody: undefined |  BodyType<PostCollectionsAdminsConfirmEmailChangeBody>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsConfirmEmailChange<TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsConfirmEmailChangeBody?: BodyType<PostCollectionsAdminsConfirmEmailChangeBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsConfirmEmailChange<TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsConfirmEmailChangeBody?: BodyType<PostCollectionsAdminsConfirmEmailChangeBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Confirm Admins Collection email change
 */

export function usePostCollectionsAdminsConfirmEmailChange<TData = Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsConfirmEmailChangeBody?: BodyType<PostCollectionsAdminsConfirmEmailChangeBody>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsConfirmEmailChange>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsAdminsConfirmEmailChangeQueryOptions(postCollectionsAdminsConfirmEmailChangeBody,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postCollectionsAdminsAuthRefreshResponse200 = {
  data: PostCollectionsAdminsAuthRefresh200
  status: 200
}

export type postCollectionsAdminsAuthRefreshResponseSuccess = (postCollectionsAdminsAuthRefreshResponse200) & {
  headers: Headers;
};
;

export type postCollectionsAdminsAuthRefreshResponse = (postCollectionsAdminsAuthRefreshResponseSuccess)

export const getPostCollectionsAdminsAuthRefreshUrl = () => {




  return `/collections/admins/auth-refresh`
}

/**
 * @summary Refresh Admins Collection authentication token
 */
export const postCollectionsAdminsAuthRefresh = async ( options?: RequestInit): Promise<postCollectionsAdminsAuthRefreshResponse> => {

  return customInstance<postCollectionsAdminsAuthRefreshResponse>(getPostCollectionsAdminsAuthRefreshUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostCollectionsAdminsAuthRefreshQueryKey = () => {
    return [
    'POST', `/collections/admins/auth-refresh`
    ] as const;
    }


export const getPostCollectionsAdminsAuthRefreshQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsAdminsAuthRefreshQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>> = ({ signal }) => postCollectionsAdminsAuthRefresh({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsAdminsAuthRefreshQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>>
export type PostCollectionsAdminsAuthRefreshQueryError = ErrorType<unknown>


export function usePostCollectionsAdminsAuthRefresh<TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsAuthRefresh<TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsAuthRefresh<TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Refresh Admins Collection authentication token
 */

export function usePostCollectionsAdminsAuthRefresh<TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthRefresh>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsAdminsAuthRefreshQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type postCollectionsAdminsAuthWithOauth2Response200 = {
  data: PostCollectionsAdminsAuthWithOauth2200
  status: 200
}

export type postCollectionsAdminsAuthWithOauth2ResponseSuccess = (postCollectionsAdminsAuthWithOauth2Response200) & {
  headers: Headers;
};
;

export type postCollectionsAdminsAuthWithOauth2Response = (postCollectionsAdminsAuthWithOauth2ResponseSuccess)

export const getPostCollectionsAdminsAuthWithOauth2Url = () => {




  return `/collections/admins/auth-with-oauth2`
}

/**
 * @summary Authenticate Admins Collection with OAuth2
 */
export const postCollectionsAdminsAuthWithOauth2 = async (postCollectionsAdminsAuthWithOauth2Body?: PostCollectionsAdminsAuthWithOauth2Body, options?: RequestInit): Promise<postCollectionsAdminsAuthWithOauth2Response> => {

  return customInstance<postCollectionsAdminsAuthWithOauth2Response>(getPostCollectionsAdminsAuthWithOauth2Url(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(postCollectionsAdminsAuthWithOauth2Body)
  }
);}





export const getPostCollectionsAdminsAuthWithOauth2QueryKey = (postCollectionsAdminsAuthWithOauth2Body?: BodyType<PostCollectionsAdminsAuthWithOauth2Body>,) => {
    return [
    'POST', `/collections/admins/auth-with-oauth2`, postCollectionsAdminsAuthWithOauth2Body
    ] as const;
    }


export const getPostCollectionsAdminsAuthWithOauth2QueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>, TError = ErrorType<unknown>>(postCollectionsAdminsAuthWithOauth2Body?: BodyType<PostCollectionsAdminsAuthWithOauth2Body>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsAdminsAuthWithOauth2QueryKey(postCollectionsAdminsAuthWithOauth2Body);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>> = ({ signal }) => postCollectionsAdminsAuthWithOauth2(postCollectionsAdminsAuthWithOauth2Body, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsAdminsAuthWithOauth2QueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>>
export type PostCollectionsAdminsAuthWithOauth2QueryError = ErrorType<unknown>


export function usePostCollectionsAdminsAuthWithOauth2<TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsAuthWithOauth2Body: undefined |  BodyType<PostCollectionsAdminsAuthWithOauth2Body>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsAuthWithOauth2<TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsAuthWithOauth2Body?: BodyType<PostCollectionsAdminsAuthWithOauth2Body>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsAdminsAuthWithOauth2<TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsAuthWithOauth2Body?: BodyType<PostCollectionsAdminsAuthWithOauth2Body>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Authenticate Admins Collection with OAuth2
 */

export function usePostCollectionsAdminsAuthWithOauth2<TData = Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>, TError = ErrorType<unknown>>(
 postCollectionsAdminsAuthWithOauth2Body?: BodyType<PostCollectionsAdminsAuthWithOauth2Body>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsAdminsAuthWithOauth2>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsAdminsAuthWithOauth2QueryOptions(postCollectionsAdminsAuthWithOauth2Body,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






