/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCollectionsMatchDraftsRecords200,
  GetCollectionsMatchDraftsRecordsIdParams,
  GetCollectionsMatchDraftsRecordsParams,
  MatchDraftsRecord
} from '../model';

import { customInstance } from '../../../lib/api/mutator/custom-instance.ts';
import type { ErrorType , BodyType } from '../../../lib/api/mutator/custom-instance.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getCollectionsMatchDraftsRecordsResponse200 = {
  data: GetCollectionsMatchDraftsRecords200
  status: 200
}

export type getCollectionsMatchDraftsRecordsResponseSuccess = (getCollectionsMatchDraftsRecordsResponse200) & {
  headers: Headers;
};
;

export type getCollectionsMatchDraftsRecordsResponse = (getCollectionsMatchDraftsRecordsResponseSuccess)

export const getGetCollectionsMatchDraftsRecordsUrl = (params?: GetCollectionsMatchDraftsRecordsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collections/match_drafts/records?${stringifiedParams}` : `/collections/match_drafts/records`
}

/**
 * Retrieves a paginated list of Match_drafts Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Match_drafts Collection
 */
export const getCollectionsMatchDraftsRecords = async (params?: GetCollectionsMatchDraftsRecordsParams, options?: RequestInit): Promise<getCollectionsMatchDraftsRecordsResponse> => {

  return customInstance<getCollectionsMatchDraftsRecordsResponse>(getGetCollectionsMatchDraftsRecordsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsMatchDraftsRecordsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsMatchDraftsRecords>>, TError,{params?: GetCollectionsMatchDraftsRecordsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsMatchDraftsRecords>>, TError,{params?: GetCollectionsMatchDraftsRecordsParams}, TContext> => {

const mutationKey = ['getCollectionsMatchDraftsRecords'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsMatchDraftsRecords>>, {params?: GetCollectionsMatchDraftsRecordsParams}> = (props) => {
          const {params} = props ?? {};

          return  getCollectionsMatchDraftsRecords(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsMatchDraftsRecordsMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsMatchDraftsRecords>>>

    export type GetCollectionsMatchDraftsRecordsMutationError = ErrorType<unknown>

    /**
 * @summary List Match_drafts Collection
 */
export const useGetCollectionsMatchDraftsRecords = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsMatchDraftsRecords>>, TError,{params?: GetCollectionsMatchDraftsRecordsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsMatchDraftsRecords>>,
        TError,
        {params?: GetCollectionsMatchDraftsRecordsParams},
        TContext
      > => {
      return useMutation(getGetCollectionsMatchDraftsRecordsMutationOptions(options), queryClient);
    }
    export type postCollectionsMatchDraftsRecordsResponse200 = {
  data: MatchDraftsRecord
  status: 200
}

export type postCollectionsMatchDraftsRecordsResponseSuccess = (postCollectionsMatchDraftsRecordsResponse200) & {
  headers: Headers;
};
;

export type postCollectionsMatchDraftsRecordsResponse = (postCollectionsMatchDraftsRecordsResponseSuccess)

export const getPostCollectionsMatchDraftsRecordsUrl = () => {




  return `/collections/match_drafts/records`
}

/**
 * @summary Create Match_drafts Collection Record
 */
export const postCollectionsMatchDraftsRecords = async (matchDraftsRecord?: MatchDraftsRecord, options?: RequestInit): Promise<postCollectionsMatchDraftsRecordsResponse> => {

  return customInstance<postCollectionsMatchDraftsRecordsResponse>(getPostCollectionsMatchDraftsRecordsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(matchDraftsRecord)
  }
);}





export const getPostCollectionsMatchDraftsRecordsQueryKey = (matchDraftsRecord?: BodyType<MatchDraftsRecord>,) => {
    return [
    'POST', `/collections/match_drafts/records`, matchDraftsRecord
    ] as const;
    }


export const getPostCollectionsMatchDraftsRecordsQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>, TError = ErrorType<unknown>>(matchDraftsRecord?: BodyType<MatchDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsMatchDraftsRecordsQueryKey(matchDraftsRecord);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>> = ({ signal }) => postCollectionsMatchDraftsRecords(matchDraftsRecord, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsMatchDraftsRecordsQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>>
export type PostCollectionsMatchDraftsRecordsQueryError = ErrorType<unknown>


export function usePostCollectionsMatchDraftsRecords<TData = Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>, TError = ErrorType<unknown>>(
 matchDraftsRecord: undefined |  BodyType<MatchDraftsRecord>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsMatchDraftsRecords<TData = Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>, TError = ErrorType<unknown>>(
 matchDraftsRecord?: BodyType<MatchDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsMatchDraftsRecords<TData = Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>, TError = ErrorType<unknown>>(
 matchDraftsRecord?: BodyType<MatchDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create Match_drafts Collection Record
 */

export function usePostCollectionsMatchDraftsRecords<TData = Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>, TError = ErrorType<unknown>>(
 matchDraftsRecord?: BodyType<MatchDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsMatchDraftsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsMatchDraftsRecordsQueryOptions(matchDraftsRecord,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getCollectionsMatchDraftsRecordsIdResponse200 = {
  data: MatchDraftsRecord
  status: 200
}

export type getCollectionsMatchDraftsRecordsIdResponseSuccess = (getCollectionsMatchDraftsRecordsIdResponse200) & {
  headers: Headers;
};
;

export type getCollectionsMatchDraftsRecordsIdResponse = (getCollectionsMatchDraftsRecordsIdResponseSuccess)

export const getGetCollectionsMatchDraftsRecordsIdUrl = (id: string,
    params?: GetCollectionsMatchDraftsRecordsIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collections/match_drafts/records/${id}?${stringifiedParams}` : `/collections/match_drafts/records/${id}`
}

/**
 * @summary Get Match_drafts Collection by ID
 */
export const getCollectionsMatchDraftsRecordsId = async (id: string,
    params?: GetCollectionsMatchDraftsRecordsIdParams, options?: RequestInit): Promise<getCollectionsMatchDraftsRecordsIdResponse> => {

  return customInstance<getCollectionsMatchDraftsRecordsIdResponse>(getGetCollectionsMatchDraftsRecordsIdUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsMatchDraftsRecordsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsMatchDraftsRecordsId>>, TError,{id: string;params?: GetCollectionsMatchDraftsRecordsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsMatchDraftsRecordsId>>, TError,{id: string;params?: GetCollectionsMatchDraftsRecordsIdParams}, TContext> => {

const mutationKey = ['getCollectionsMatchDraftsRecordsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsMatchDraftsRecordsId>>, {id: string;params?: GetCollectionsMatchDraftsRecordsIdParams}> = (props) => {
          const {id,params} = props ?? {};

          return  getCollectionsMatchDraftsRecordsId(id,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsMatchDraftsRecordsIdMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsMatchDraftsRecordsId>>>

    export type GetCollectionsMatchDraftsRecordsIdMutationError = ErrorType<unknown>

    /**
 * @summary Get Match_drafts Collection by ID
 */
export const useGetCollectionsMatchDraftsRecordsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsMatchDraftsRecordsId>>, TError,{id: string;params?: GetCollectionsMatchDraftsRecordsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsMatchDraftsRecordsId>>,
        TError,
        {id: string;params?: GetCollectionsMatchDraftsRecordsIdParams},
        TContext
      > => {
      return useMutation(getGetCollectionsMatchDraftsRecordsIdMutationOptions(options), queryClient);
    }
    export type patchCollectionsMatchDraftsRecordsIdResponse200 = {
  data: MatchDraftsRecord
  status: 200
}

export type patchCollectionsMatchDraftsRecordsIdResponseSuccess = (patchCollectionsMatchDraftsRecordsIdResponse200) & {
  headers: Headers;
};
;

export type patchCollectionsMatchDraftsRecordsIdResponse = (patchCollectionsMatchDraftsRecordsIdResponseSuccess)

export const getPatchCollectionsMatchDraftsRecordsIdUrl = (id: string,) => {




  return `/collections/match_drafts/records/${id}`
}

/**
 * @summary Update Match_drafts Collection Record
 */
export const patchCollectionsMatchDraftsRecordsId = async (id: string,
    matchDraftsRecord?: MatchDraftsRecord, options?: RequestInit): Promise<patchCollectionsMatchDraftsRecordsIdResponse> => {

  return customInstance<patchCollectionsMatchDraftsRecordsIdResponse>(getPatchCollectionsMatchDraftsRecordsIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(matchDraftsRecord)
  }
);}





export const getPatchCollectionsMatchDraftsRecordsIdQueryKey = (id: string,
    matchDraftsRecord?: BodyType<MatchDraftsRecord>,) => {
    return [
    'PATCH', `/collections/match_drafts/records/${id}`, matchDraftsRecord
    ] as const;
    }


export const getPatchCollectionsMatchDraftsRecordsIdQueryOptions = <TData = Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>, TError = ErrorType<unknown>>(id: string,
    matchDraftsRecord?: BodyType<MatchDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPatchCollectionsMatchDraftsRecordsIdQueryKey(id,matchDraftsRecord);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>> = ({ signal }) => patchCollectionsMatchDraftsRecordsId(id,matchDraftsRecord, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PatchCollectionsMatchDraftsRecordsIdQueryResult = NonNullable<Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>>
export type PatchCollectionsMatchDraftsRecordsIdQueryError = ErrorType<unknown>


export function usePatchCollectionsMatchDraftsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    matchDraftsRecord: undefined |  BodyType<MatchDraftsRecord>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatchCollectionsMatchDraftsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    matchDraftsRecord?: BodyType<MatchDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatchCollectionsMatchDraftsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    matchDraftsRecord?: BodyType<MatchDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update Match_drafts Collection Record
 */

export function usePatchCollectionsMatchDraftsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    matchDraftsRecord?: BodyType<MatchDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsMatchDraftsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPatchCollectionsMatchDraftsRecordsIdQueryOptions(id,matchDraftsRecord,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteCollectionsMatchDraftsRecordsIdResponse204 = {
  data: void
  status: 204
}

export type deleteCollectionsMatchDraftsRecordsIdResponseSuccess = (deleteCollectionsMatchDraftsRecordsIdResponse204) & {
  headers: Headers;
};
;

export type deleteCollectionsMatchDraftsRecordsIdResponse = (deleteCollectionsMatchDraftsRecordsIdResponseSuccess)

export const getDeleteCollectionsMatchDraftsRecordsIdUrl = (id: string,) => {




  return `/collections/match_drafts/records/${id}`
}

/**
 * @summary Delete Match_drafts Collection Record
 */
export const deleteCollectionsMatchDraftsRecordsId = async (id: string, options?: RequestInit): Promise<deleteCollectionsMatchDraftsRecordsIdResponse> => {

  return customInstance<deleteCollectionsMatchDraftsRecordsIdResponse>(getDeleteCollectionsMatchDraftsRecordsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteCollectionsMatchDraftsRecordsIdQueryKey = (id: string,) => {
    return [
    'DELETE', `/collections/match_drafts/records/${id}`
    ] as const;
    }


export const getDeleteCollectionsMatchDraftsRecordsIdQueryOptions = <TData = Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteCollectionsMatchDraftsRecordsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>> = ({ signal }) => deleteCollectionsMatchDraftsRecordsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteCollectionsMatchDraftsRecordsIdQueryResult = NonNullable<Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>>
export type DeleteCollectionsMatchDraftsRecordsIdQueryError = ErrorType<unknown>


export function useDeleteCollectionsMatchDraftsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteCollectionsMatchDraftsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteCollectionsMatchDraftsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete Match_drafts Collection Record
 */

export function useDeleteCollectionsMatchDraftsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsMatchDraftsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteCollectionsMatchDraftsRecordsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






