/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Retrieves a paginated list of Audit_log Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Audit_log Collection
 */
export const getCollectionsAuditLogRecordsQueryPageDefault = 1;

export const getCollectionsAuditLogRecordsQueryPerPageDefault = 30;
export const getCollectionsAuditLogRecordsQueryPerPageMax = 500;

export const getCollectionsAuditLogRecordsQuerySkipTotalDefault = false;

export const GetCollectionsAuditLogRecordsQueryParams = zod.object({
  "filter": zod.string().optional().describe('Filtering expression (e.g., \'created > \"2022-01-01\"\')'),
  "sort": zod.string().optional().describe('Comma-separated list of fields to sort by. Prefix with \'-\' for descending order.'),
  "page": zod.number().min(1).default(getCollectionsAuditLogRecordsQueryPageDefault).describe('Page number (starting from 1)'),
  "perPage": zod.number().min(1).max(getCollectionsAuditLogRecordsQueryPerPageMax).default(getCollectionsAuditLogRecordsQueryPerPageDefault).describe('Number of records per page (max 500)'),
  "skipTotal": zod.boolean().default(getCollectionsAuditLogRecordsQuerySkipTotalDefault).describe('Set to true to skip the total count (improves performance for large collections)'),
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsAuditLogRecordsResponse = zod.object({
  "page": zod.number().optional(),
  "perPage": zod.number().optional(),
  "totalItems": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "items": zod.array(zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "table_name": zod.string().optional(),
  "record_id": zod.string().optional(),
  "key_field": zod.string().optional(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})).optional()
})

/**
 * @summary Create Audit_log Collection Record
 */
export const PostCollectionsAuditLogRecordsBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "table_name": zod.string().optional(),
  "record_id": zod.string().optional(),
  "key_field": zod.string().optional(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const PostCollectionsAuditLogRecordsResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "table_name": zod.string().optional(),
  "record_id": zod.string().optional(),
  "key_field": zod.string().optional(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Get Audit_log Collection by ID
 */
export const GetCollectionsAuditLogRecordsIdParams = zod.object({
  "id": zod.string()
})

export const GetCollectionsAuditLogRecordsIdQueryParams = zod.object({
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsAuditLogRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "table_name": zod.string().optional(),
  "record_id": zod.string().optional(),
  "key_field": zod.string().optional(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Update Audit_log Collection Record
 */
export const PatchCollectionsAuditLogRecordsIdParams = zod.object({
  "id": zod.string()
})

export const PatchCollectionsAuditLogRecordsIdBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "table_name": zod.string().optional(),
  "record_id": zod.string().optional(),
  "key_field": zod.string().optional(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const PatchCollectionsAuditLogRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "table_name": zod.string().optional(),
  "record_id": zod.string().optional(),
  "key_field": zod.string().optional(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Delete Audit_log Collection Record
 */
export const DeleteCollectionsAuditLogRecordsIdParams = zod.object({
  "id": zod.string()
})

export const DeleteCollectionsAuditLogRecordsIdResponse = zod.void()

