/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCollectionsMatchesRecords200,
  GetCollectionsMatchesRecordsIdParams,
  GetCollectionsMatchesRecordsParams,
  MatchesRecord
} from '../model';

import { customInstance } from '../../../lib/api/mutator/custom-instance.ts';
import type { ErrorType , BodyType } from '../../../lib/api/mutator/custom-instance.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getCollectionsMatchesRecordsResponse200 = {
  data: GetCollectionsMatchesRecords200
  status: 200
}

export type getCollectionsMatchesRecordsResponseSuccess = (getCollectionsMatchesRecordsResponse200) & {
  headers: Headers;
};
;

export type getCollectionsMatchesRecordsResponse = (getCollectionsMatchesRecordsResponseSuccess)

export const getGetCollectionsMatchesRecordsUrl = (params?: GetCollectionsMatchesRecordsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collections/matches/records?${stringifiedParams}` : `/collections/matches/records`
}

/**
 * Retrieves a paginated list of Matches Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Matches Collection
 */
export const getCollectionsMatchesRecords = async (params?: GetCollectionsMatchesRecordsParams, options?: RequestInit): Promise<getCollectionsMatchesRecordsResponse> => {

  return customInstance<getCollectionsMatchesRecordsResponse>(getGetCollectionsMatchesRecordsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsMatchesRecordsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsMatchesRecords>>, TError,{params?: GetCollectionsMatchesRecordsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsMatchesRecords>>, TError,{params?: GetCollectionsMatchesRecordsParams}, TContext> => {

const mutationKey = ['getCollectionsMatchesRecords'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsMatchesRecords>>, {params?: GetCollectionsMatchesRecordsParams}> = (props) => {
          const {params} = props ?? {};

          return  getCollectionsMatchesRecords(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsMatchesRecordsMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsMatchesRecords>>>

    export type GetCollectionsMatchesRecordsMutationError = ErrorType<unknown>

    /**
 * @summary List Matches Collection
 */
export const useGetCollectionsMatchesRecords = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsMatchesRecords>>, TError,{params?: GetCollectionsMatchesRecordsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsMatchesRecords>>,
        TError,
        {params?: GetCollectionsMatchesRecordsParams},
        TContext
      > => {
      return useMutation(getGetCollectionsMatchesRecordsMutationOptions(options), queryClient);
    }
    export type postCollectionsMatchesRecordsResponse200 = {
  data: MatchesRecord
  status: 200
}

export type postCollectionsMatchesRecordsResponseSuccess = (postCollectionsMatchesRecordsResponse200) & {
  headers: Headers;
};
;

export type postCollectionsMatchesRecordsResponse = (postCollectionsMatchesRecordsResponseSuccess)

export const getPostCollectionsMatchesRecordsUrl = () => {




  return `/collections/matches/records`
}

/**
 * @summary Create Matches Collection Record
 */
export const postCollectionsMatchesRecords = async (matchesRecord?: MatchesRecord, options?: RequestInit): Promise<postCollectionsMatchesRecordsResponse> => {

  return customInstance<postCollectionsMatchesRecordsResponse>(getPostCollectionsMatchesRecordsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(matchesRecord)
  }
);}





export const getPostCollectionsMatchesRecordsQueryKey = (matchesRecord?: BodyType<MatchesRecord>,) => {
    return [
    'POST', `/collections/matches/records`, matchesRecord
    ] as const;
    }


export const getPostCollectionsMatchesRecordsQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsMatchesRecords>>, TError = ErrorType<unknown>>(matchesRecord?: BodyType<MatchesRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsMatchesRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsMatchesRecordsQueryKey(matchesRecord);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsMatchesRecords>>> = ({ signal }) => postCollectionsMatchesRecords(matchesRecord, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsMatchesRecords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsMatchesRecordsQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsMatchesRecords>>>
export type PostCollectionsMatchesRecordsQueryError = ErrorType<unknown>


export function usePostCollectionsMatchesRecords<TData = Awaited<ReturnType<typeof postCollectionsMatchesRecords>>, TError = ErrorType<unknown>>(
 matchesRecord: undefined |  BodyType<MatchesRecord>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsMatchesRecords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsMatchesRecords>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsMatchesRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsMatchesRecords<TData = Awaited<ReturnType<typeof postCollectionsMatchesRecords>>, TError = ErrorType<unknown>>(
 matchesRecord?: BodyType<MatchesRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsMatchesRecords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsMatchesRecords>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsMatchesRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsMatchesRecords<TData = Awaited<ReturnType<typeof postCollectionsMatchesRecords>>, TError = ErrorType<unknown>>(
 matchesRecord?: BodyType<MatchesRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsMatchesRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create Matches Collection Record
 */

export function usePostCollectionsMatchesRecords<TData = Awaited<ReturnType<typeof postCollectionsMatchesRecords>>, TError = ErrorType<unknown>>(
 matchesRecord?: BodyType<MatchesRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsMatchesRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsMatchesRecordsQueryOptions(matchesRecord,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getCollectionsMatchesRecordsIdResponse200 = {
  data: MatchesRecord
  status: 200
}

export type getCollectionsMatchesRecordsIdResponseSuccess = (getCollectionsMatchesRecordsIdResponse200) & {
  headers: Headers;
};
;

export type getCollectionsMatchesRecordsIdResponse = (getCollectionsMatchesRecordsIdResponseSuccess)

export const getGetCollectionsMatchesRecordsIdUrl = (id: string,
    params?: GetCollectionsMatchesRecordsIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collections/matches/records/${id}?${stringifiedParams}` : `/collections/matches/records/${id}`
}

/**
 * @summary Get Matches Collection by ID
 */
export const getCollectionsMatchesRecordsId = async (id: string,
    params?: GetCollectionsMatchesRecordsIdParams, options?: RequestInit): Promise<getCollectionsMatchesRecordsIdResponse> => {

  return customInstance<getCollectionsMatchesRecordsIdResponse>(getGetCollectionsMatchesRecordsIdUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsMatchesRecordsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsMatchesRecordsId>>, TError,{id: string;params?: GetCollectionsMatchesRecordsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsMatchesRecordsId>>, TError,{id: string;params?: GetCollectionsMatchesRecordsIdParams}, TContext> => {

const mutationKey = ['getCollectionsMatchesRecordsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsMatchesRecordsId>>, {id: string;params?: GetCollectionsMatchesRecordsIdParams}> = (props) => {
          const {id,params} = props ?? {};

          return  getCollectionsMatchesRecordsId(id,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsMatchesRecordsIdMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsMatchesRecordsId>>>

    export type GetCollectionsMatchesRecordsIdMutationError = ErrorType<unknown>

    /**
 * @summary Get Matches Collection by ID
 */
export const useGetCollectionsMatchesRecordsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsMatchesRecordsId>>, TError,{id: string;params?: GetCollectionsMatchesRecordsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsMatchesRecordsId>>,
        TError,
        {id: string;params?: GetCollectionsMatchesRecordsIdParams},
        TContext
      > => {
      return useMutation(getGetCollectionsMatchesRecordsIdMutationOptions(options), queryClient);
    }
    export type patchCollectionsMatchesRecordsIdResponse200 = {
  data: MatchesRecord
  status: 200
}

export type patchCollectionsMatchesRecordsIdResponseSuccess = (patchCollectionsMatchesRecordsIdResponse200) & {
  headers: Headers;
};
;

export type patchCollectionsMatchesRecordsIdResponse = (patchCollectionsMatchesRecordsIdResponseSuccess)

export const getPatchCollectionsMatchesRecordsIdUrl = (id: string,) => {




  return `/collections/matches/records/${id}`
}

/**
 * @summary Update Matches Collection Record
 */
export const patchCollectionsMatchesRecordsId = async (id: string,
    matchesRecord?: MatchesRecord, options?: RequestInit): Promise<patchCollectionsMatchesRecordsIdResponse> => {

  return customInstance<patchCollectionsMatchesRecordsIdResponse>(getPatchCollectionsMatchesRecordsIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(matchesRecord)
  }
);}





export const getPatchCollectionsMatchesRecordsIdQueryKey = (id: string,
    matchesRecord?: BodyType<MatchesRecord>,) => {
    return [
    'PATCH', `/collections/matches/records/${id}`, matchesRecord
    ] as const;
    }


export const getPatchCollectionsMatchesRecordsIdQueryOptions = <TData = Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>, TError = ErrorType<unknown>>(id: string,
    matchesRecord?: BodyType<MatchesRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPatchCollectionsMatchesRecordsIdQueryKey(id,matchesRecord);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>> = ({ signal }) => patchCollectionsMatchesRecordsId(id,matchesRecord, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PatchCollectionsMatchesRecordsIdQueryResult = NonNullable<Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>>
export type PatchCollectionsMatchesRecordsIdQueryError = ErrorType<unknown>


export function usePatchCollectionsMatchesRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    matchesRecord: undefined |  BodyType<MatchesRecord>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>,
          TError,
          Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatchCollectionsMatchesRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    matchesRecord?: BodyType<MatchesRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>,
          TError,
          Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatchCollectionsMatchesRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    matchesRecord?: BodyType<MatchesRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update Matches Collection Record
 */

export function usePatchCollectionsMatchesRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    matchesRecord?: BodyType<MatchesRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsMatchesRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPatchCollectionsMatchesRecordsIdQueryOptions(id,matchesRecord,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteCollectionsMatchesRecordsIdResponse204 = {
  data: void
  status: 204
}

export type deleteCollectionsMatchesRecordsIdResponseSuccess = (deleteCollectionsMatchesRecordsIdResponse204) & {
  headers: Headers;
};
;

export type deleteCollectionsMatchesRecordsIdResponse = (deleteCollectionsMatchesRecordsIdResponseSuccess)

export const getDeleteCollectionsMatchesRecordsIdUrl = (id: string,) => {




  return `/collections/matches/records/${id}`
}

/**
 * @summary Delete Matches Collection Record
 */
export const deleteCollectionsMatchesRecordsId = async (id: string, options?: RequestInit): Promise<deleteCollectionsMatchesRecordsIdResponse> => {

  return customInstance<deleteCollectionsMatchesRecordsIdResponse>(getDeleteCollectionsMatchesRecordsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteCollectionsMatchesRecordsIdQueryKey = (id: string,) => {
    return [
    'DELETE', `/collections/matches/records/${id}`
    ] as const;
    }


export const getDeleteCollectionsMatchesRecordsIdQueryOptions = <TData = Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteCollectionsMatchesRecordsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>> = ({ signal }) => deleteCollectionsMatchesRecordsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteCollectionsMatchesRecordsIdQueryResult = NonNullable<Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>>
export type DeleteCollectionsMatchesRecordsIdQueryError = ErrorType<unknown>


export function useDeleteCollectionsMatchesRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>,
          TError,
          Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteCollectionsMatchesRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>,
          TError,
          Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteCollectionsMatchesRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete Matches Collection Record
 */

export function useDeleteCollectionsMatchesRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsMatchesRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteCollectionsMatchesRecordsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






