/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Retrieves a paginated list of Participants Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Participants Collection
 */
export const getCollectionsParticipantsRecordsQueryPageDefault = 1;

export const getCollectionsParticipantsRecordsQueryPerPageDefault = 30;
export const getCollectionsParticipantsRecordsQueryPerPageMax = 500;

export const getCollectionsParticipantsRecordsQuerySkipTotalDefault = false;

export const GetCollectionsParticipantsRecordsQueryParams = zod.object({
  "filter": zod.string().optional().describe('Filtering expression (e.g., \'created > \"2022-01-01\"\')'),
  "sort": zod.string().optional().describe('Comma-separated list of fields to sort by. Prefix with \'-\' for descending order.'),
  "page": zod.number().min(1).default(getCollectionsParticipantsRecordsQueryPageDefault).describe('Page number (starting from 1)'),
  "perPage": zod.number().min(1).max(getCollectionsParticipantsRecordsQueryPerPageMax).default(getCollectionsParticipantsRecordsQueryPerPageDefault).describe('Number of records per page (max 500)'),
  "skipTotal": zod.boolean().default(getCollectionsParticipantsRecordsQuerySkipTotalDefault).describe('Set to true to skip the total count (improves performance for large collections)'),
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const getCollectionsParticipantsRecordsResponseItemsItemPreferredRolesMax = 5;



export const GetCollectionsParticipantsRecordsResponse = zod.object({
  "page": zod.number().optional(),
  "perPage": zod.number().optional(),
  "totalItems": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "items": zod.array(zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "name": zod.string(),
  "email": zod.email(),
  "ign": zod.string(),
  "birthdate": zod.iso.datetime({"offset":true}),
  "contact_number": zod.string().optional(),
  "user_id": zod.string(),
  "server_id": zod.string(),
  "address_phase": zod.enum(['4', '9', '10']),
  "address_package": zod.string(),
  "address_block": zod.string(),
  "address_lot": zod.string(),
  "preferred_lane": zod.enum(['mid', 'gold', 'exp', 'support', 'jungle']),
  "preferred_roles": zod.array(zod.enum(['mid', 'gold', 'exp', 'support', 'jungle'])).max(getCollectionsParticipantsRecordsResponseItemsItemPreferredRolesMax).optional(),
  "role_rankings": zod.record(zod.string(), zod.unknown()).optional(),
  "performance_basis": zod.record(zod.string(), zod.unknown()).optional(),
  "team_intent": zod.enum(['open_matching', 'join_team', 'create_team']).optional(),
  "preferred_team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "preferred_team_name": zod.string().optional(),
  "registration_status": zod.enum(['pending', 'approved', 'rejected']),
  "registration_reject_reason": zod.string().optional(),
  "registration_status_code": zod.string().optional(),
  "consent_version": zod.string().optional(),
  "school_id_front": zod.string().optional(),
  "school_id_back": zod.string().optional(),
  "purok_endorsement": zod.string().optional(),
  "status": zod.enum(['unassigned', 'suggested', 'assigned', 'inactive']),
  "team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "consent_accepted_at": zod.iso.datetime({"offset":true}).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})).optional()
})

/**
 * @summary Create Participants Collection Record
 */
export const postCollectionsParticipantsRecordsBodyPreferredRolesMax = 5;



export const PostCollectionsParticipantsRecordsBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "name": zod.string(),
  "email": zod.email(),
  "ign": zod.string(),
  "birthdate": zod.iso.datetime({"offset":true}),
  "contact_number": zod.string().optional(),
  "user_id": zod.string(),
  "server_id": zod.string(),
  "address_phase": zod.enum(['4', '9', '10']),
  "address_package": zod.string(),
  "address_block": zod.string(),
  "address_lot": zod.string(),
  "preferred_lane": zod.enum(['mid', 'gold', 'exp', 'support', 'jungle']),
  "preferred_roles": zod.array(zod.enum(['mid', 'gold', 'exp', 'support', 'jungle'])).max(postCollectionsParticipantsRecordsBodyPreferredRolesMax).optional(),
  "role_rankings": zod.record(zod.string(), zod.unknown()).optional(),
  "performance_basis": zod.record(zod.string(), zod.unknown()).optional(),
  "team_intent": zod.enum(['open_matching', 'join_team', 'create_team']).optional(),
  "preferred_team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "preferred_team_name": zod.string().optional(),
  "registration_status": zod.enum(['pending', 'approved', 'rejected']),
  "registration_reject_reason": zod.string().optional(),
  "registration_status_code": zod.string().optional(),
  "consent_version": zod.string().optional(),
  "school_id_front": zod.string().optional(),
  "school_id_back": zod.string().optional(),
  "purok_endorsement": zod.string().optional(),
  "status": zod.enum(['unassigned', 'suggested', 'assigned', 'inactive']),
  "team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "consent_accepted_at": zod.iso.datetime({"offset":true}).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const postCollectionsParticipantsRecordsResponsePreferredRolesMax = 5;



export const PostCollectionsParticipantsRecordsResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "name": zod.string(),
  "email": zod.email(),
  "ign": zod.string(),
  "birthdate": zod.iso.datetime({"offset":true}),
  "contact_number": zod.string().optional(),
  "user_id": zod.string(),
  "server_id": zod.string(),
  "address_phase": zod.enum(['4', '9', '10']),
  "address_package": zod.string(),
  "address_block": zod.string(),
  "address_lot": zod.string(),
  "preferred_lane": zod.enum(['mid', 'gold', 'exp', 'support', 'jungle']),
  "preferred_roles": zod.array(zod.enum(['mid', 'gold', 'exp', 'support', 'jungle'])).max(postCollectionsParticipantsRecordsResponsePreferredRolesMax).optional(),
  "role_rankings": zod.record(zod.string(), zod.unknown()).optional(),
  "performance_basis": zod.record(zod.string(), zod.unknown()).optional(),
  "team_intent": zod.enum(['open_matching', 'join_team', 'create_team']).optional(),
  "preferred_team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "preferred_team_name": zod.string().optional(),
  "registration_status": zod.enum(['pending', 'approved', 'rejected']),
  "registration_reject_reason": zod.string().optional(),
  "registration_status_code": zod.string().optional(),
  "consent_version": zod.string().optional(),
  "school_id_front": zod.string().optional(),
  "school_id_back": zod.string().optional(),
  "purok_endorsement": zod.string().optional(),
  "status": zod.enum(['unassigned', 'suggested', 'assigned', 'inactive']),
  "team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "consent_accepted_at": zod.iso.datetime({"offset":true}).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Get Participants Collection by ID
 */
export const GetCollectionsParticipantsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const GetCollectionsParticipantsRecordsIdQueryParams = zod.object({
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const getCollectionsParticipantsRecordsIdResponsePreferredRolesMax = 5;



export const GetCollectionsParticipantsRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "name": zod.string(),
  "email": zod.email(),
  "ign": zod.string(),
  "birthdate": zod.iso.datetime({"offset":true}),
  "contact_number": zod.string().optional(),
  "user_id": zod.string(),
  "server_id": zod.string(),
  "address_phase": zod.enum(['4', '9', '10']),
  "address_package": zod.string(),
  "address_block": zod.string(),
  "address_lot": zod.string(),
  "preferred_lane": zod.enum(['mid', 'gold', 'exp', 'support', 'jungle']),
  "preferred_roles": zod.array(zod.enum(['mid', 'gold', 'exp', 'support', 'jungle'])).max(getCollectionsParticipantsRecordsIdResponsePreferredRolesMax).optional(),
  "role_rankings": zod.record(zod.string(), zod.unknown()).optional(),
  "performance_basis": zod.record(zod.string(), zod.unknown()).optional(),
  "team_intent": zod.enum(['open_matching', 'join_team', 'create_team']).optional(),
  "preferred_team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "preferred_team_name": zod.string().optional(),
  "registration_status": zod.enum(['pending', 'approved', 'rejected']),
  "registration_reject_reason": zod.string().optional(),
  "registration_status_code": zod.string().optional(),
  "consent_version": zod.string().optional(),
  "school_id_front": zod.string().optional(),
  "school_id_back": zod.string().optional(),
  "purok_endorsement": zod.string().optional(),
  "status": zod.enum(['unassigned', 'suggested', 'assigned', 'inactive']),
  "team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "consent_accepted_at": zod.iso.datetime({"offset":true}).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Update Participants Collection Record
 */
export const PatchCollectionsParticipantsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const patchCollectionsParticipantsRecordsIdBodyPreferredRolesMax = 5;



export const PatchCollectionsParticipantsRecordsIdBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "name": zod.string(),
  "email": zod.email(),
  "ign": zod.string(),
  "birthdate": zod.iso.datetime({"offset":true}),
  "contact_number": zod.string().optional(),
  "user_id": zod.string(),
  "server_id": zod.string(),
  "address_phase": zod.enum(['4', '9', '10']),
  "address_package": zod.string(),
  "address_block": zod.string(),
  "address_lot": zod.string(),
  "preferred_lane": zod.enum(['mid', 'gold', 'exp', 'support', 'jungle']),
  "preferred_roles": zod.array(zod.enum(['mid', 'gold', 'exp', 'support', 'jungle'])).max(patchCollectionsParticipantsRecordsIdBodyPreferredRolesMax).optional(),
  "role_rankings": zod.record(zod.string(), zod.unknown()).optional(),
  "performance_basis": zod.record(zod.string(), zod.unknown()).optional(),
  "team_intent": zod.enum(['open_matching', 'join_team', 'create_team']).optional(),
  "preferred_team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "preferred_team_name": zod.string().optional(),
  "registration_status": zod.enum(['pending', 'approved', 'rejected']),
  "registration_reject_reason": zod.string().optional(),
  "registration_status_code": zod.string().optional(),
  "consent_version": zod.string().optional(),
  "school_id_front": zod.string().optional(),
  "school_id_back": zod.string().optional(),
  "purok_endorsement": zod.string().optional(),
  "status": zod.enum(['unassigned', 'suggested', 'assigned', 'inactive']),
  "team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "consent_accepted_at": zod.iso.datetime({"offset":true}).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const patchCollectionsParticipantsRecordsIdResponsePreferredRolesMax = 5;



export const PatchCollectionsParticipantsRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "name": zod.string(),
  "email": zod.email(),
  "ign": zod.string(),
  "birthdate": zod.iso.datetime({"offset":true}),
  "contact_number": zod.string().optional(),
  "user_id": zod.string(),
  "server_id": zod.string(),
  "address_phase": zod.enum(['4', '9', '10']),
  "address_package": zod.string(),
  "address_block": zod.string(),
  "address_lot": zod.string(),
  "preferred_lane": zod.enum(['mid', 'gold', 'exp', 'support', 'jungle']),
  "preferred_roles": zod.array(zod.enum(['mid', 'gold', 'exp', 'support', 'jungle'])).max(patchCollectionsParticipantsRecordsIdResponsePreferredRolesMax).optional(),
  "role_rankings": zod.record(zod.string(), zod.unknown()).optional(),
  "performance_basis": zod.record(zod.string(), zod.unknown()).optional(),
  "team_intent": zod.enum(['open_matching', 'join_team', 'create_team']).optional(),
  "preferred_team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "preferred_team_name": zod.string().optional(),
  "registration_status": zod.enum(['pending', 'approved', 'rejected']),
  "registration_reject_reason": zod.string().optional(),
  "registration_status_code": zod.string().optional(),
  "consent_version": zod.string().optional(),
  "school_id_front": zod.string().optional(),
  "school_id_back": zod.string().optional(),
  "purok_endorsement": zod.string().optional(),
  "status": zod.enum(['unassigned', 'suggested', 'assigned', 'inactive']),
  "team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "consent_accepted_at": zod.iso.datetime({"offset":true}).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Delete Participants Collection Record
 */
export const DeleteCollectionsParticipantsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const DeleteCollectionsParticipantsRecordsIdResponse = zod.void()

