/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCollectionsTeamsRecords200,
  GetCollectionsTeamsRecordsIdParams,
  GetCollectionsTeamsRecordsParams,
  TeamsRecord
} from '../model';

import { customInstance } from '../../../lib/api/mutator/custom-instance.ts';
import type { ErrorType , BodyType } from '../../../lib/api/mutator/custom-instance.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getCollectionsTeamsRecordsResponse200 = {
  data: GetCollectionsTeamsRecords200
  status: 200
}

export type getCollectionsTeamsRecordsResponseSuccess = (getCollectionsTeamsRecordsResponse200) & {
  headers: Headers;
};
;

export type getCollectionsTeamsRecordsResponse = (getCollectionsTeamsRecordsResponseSuccess)

export const getGetCollectionsTeamsRecordsUrl = (params?: GetCollectionsTeamsRecordsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collections/teams/records?${stringifiedParams}` : `/collections/teams/records`
}

/**
 * Retrieves a paginated list of Teams Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Teams Collection
 */
export const getCollectionsTeamsRecords = async (params?: GetCollectionsTeamsRecordsParams, options?: RequestInit): Promise<getCollectionsTeamsRecordsResponse> => {

  return customInstance<getCollectionsTeamsRecordsResponse>(getGetCollectionsTeamsRecordsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsTeamsRecordsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTeamsRecords>>, TError,{params?: GetCollectionsTeamsRecordsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTeamsRecords>>, TError,{params?: GetCollectionsTeamsRecordsParams}, TContext> => {

const mutationKey = ['getCollectionsTeamsRecords'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsTeamsRecords>>, {params?: GetCollectionsTeamsRecordsParams}> = (props) => {
          const {params} = props ?? {};

          return  getCollectionsTeamsRecords(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsTeamsRecordsMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsTeamsRecords>>>

    export type GetCollectionsTeamsRecordsMutationError = ErrorType<unknown>

    /**
 * @summary List Teams Collection
 */
export const useGetCollectionsTeamsRecords = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTeamsRecords>>, TError,{params?: GetCollectionsTeamsRecordsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsTeamsRecords>>,
        TError,
        {params?: GetCollectionsTeamsRecordsParams},
        TContext
      > => {
      return useMutation(getGetCollectionsTeamsRecordsMutationOptions(options), queryClient);
    }
    export type postCollectionsTeamsRecordsResponse200 = {
  data: TeamsRecord
  status: 200
}

export type postCollectionsTeamsRecordsResponseSuccess = (postCollectionsTeamsRecordsResponse200) & {
  headers: Headers;
};
;

export type postCollectionsTeamsRecordsResponse = (postCollectionsTeamsRecordsResponseSuccess)

export const getPostCollectionsTeamsRecordsUrl = () => {




  return `/collections/teams/records`
}

/**
 * @summary Create Teams Collection Record
 */
export const postCollectionsTeamsRecords = async (teamsRecord?: TeamsRecord, options?: RequestInit): Promise<postCollectionsTeamsRecordsResponse> => {

  return customInstance<postCollectionsTeamsRecordsResponse>(getPostCollectionsTeamsRecordsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(teamsRecord)
  }
);}





export const getPostCollectionsTeamsRecordsQueryKey = (teamsRecord?: BodyType<TeamsRecord>,) => {
    return [
    'POST', `/collections/teams/records`, teamsRecord
    ] as const;
    }


export const getPostCollectionsTeamsRecordsQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsTeamsRecords>>, TError = ErrorType<unknown>>(teamsRecord?: BodyType<TeamsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTeamsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsTeamsRecordsQueryKey(teamsRecord);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsTeamsRecords>>> = ({ signal }) => postCollectionsTeamsRecords(teamsRecord, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTeamsRecords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsTeamsRecordsQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsTeamsRecords>>>
export type PostCollectionsTeamsRecordsQueryError = ErrorType<unknown>


export function usePostCollectionsTeamsRecords<TData = Awaited<ReturnType<typeof postCollectionsTeamsRecords>>, TError = ErrorType<unknown>>(
 teamsRecord: undefined |  BodyType<TeamsRecord>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTeamsRecords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsTeamsRecords>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsTeamsRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsTeamsRecords<TData = Awaited<ReturnType<typeof postCollectionsTeamsRecords>>, TError = ErrorType<unknown>>(
 teamsRecord?: BodyType<TeamsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTeamsRecords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsTeamsRecords>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsTeamsRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsTeamsRecords<TData = Awaited<ReturnType<typeof postCollectionsTeamsRecords>>, TError = ErrorType<unknown>>(
 teamsRecord?: BodyType<TeamsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTeamsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create Teams Collection Record
 */

export function usePostCollectionsTeamsRecords<TData = Awaited<ReturnType<typeof postCollectionsTeamsRecords>>, TError = ErrorType<unknown>>(
 teamsRecord?: BodyType<TeamsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTeamsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsTeamsRecordsQueryOptions(teamsRecord,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getCollectionsTeamsRecordsIdResponse200 = {
  data: TeamsRecord
  status: 200
}

export type getCollectionsTeamsRecordsIdResponseSuccess = (getCollectionsTeamsRecordsIdResponse200) & {
  headers: Headers;
};
;

export type getCollectionsTeamsRecordsIdResponse = (getCollectionsTeamsRecordsIdResponseSuccess)

export const getGetCollectionsTeamsRecordsIdUrl = (id: string,
    params?: GetCollectionsTeamsRecordsIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collections/teams/records/${id}?${stringifiedParams}` : `/collections/teams/records/${id}`
}

/**
 * @summary Get Teams Collection by ID
 */
export const getCollectionsTeamsRecordsId = async (id: string,
    params?: GetCollectionsTeamsRecordsIdParams, options?: RequestInit): Promise<getCollectionsTeamsRecordsIdResponse> => {

  return customInstance<getCollectionsTeamsRecordsIdResponse>(getGetCollectionsTeamsRecordsIdUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsTeamsRecordsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTeamsRecordsId>>, TError,{id: string;params?: GetCollectionsTeamsRecordsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTeamsRecordsId>>, TError,{id: string;params?: GetCollectionsTeamsRecordsIdParams}, TContext> => {

const mutationKey = ['getCollectionsTeamsRecordsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsTeamsRecordsId>>, {id: string;params?: GetCollectionsTeamsRecordsIdParams}> = (props) => {
          const {id,params} = props ?? {};

          return  getCollectionsTeamsRecordsId(id,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsTeamsRecordsIdMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsTeamsRecordsId>>>

    export type GetCollectionsTeamsRecordsIdMutationError = ErrorType<unknown>

    /**
 * @summary Get Teams Collection by ID
 */
export const useGetCollectionsTeamsRecordsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTeamsRecordsId>>, TError,{id: string;params?: GetCollectionsTeamsRecordsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsTeamsRecordsId>>,
        TError,
        {id: string;params?: GetCollectionsTeamsRecordsIdParams},
        TContext
      > => {
      return useMutation(getGetCollectionsTeamsRecordsIdMutationOptions(options), queryClient);
    }
    export type patchCollectionsTeamsRecordsIdResponse200 = {
  data: TeamsRecord
  status: 200
}

export type patchCollectionsTeamsRecordsIdResponseSuccess = (patchCollectionsTeamsRecordsIdResponse200) & {
  headers: Headers;
};
;

export type patchCollectionsTeamsRecordsIdResponse = (patchCollectionsTeamsRecordsIdResponseSuccess)

export const getPatchCollectionsTeamsRecordsIdUrl = (id: string,) => {




  return `/collections/teams/records/${id}`
}

/**
 * @summary Update Teams Collection Record
 */
export const patchCollectionsTeamsRecordsId = async (id: string,
    teamsRecord?: TeamsRecord, options?: RequestInit): Promise<patchCollectionsTeamsRecordsIdResponse> => {

  return customInstance<patchCollectionsTeamsRecordsIdResponse>(getPatchCollectionsTeamsRecordsIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(teamsRecord)
  }
);}





export const getPatchCollectionsTeamsRecordsIdQueryKey = (id: string,
    teamsRecord?: BodyType<TeamsRecord>,) => {
    return [
    'PATCH', `/collections/teams/records/${id}`, teamsRecord
    ] as const;
    }


export const getPatchCollectionsTeamsRecordsIdQueryOptions = <TData = Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>, TError = ErrorType<unknown>>(id: string,
    teamsRecord?: BodyType<TeamsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPatchCollectionsTeamsRecordsIdQueryKey(id,teamsRecord);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>> = ({ signal }) => patchCollectionsTeamsRecordsId(id,teamsRecord, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PatchCollectionsTeamsRecordsIdQueryResult = NonNullable<Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>>
export type PatchCollectionsTeamsRecordsIdQueryError = ErrorType<unknown>


export function usePatchCollectionsTeamsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    teamsRecord: undefined |  BodyType<TeamsRecord>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatchCollectionsTeamsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    teamsRecord?: BodyType<TeamsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatchCollectionsTeamsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    teamsRecord?: BodyType<TeamsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update Teams Collection Record
 */

export function usePatchCollectionsTeamsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    teamsRecord?: BodyType<TeamsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTeamsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPatchCollectionsTeamsRecordsIdQueryOptions(id,teamsRecord,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteCollectionsTeamsRecordsIdResponse204 = {
  data: void
  status: 204
}

export type deleteCollectionsTeamsRecordsIdResponseSuccess = (deleteCollectionsTeamsRecordsIdResponse204) & {
  headers: Headers;
};
;

export type deleteCollectionsTeamsRecordsIdResponse = (deleteCollectionsTeamsRecordsIdResponseSuccess)

export const getDeleteCollectionsTeamsRecordsIdUrl = (id: string,) => {




  return `/collections/teams/records/${id}`
}

/**
 * @summary Delete Teams Collection Record
 */
export const deleteCollectionsTeamsRecordsId = async (id: string, options?: RequestInit): Promise<deleteCollectionsTeamsRecordsIdResponse> => {

  return customInstance<deleteCollectionsTeamsRecordsIdResponse>(getDeleteCollectionsTeamsRecordsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteCollectionsTeamsRecordsIdQueryKey = (id: string,) => {
    return [
    'DELETE', `/collections/teams/records/${id}`
    ] as const;
    }


export const getDeleteCollectionsTeamsRecordsIdQueryOptions = <TData = Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteCollectionsTeamsRecordsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>> = ({ signal }) => deleteCollectionsTeamsRecordsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteCollectionsTeamsRecordsIdQueryResult = NonNullable<Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>>
export type DeleteCollectionsTeamsRecordsIdQueryError = ErrorType<unknown>


export function useDeleteCollectionsTeamsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteCollectionsTeamsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteCollectionsTeamsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete Teams Collection Record
 */

export function useDeleteCollectionsTeamsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTeamsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteCollectionsTeamsRecordsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






