/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DraftSuggestionsRecord,
  GetCollectionsDraftSuggestionsRecords200,
  GetCollectionsDraftSuggestionsRecordsIdParams,
  GetCollectionsDraftSuggestionsRecordsParams
} from '../model';

import { customInstance } from '../../../lib/api/mutator/custom-instance.ts';
import type { ErrorType } from '../../../lib/api/mutator/custom-instance.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getCollectionsDraftSuggestionsRecordsResponse200 = {
  data: GetCollectionsDraftSuggestionsRecords200
  status: 200
}

export type getCollectionsDraftSuggestionsRecordsResponseSuccess = (getCollectionsDraftSuggestionsRecordsResponse200) & {
  headers: Headers;
};
;

export type getCollectionsDraftSuggestionsRecordsResponse = (getCollectionsDraftSuggestionsRecordsResponseSuccess)

export const getGetCollectionsDraftSuggestionsRecordsUrl = (params?: GetCollectionsDraftSuggestionsRecordsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collections/draft_suggestions/records?${stringifiedParams}` : `/collections/draft_suggestions/records`
}

/**
 * Retrieves a paginated list of Draft_suggestions Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Draft_suggestions Collection
 */
export const getCollectionsDraftSuggestionsRecords = async (params?: GetCollectionsDraftSuggestionsRecordsParams, options?: RequestInit): Promise<getCollectionsDraftSuggestionsRecordsResponse> => {

  return customInstance<getCollectionsDraftSuggestionsRecordsResponse>(getGetCollectionsDraftSuggestionsRecordsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsDraftSuggestionsRecordsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsDraftSuggestionsRecords>>, TError,{params?: GetCollectionsDraftSuggestionsRecordsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsDraftSuggestionsRecords>>, TError,{params?: GetCollectionsDraftSuggestionsRecordsParams}, TContext> => {

const mutationKey = ['getCollectionsDraftSuggestionsRecords'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsDraftSuggestionsRecords>>, {params?: GetCollectionsDraftSuggestionsRecordsParams}> = (props) => {
          const {params} = props ?? {};

          return  getCollectionsDraftSuggestionsRecords(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsDraftSuggestionsRecordsMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsDraftSuggestionsRecords>>>

    export type GetCollectionsDraftSuggestionsRecordsMutationError = ErrorType<unknown>

    /**
 * @summary List Draft_suggestions Collection
 */
export const useGetCollectionsDraftSuggestionsRecords = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsDraftSuggestionsRecords>>, TError,{params?: GetCollectionsDraftSuggestionsRecordsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsDraftSuggestionsRecords>>,
        TError,
        {params?: GetCollectionsDraftSuggestionsRecordsParams},
        TContext
      > => {
      return useMutation(getGetCollectionsDraftSuggestionsRecordsMutationOptions(options), queryClient);
    }
    export type getCollectionsDraftSuggestionsRecordsIdResponse200 = {
  data: DraftSuggestionsRecord
  status: 200
}

export type getCollectionsDraftSuggestionsRecordsIdResponseSuccess = (getCollectionsDraftSuggestionsRecordsIdResponse200) & {
  headers: Headers;
};
;

export type getCollectionsDraftSuggestionsRecordsIdResponse = (getCollectionsDraftSuggestionsRecordsIdResponseSuccess)

export const getGetCollectionsDraftSuggestionsRecordsIdUrl = (id: string,
    params?: GetCollectionsDraftSuggestionsRecordsIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collections/draft_suggestions/records/${id}?${stringifiedParams}` : `/collections/draft_suggestions/records/${id}`
}

/**
 * @summary Get Draft_suggestions Collection by ID
 */
export const getCollectionsDraftSuggestionsRecordsId = async (id: string,
    params?: GetCollectionsDraftSuggestionsRecordsIdParams, options?: RequestInit): Promise<getCollectionsDraftSuggestionsRecordsIdResponse> => {

  return customInstance<getCollectionsDraftSuggestionsRecordsIdResponse>(getGetCollectionsDraftSuggestionsRecordsIdUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsDraftSuggestionsRecordsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsDraftSuggestionsRecordsId>>, TError,{id: string;params?: GetCollectionsDraftSuggestionsRecordsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsDraftSuggestionsRecordsId>>, TError,{id: string;params?: GetCollectionsDraftSuggestionsRecordsIdParams}, TContext> => {

const mutationKey = ['getCollectionsDraftSuggestionsRecordsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsDraftSuggestionsRecordsId>>, {id: string;params?: GetCollectionsDraftSuggestionsRecordsIdParams}> = (props) => {
          const {id,params} = props ?? {};

          return  getCollectionsDraftSuggestionsRecordsId(id,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsDraftSuggestionsRecordsIdMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsDraftSuggestionsRecordsId>>>

    export type GetCollectionsDraftSuggestionsRecordsIdMutationError = ErrorType<unknown>

    /**
 * @summary Get Draft_suggestions Collection by ID
 */
export const useGetCollectionsDraftSuggestionsRecordsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsDraftSuggestionsRecordsId>>, TError,{id: string;params?: GetCollectionsDraftSuggestionsRecordsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsDraftSuggestionsRecordsId>>,
        TError,
        {id: string;params?: GetCollectionsDraftSuggestionsRecordsIdParams},
        TContext
      > => {
      return useMutation(getGetCollectionsDraftSuggestionsRecordsIdMutationOptions(options), queryClient);
    }
