/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Retrieves a paginated list of Teams Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Teams Collection
 */
export const getCollectionsTeamsRecordsQueryPageDefault = 1;

export const getCollectionsTeamsRecordsQueryPerPageDefault = 30;
export const getCollectionsTeamsRecordsQueryPerPageMax = 500;

export const getCollectionsTeamsRecordsQuerySkipTotalDefault = false;

export const GetCollectionsTeamsRecordsQueryParams = zod.object({
  "filter": zod.string().optional().describe('Filtering expression (e.g., \'created > \"2022-01-01\"\')'),
  "sort": zod.string().optional().describe('Comma-separated list of fields to sort by. Prefix with \'-\' for descending order.'),
  "page": zod.number().min(1).default(getCollectionsTeamsRecordsQueryPageDefault).describe('Page number (starting from 1)'),
  "perPage": zod.number().min(1).max(getCollectionsTeamsRecordsQueryPerPageMax).default(getCollectionsTeamsRecordsQueryPerPageDefault).describe('Number of records per page (max 500)'),
  "skipTotal": zod.boolean().default(getCollectionsTeamsRecordsQuerySkipTotalDefault).describe('Set to true to skip the total count (improves performance for large collections)'),
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsTeamsRecordsResponse = zod.object({
  "page": zod.number().optional(),
  "perPage": zod.number().optional(),
  "totalItems": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "items": zod.array(zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "name": zod.string(),
  "captain": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "status": zod.enum(['forming', 'ready', 'incomplete', 'inactive']),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})).optional()
})

/**
 * @summary Create Teams Collection Record
 */
export const PostCollectionsTeamsRecordsBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "name": zod.string(),
  "captain": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "status": zod.enum(['forming', 'ready', 'incomplete', 'inactive']),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const PostCollectionsTeamsRecordsResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "name": zod.string(),
  "captain": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "status": zod.enum(['forming', 'ready', 'incomplete', 'inactive']),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Get Teams Collection by ID
 */
export const GetCollectionsTeamsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const GetCollectionsTeamsRecordsIdQueryParams = zod.object({
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsTeamsRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "name": zod.string(),
  "captain": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "status": zod.enum(['forming', 'ready', 'incomplete', 'inactive']),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Update Teams Collection Record
 */
export const PatchCollectionsTeamsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const PatchCollectionsTeamsRecordsIdBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "name": zod.string(),
  "captain": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "status": zod.enum(['forming', 'ready', 'incomplete', 'inactive']),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const PatchCollectionsTeamsRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "name": zod.string(),
  "captain": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "status": zod.enum(['forming', 'ready', 'incomplete', 'inactive']),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Delete Teams Collection Record
 */
export const DeleteCollectionsTeamsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const DeleteCollectionsTeamsRecordsIdResponse = zod.void()

