/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCollectionsParticipantsRecords200,
  GetCollectionsParticipantsRecordsIdParams,
  GetCollectionsParticipantsRecordsParams,
  ParticipantsRecord
} from '../model';

import { customInstance } from '../../../lib/api/mutator/custom-instance.ts';
import type { ErrorType , BodyType } from '../../../lib/api/mutator/custom-instance.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getCollectionsParticipantsRecordsResponse200 = {
  data: GetCollectionsParticipantsRecords200
  status: 200
}

export type getCollectionsParticipantsRecordsResponseSuccess = (getCollectionsParticipantsRecordsResponse200) & {
  headers: Headers;
};
;

export type getCollectionsParticipantsRecordsResponse = (getCollectionsParticipantsRecordsResponseSuccess)

export const getGetCollectionsParticipantsRecordsUrl = (params?: GetCollectionsParticipantsRecordsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collections/participants/records?${stringifiedParams}` : `/collections/participants/records`
}

/**
 * Retrieves a paginated list of Participants Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Participants Collection
 */
export const getCollectionsParticipantsRecords = async (params?: GetCollectionsParticipantsRecordsParams, options?: RequestInit): Promise<getCollectionsParticipantsRecordsResponse> => {

  return customInstance<getCollectionsParticipantsRecordsResponse>(getGetCollectionsParticipantsRecordsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsParticipantsRecordsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsParticipantsRecords>>, TError,{params?: GetCollectionsParticipantsRecordsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsParticipantsRecords>>, TError,{params?: GetCollectionsParticipantsRecordsParams}, TContext> => {

const mutationKey = ['getCollectionsParticipantsRecords'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsParticipantsRecords>>, {params?: GetCollectionsParticipantsRecordsParams}> = (props) => {
          const {params} = props ?? {};

          return  getCollectionsParticipantsRecords(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsParticipantsRecordsMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsParticipantsRecords>>>

    export type GetCollectionsParticipantsRecordsMutationError = ErrorType<unknown>

    /**
 * @summary List Participants Collection
 */
export const useGetCollectionsParticipantsRecords = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsParticipantsRecords>>, TError,{params?: GetCollectionsParticipantsRecordsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsParticipantsRecords>>,
        TError,
        {params?: GetCollectionsParticipantsRecordsParams},
        TContext
      > => {
      return useMutation(getGetCollectionsParticipantsRecordsMutationOptions(options), queryClient);
    }
    export type postCollectionsParticipantsRecordsResponse200 = {
  data: ParticipantsRecord
  status: 200
}

export type postCollectionsParticipantsRecordsResponseSuccess = (postCollectionsParticipantsRecordsResponse200) & {
  headers: Headers;
};
;

export type postCollectionsParticipantsRecordsResponse = (postCollectionsParticipantsRecordsResponseSuccess)

export const getPostCollectionsParticipantsRecordsUrl = () => {




  return `/collections/participants/records`
}

/**
 * @summary Create Participants Collection Record
 */
export const postCollectionsParticipantsRecords = async (participantsRecord?: ParticipantsRecord, options?: RequestInit): Promise<postCollectionsParticipantsRecordsResponse> => {

  return customInstance<postCollectionsParticipantsRecordsResponse>(getPostCollectionsParticipantsRecordsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(participantsRecord)
  }
);}





export const getPostCollectionsParticipantsRecordsQueryKey = (participantsRecord?: BodyType<ParticipantsRecord>,) => {
    return [
    'POST', `/collections/participants/records`, participantsRecord
    ] as const;
    }


export const getPostCollectionsParticipantsRecordsQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>, TError = ErrorType<unknown>>(participantsRecord?: BodyType<ParticipantsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsParticipantsRecordsQueryKey(participantsRecord);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>> = ({ signal }) => postCollectionsParticipantsRecords(participantsRecord, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsParticipantsRecordsQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>>
export type PostCollectionsParticipantsRecordsQueryError = ErrorType<unknown>


export function usePostCollectionsParticipantsRecords<TData = Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>, TError = ErrorType<unknown>>(
 participantsRecord: undefined |  BodyType<ParticipantsRecord>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsParticipantsRecords<TData = Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>, TError = ErrorType<unknown>>(
 participantsRecord?: BodyType<ParticipantsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsParticipantsRecords<TData = Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>, TError = ErrorType<unknown>>(
 participantsRecord?: BodyType<ParticipantsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create Participants Collection Record
 */

export function usePostCollectionsParticipantsRecords<TData = Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>, TError = ErrorType<unknown>>(
 participantsRecord?: BodyType<ParticipantsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsParticipantsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsParticipantsRecordsQueryOptions(participantsRecord,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getCollectionsParticipantsRecordsIdResponse200 = {
  data: ParticipantsRecord
  status: 200
}

export type getCollectionsParticipantsRecordsIdResponseSuccess = (getCollectionsParticipantsRecordsIdResponse200) & {
  headers: Headers;
};
;

export type getCollectionsParticipantsRecordsIdResponse = (getCollectionsParticipantsRecordsIdResponseSuccess)

export const getGetCollectionsParticipantsRecordsIdUrl = (id: string,
    params?: GetCollectionsParticipantsRecordsIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collections/participants/records/${id}?${stringifiedParams}` : `/collections/participants/records/${id}`
}

/**
 * @summary Get Participants Collection by ID
 */
export const getCollectionsParticipantsRecordsId = async (id: string,
    params?: GetCollectionsParticipantsRecordsIdParams, options?: RequestInit): Promise<getCollectionsParticipantsRecordsIdResponse> => {

  return customInstance<getCollectionsParticipantsRecordsIdResponse>(getGetCollectionsParticipantsRecordsIdUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsParticipantsRecordsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsParticipantsRecordsId>>, TError,{id: string;params?: GetCollectionsParticipantsRecordsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsParticipantsRecordsId>>, TError,{id: string;params?: GetCollectionsParticipantsRecordsIdParams}, TContext> => {

const mutationKey = ['getCollectionsParticipantsRecordsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsParticipantsRecordsId>>, {id: string;params?: GetCollectionsParticipantsRecordsIdParams}> = (props) => {
          const {id,params} = props ?? {};

          return  getCollectionsParticipantsRecordsId(id,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsParticipantsRecordsIdMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsParticipantsRecordsId>>>

    export type GetCollectionsParticipantsRecordsIdMutationError = ErrorType<unknown>

    /**
 * @summary Get Participants Collection by ID
 */
export const useGetCollectionsParticipantsRecordsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsParticipantsRecordsId>>, TError,{id: string;params?: GetCollectionsParticipantsRecordsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsParticipantsRecordsId>>,
        TError,
        {id: string;params?: GetCollectionsParticipantsRecordsIdParams},
        TContext
      > => {
      return useMutation(getGetCollectionsParticipantsRecordsIdMutationOptions(options), queryClient);
    }
    export type patchCollectionsParticipantsRecordsIdResponse200 = {
  data: ParticipantsRecord
  status: 200
}

export type patchCollectionsParticipantsRecordsIdResponseSuccess = (patchCollectionsParticipantsRecordsIdResponse200) & {
  headers: Headers;
};
;

export type patchCollectionsParticipantsRecordsIdResponse = (patchCollectionsParticipantsRecordsIdResponseSuccess)

export const getPatchCollectionsParticipantsRecordsIdUrl = (id: string,) => {




  return `/collections/participants/records/${id}`
}

/**
 * @summary Update Participants Collection Record
 */
export const patchCollectionsParticipantsRecordsId = async (id: string,
    participantsRecord?: ParticipantsRecord, options?: RequestInit): Promise<patchCollectionsParticipantsRecordsIdResponse> => {

  return customInstance<patchCollectionsParticipantsRecordsIdResponse>(getPatchCollectionsParticipantsRecordsIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(participantsRecord)
  }
);}





export const getPatchCollectionsParticipantsRecordsIdQueryKey = (id: string,
    participantsRecord?: BodyType<ParticipantsRecord>,) => {
    return [
    'PATCH', `/collections/participants/records/${id}`, participantsRecord
    ] as const;
    }


export const getPatchCollectionsParticipantsRecordsIdQueryOptions = <TData = Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>, TError = ErrorType<unknown>>(id: string,
    participantsRecord?: BodyType<ParticipantsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPatchCollectionsParticipantsRecordsIdQueryKey(id,participantsRecord);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>> = ({ signal }) => patchCollectionsParticipantsRecordsId(id,participantsRecord, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PatchCollectionsParticipantsRecordsIdQueryResult = NonNullable<Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>>
export type PatchCollectionsParticipantsRecordsIdQueryError = ErrorType<unknown>


export function usePatchCollectionsParticipantsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    participantsRecord: undefined |  BodyType<ParticipantsRecord>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatchCollectionsParticipantsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    participantsRecord?: BodyType<ParticipantsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatchCollectionsParticipantsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    participantsRecord?: BodyType<ParticipantsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update Participants Collection Record
 */

export function usePatchCollectionsParticipantsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    participantsRecord?: BodyType<ParticipantsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsParticipantsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPatchCollectionsParticipantsRecordsIdQueryOptions(id,participantsRecord,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteCollectionsParticipantsRecordsIdResponse204 = {
  data: void
  status: 204
}

export type deleteCollectionsParticipantsRecordsIdResponseSuccess = (deleteCollectionsParticipantsRecordsIdResponse204) & {
  headers: Headers;
};
;

export type deleteCollectionsParticipantsRecordsIdResponse = (deleteCollectionsParticipantsRecordsIdResponseSuccess)

export const getDeleteCollectionsParticipantsRecordsIdUrl = (id: string,) => {




  return `/collections/participants/records/${id}`
}

/**
 * @summary Delete Participants Collection Record
 */
export const deleteCollectionsParticipantsRecordsId = async (id: string, options?: RequestInit): Promise<deleteCollectionsParticipantsRecordsIdResponse> => {

  return customInstance<deleteCollectionsParticipantsRecordsIdResponse>(getDeleteCollectionsParticipantsRecordsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteCollectionsParticipantsRecordsIdQueryKey = (id: string,) => {
    return [
    'DELETE', `/collections/participants/records/${id}`
    ] as const;
    }


export const getDeleteCollectionsParticipantsRecordsIdQueryOptions = <TData = Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteCollectionsParticipantsRecordsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>> = ({ signal }) => deleteCollectionsParticipantsRecordsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteCollectionsParticipantsRecordsIdQueryResult = NonNullable<Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>>
export type DeleteCollectionsParticipantsRecordsIdQueryError = ErrorType<unknown>


export function useDeleteCollectionsParticipantsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteCollectionsParticipantsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteCollectionsParticipantsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete Participants Collection Record
 */

export function useDeleteCollectionsParticipantsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsParticipantsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteCollectionsParticipantsRecordsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






