/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import type { DraftSuggestionsRecordMatchLabel } from './draftSuggestionsRecordMatchLabel.ts';
import type { DraftSuggestionsRecordNotes } from './draftSuggestionsRecordNotes.ts';
import type { DraftSuggestionsRecordStatus } from './draftSuggestionsRecordStatus.ts';
import type { DraftSuggestionsRecordSuggestedBans } from './draftSuggestionsRecordSuggestedBans.ts';
import type { DraftSuggestionsRecordSuggestedPicks } from './draftSuggestionsRecordSuggestedPicks.ts';

export interface DraftSuggestionsRecord {
  /** Unique record identifier */
  id?: string;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  tournament_id?: string;
  tournament_title: string;
  match_label?: DraftSuggestionsRecordMatchLabel;
  suggested_bans?: DraftSuggestionsRecordSuggestedBans;
  suggested_picks?: DraftSuggestionsRecordSuggestedPicks;
  notes?: DraftSuggestionsRecordNotes;
  status?: DraftSuggestionsRecordStatus;
  created?: string;
  updated?: string;
}
