/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import type { TeamSuggestionsRecord } from './teamSuggestionsRecord.ts';

export type GetCollectionsTeamSuggestionsRecords200 = {
  page?: number;
  perPage?: number;
  totalItems?: number;
  totalPages?: number;
  items?: TeamSuggestionsRecord[];
};
