/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import type { MatchesRecord } from './matchesRecord.ts';

export type GetCollectionsMatchesRecords200 = {
  page?: number;
  perPage?: number;
  totalItems?: number;
  totalPages?: number;
  items?: MatchesRecord[];
};
