/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */

export type GetCollectionsTournamentDraftsRecordsParams = {
/**
 * Filtering expression (e.g., 'created > "2022-01-01"')
 */
filter?: string;
/**
 * Comma-separated list of fields to sort by. Prefix with '-' for descending order.
 */
sort?: string;
/**
 * Page number (starting from 1)
 * @minimum 1
 */
page?: number;
/**
 * Number of records per page (max 500)
 * @minimum 1
 * @maximum 500
 */
perPage?: number;
/**
 * Set to true to skip the total count (improves performance for large collections)
 */
skipTotal?: boolean;
/**
 * Comma-separated list of relations to expand. Use dot notation for nested relations.
 */
expand?: string;
};
