/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */

export type GetCollectionsMatchDraftsRecordsIdParams = {
/**
 * Comma-separated list of relations to expand. Use dot notation for nested relations.
 */
expand?: string;
};
