/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import type { AuditLogRecord } from './auditLogRecord.ts';

export type GetCollectionsAuditLogRecords200 = {
  page?: number;
  perPage?: number;
  totalItems?: number;
  totalPages?: number;
  items?: AuditLogRecord[];
};
