/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */

export type MatchDraftsRecordStatus = typeof MatchDraftsRecordStatus[keyof typeof MatchDraftsRecordStatus];


export const MatchDraftsRecordStatus = {
  pending: 'pending',
  active: 'active',
  completed: 'completed',
} as const;
