/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import type { MatchDraftsRecordBans } from './matchDraftsRecordBans.ts';
import type { MatchDraftsRecordPicks } from './matchDraftsRecordPicks.ts';
import type { MatchDraftsRecordStatus } from './matchDraftsRecordStatus.ts';

export interface MatchDraftsRecord {
  /** Unique record identifier */
  id?: string;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  tournament: string;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  team_a?: string;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  team_b?: string;
  match_label?: string;
  game_number?: number;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  first_pick_team?: string;
  bans?: MatchDraftsRecordBans;
  picks?: MatchDraftsRecordPicks;
  status: MatchDraftsRecordStatus;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  created_by?: string;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  updated_by?: string;
  archived: boolean;
  created?: string;
  updated?: string;
}
