/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import type { MatchResultRecordLane } from './matchResultRecordLane.ts';

export interface MatchResultRecord {
  /** Unique record identifier */
  id?: string;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  match: string;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  player: string;
  lane?: MatchResultRecordLane;
  kills?: number;
  deaths?: number;
  assists?: number;
  game_performance_rating?: number;
  accumulated_gold?: number;
  archived: boolean;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  created_by?: string;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  updated_by?: string;
  created?: string;
  updated?: string;
}
