/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */

export type MatchesRecordStatus = typeof MatchesRecordStatus[keyof typeof MatchesRecordStatus];


export const MatchesRecordStatus = {
  draft: 'draft',
  scheduled: 'scheduled',
  live: 'live',
  completed: 'completed',
  walkover: 'walkover',
  cancelled: 'cancelled',
} as const;
