/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */

export type ParticipantsRecordTeamIntent = typeof ParticipantsRecordTeamIntent[keyof typeof ParticipantsRecordTeamIntent];


export const ParticipantsRecordTeamIntent = {
  open_matching: 'open_matching',
  join_team: 'join_team',
  create_team: 'create_team',
} as const;
