/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */

export type ParticipantsRecordAddressPhase = typeof ParticipantsRecordAddressPhase[keyof typeof ParticipantsRecordAddressPhase];


export const ParticipantsRecordAddressPhase = {
  NUMBER_4: '4',
  NUMBER_9: '9',
  NUMBER_10: '10',
} as const;
