/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import type { PostCollectionsAdminsRecordsBodyRole } from './postCollectionsAdminsRecordsBodyRole.ts';

export type PostCollectionsAdminsRecordsBody = {
  /**
     * @minLength 15
     * @maxLength 15
     * @pattern ^[a-z0-9]+$
     */
  id: string;
  password: string;
  /**
     * @minLength 30
     * @maxLength 60
     */
  tokenKey: string;
  email: string;
  emailVisibility?: boolean;
  verified?: boolean;
  name: string;
  role: PostCollectionsAdminsRecordsBodyRole;
  is_active: boolean;
  last_login_at?: string;
  created?: string;
  updated?: string;
  passwordConfirm: string;
};
