/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */

export type TeamSuggestionsRecordPreferredRole1 = typeof TeamSuggestionsRecordPreferredRole1[keyof typeof TeamSuggestionsRecordPreferredRole1];


export const TeamSuggestionsRecordPreferredRole1 = {
  mid: 'mid',
  gold: 'gold',
  exp: 'exp',
  support: 'support',
  jungle: 'jungle',
} as const;
