/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import type { TeamSuggestionsRecordAccumulatedGold } from './teamSuggestionsRecordAccumulatedGold.ts';
import type { TeamSuggestionsRecordGamePerformanceRating } from './teamSuggestionsRecordGamePerformanceRating.ts';
import type { TeamSuggestionsRecordKda } from './teamSuggestionsRecordKda.ts';
import type { TeamSuggestionsRecordParticipantHasTeam } from './teamSuggestionsRecordParticipantHasTeam.ts';
import type { TeamSuggestionsRecordParticipantStatus } from './teamSuggestionsRecordParticipantStatus.ts';
import type { TeamSuggestionsRecordPreferredRole1 } from './teamSuggestionsRecordPreferredRole1.ts';
import type { TeamSuggestionsRecordPreferredRole2 } from './teamSuggestionsRecordPreferredRole2.ts';
import type { TeamSuggestionsRecordPreferredRole3 } from './teamSuggestionsRecordPreferredRole3.ts';
import type { TeamSuggestionsRecordRankingBasis } from './teamSuggestionsRecordRankingBasis.ts';
import type { TeamSuggestionsRecordReason } from './teamSuggestionsRecordReason.ts';
import type { TeamSuggestionsRecordRoleDataQuality } from './teamSuggestionsRecordRoleDataQuality.ts';
import type { TeamSuggestionsRecordRoleFit } from './teamSuggestionsRecordRoleFit.ts';
import type { TeamSuggestionsRecordRoleMatchLevel } from './teamSuggestionsRecordRoleMatchLevel.ts';
import type { TeamSuggestionsRecordRoleMatchScore } from './teamSuggestionsRecordRoleMatchScore.ts';
import type { TeamSuggestionsRecordSortScore } from './teamSuggestionsRecordSortScore.ts';
import type { TeamSuggestionsRecordStatus } from './teamSuggestionsRecordStatus.ts';
import type { TeamSuggestionsRecordSuggestedTeamStatus } from './teamSuggestionsRecordSuggestedTeamStatus.ts';
import type { TeamSuggestionsRecordSuggestionPriority } from './teamSuggestionsRecordSuggestionPriority.ts';
import type { TeamSuggestionsRecordTeamMemberCount } from './teamSuggestionsRecordTeamMemberCount.ts';
import type { TeamSuggestionsRecordTeamSlotsLeft } from './teamSuggestionsRecordTeamSlotsLeft.ts';

export interface TeamSuggestionsRecord {
  /** Unique record identifier */
  id?: string;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  participant_id?: string;
  participant_game_id: string;
  participant_status: TeamSuggestionsRecordParticipantStatus;
  participant_has_team?: TeamSuggestionsRecordParticipantHasTeam;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  suggested_team_id?: string;
  suggested_team_name: string;
  suggested_team_status: TeamSuggestionsRecordSuggestedTeamStatus;
  role_fit: TeamSuggestionsRecordRoleFit;
  preferred_role_1: TeamSuggestionsRecordPreferredRole1;
  preferred_role_2?: TeamSuggestionsRecordPreferredRole2;
  preferred_role_3?: TeamSuggestionsRecordPreferredRole3;
  role_data_quality?: TeamSuggestionsRecordRoleDataQuality;
  role_match_score?: TeamSuggestionsRecordRoleMatchScore;
  role_match_level?: TeamSuggestionsRecordRoleMatchLevel;
  ranking_basis?: TeamSuggestionsRecordRankingBasis;
  game_performance_rating?: TeamSuggestionsRecordGamePerformanceRating;
  kda?: TeamSuggestionsRecordKda;
  accumulated_gold?: TeamSuggestionsRecordAccumulatedGold;
  team_member_count?: TeamSuggestionsRecordTeamMemberCount;
  team_slots_left?: TeamSuggestionsRecordTeamSlotsLeft;
  suggestion_priority?: TeamSuggestionsRecordSuggestionPriority;
  sort_score?: TeamSuggestionsRecordSortScore;
  reason?: TeamSuggestionsRecordReason;
  status?: TeamSuggestionsRecordStatus;
  created?: string;
  updated?: string;
}
