/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */

export type TeamSuggestionsRecordParticipantStatus = typeof TeamSuggestionsRecordParticipantStatus[keyof typeof TeamSuggestionsRecordParticipantStatus];


export const TeamSuggestionsRecordParticipantStatus = {
  unassigned: 'unassigned',
  suggested: 'suggested',
  assigned: 'assigned',
  inactive: 'inactive',
} as const;
