/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */

export interface TournamentDraftsRecord {
  /** Unique record identifier */
  id?: string;
  title: string;
  format?: string;
  rules?: string;
  max_teams?: number;
  scheduled_at?: string;
  notes?: string;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  publish_to_tournament?: string;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  created_by?: string;
  /** Relation field. When expanded, this becomes the related record object. Use the 'expand' query parameter to expand relations. */
  updated_by?: string;
  archived?: boolean;
  created?: string;
  updated?: string;
}
