/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Register new Admins Collection
 */
export const postCollectionsAdminsRecordsBodyIdMin = 15;
export const postCollectionsAdminsRecordsBodyIdMax = 15;


export const postCollectionsAdminsRecordsBodyIdRegExp = new RegExp('^[a-z0-9]+$');
export const postCollectionsAdminsRecordsBodyTokenKeyMin = 30;
export const postCollectionsAdminsRecordsBodyTokenKeyMax = 60;



export const PostCollectionsAdminsRecordsBody = zod.object({
  "id": zod.string().min(postCollectionsAdminsRecordsBodyIdMin).max(postCollectionsAdminsRecordsBodyIdMax).regex(postCollectionsAdminsRecordsBodyIdRegExp),
  "password": zod.string(),
  "tokenKey": zod.string().min(postCollectionsAdminsRecordsBodyTokenKeyMin).max(postCollectionsAdminsRecordsBodyTokenKeyMax),
  "email": zod.email(),
  "emailVisibility": zod.boolean().optional(),
  "verified": zod.boolean().optional(),
  "name": zod.string(),
  "role": zod.enum(['superadmin', 'staff']),
  "is_active": zod.boolean(),
  "last_login_at": zod.iso.datetime({"offset":true}).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional(),
  "passwordConfirm": zod.string()
})

export const postCollectionsAdminsRecordsResponseRecordPasswordMin = 8;

export const postCollectionsAdminsRecordsResponseRecordTokenKeyMin = 30;
export const postCollectionsAdminsRecordsResponseRecordTokenKeyMax = 60;



export const PostCollectionsAdminsRecordsResponse = zod.object({
  "token": zod.string().optional(),
  "record": zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "password": zod.string().min(postCollectionsAdminsRecordsResponseRecordPasswordMin),
  "tokenKey": zod.string().min(postCollectionsAdminsRecordsResponseRecordTokenKeyMin).max(postCollectionsAdminsRecordsResponseRecordTokenKeyMax),
  "email": zod.email(),
  "emailVisibility": zod.boolean().optional(),
  "verified": zod.boolean().optional(),
  "name": zod.string(),
  "role": zod.enum(['superadmin', 'staff']),
  "is_active": zod.boolean(),
  "last_login_at": zod.iso.datetime({"offset":true}).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
}).optional()
})

/**
 * @summary Get Admins Collection by ID
 */
export const GetCollectionsAdminsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const getCollectionsAdminsRecordsIdResponsePasswordMin = 8;

export const getCollectionsAdminsRecordsIdResponseTokenKeyMin = 30;
export const getCollectionsAdminsRecordsIdResponseTokenKeyMax = 60;



export const GetCollectionsAdminsRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "password": zod.string().min(getCollectionsAdminsRecordsIdResponsePasswordMin),
  "tokenKey": zod.string().min(getCollectionsAdminsRecordsIdResponseTokenKeyMin).max(getCollectionsAdminsRecordsIdResponseTokenKeyMax),
  "email": zod.email(),
  "emailVisibility": zod.boolean().optional(),
  "verified": zod.boolean().optional(),
  "name": zod.string(),
  "role": zod.enum(['superadmin', 'staff']),
  "is_active": zod.boolean(),
  "last_login_at": zod.iso.datetime({"offset":true}).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Update Admins Collection Record
 */
export const PatchCollectionsAdminsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const patchCollectionsAdminsRecordsIdBodyPasswordMin = 8;

export const patchCollectionsAdminsRecordsIdBodyTokenKeyMin = 30;
export const patchCollectionsAdminsRecordsIdBodyTokenKeyMax = 60;



export const PatchCollectionsAdminsRecordsIdBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "password": zod.string().min(patchCollectionsAdminsRecordsIdBodyPasswordMin),
  "tokenKey": zod.string().min(patchCollectionsAdminsRecordsIdBodyTokenKeyMin).max(patchCollectionsAdminsRecordsIdBodyTokenKeyMax),
  "email": zod.email(),
  "emailVisibility": zod.boolean().optional(),
  "verified": zod.boolean().optional(),
  "name": zod.string(),
  "role": zod.enum(['superadmin', 'staff']),
  "is_active": zod.boolean(),
  "last_login_at": zod.iso.datetime({"offset":true}).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const patchCollectionsAdminsRecordsIdResponsePasswordMin = 8;

export const patchCollectionsAdminsRecordsIdResponseTokenKeyMin = 30;
export const patchCollectionsAdminsRecordsIdResponseTokenKeyMax = 60;



export const PatchCollectionsAdminsRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "password": zod.string().min(patchCollectionsAdminsRecordsIdResponsePasswordMin),
  "tokenKey": zod.string().min(patchCollectionsAdminsRecordsIdResponseTokenKeyMin).max(patchCollectionsAdminsRecordsIdResponseTokenKeyMax),
  "email": zod.email(),
  "emailVisibility": zod.boolean().optional(),
  "verified": zod.boolean().optional(),
  "name": zod.string(),
  "role": zod.enum(['superadmin', 'staff']),
  "is_active": zod.boolean(),
  "last_login_at": zod.iso.datetime({"offset":true}).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Delete Admins Collection Record
 */
export const DeleteCollectionsAdminsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const DeleteCollectionsAdminsRecordsIdResponse = zod.void()

/**
 * @summary Authenticate Admins Collection with password
 */
export const PostCollectionsAdminsAuthWithPasswordBody = zod.object({
  "identity": zod.string(),
  "password": zod.string()
})

export const postCollectionsAdminsAuthWithPasswordResponseRecordPasswordMin = 8;

export const postCollectionsAdminsAuthWithPasswordResponseRecordTokenKeyMin = 30;
export const postCollectionsAdminsAuthWithPasswordResponseRecordTokenKeyMax = 60;



export const PostCollectionsAdminsAuthWithPasswordResponse = zod.object({
  "token": zod.string().optional(),
  "record": zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "password": zod.string().min(postCollectionsAdminsAuthWithPasswordResponseRecordPasswordMin),
  "tokenKey": zod.string().min(postCollectionsAdminsAuthWithPasswordResponseRecordTokenKeyMin).max(postCollectionsAdminsAuthWithPasswordResponseRecordTokenKeyMax),
  "email": zod.email(),
  "emailVisibility": zod.boolean().optional(),
  "verified": zod.boolean().optional(),
  "name": zod.string(),
  "role": zod.enum(['superadmin', 'staff']),
  "is_active": zod.boolean(),
  "last_login_at": zod.iso.datetime({"offset":true}).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
}).optional()
})

/**
 * @summary Request Admins Collection verification
 */
export const PostCollectionsAdminsRequestVerificationBody = zod.object({
  "email": zod.email()
})

export const PostCollectionsAdminsRequestVerificationResponse = zod.object({
  "success": zod.boolean().optional()
})

/**
 * @summary Confirm Admins Collection verification
 */
export const PostCollectionsAdminsConfirmVerificationBody = zod.object({
  "token": zod.string()
})

export const PostCollectionsAdminsConfirmVerificationResponse = zod.object({
  "success": zod.boolean().optional()
})

/**
 * @summary Request Admins Collection password reset
 */
export const PostCollectionsAdminsRequestPasswordResetBody = zod.object({
  "email": zod.email()
})

export const PostCollectionsAdminsRequestPasswordResetResponse = zod.object({
  "success": zod.boolean().optional()
})

/**
 * @summary Confirm Admins Collection password reset
 */
export const PostCollectionsAdminsConfirmPasswordResetBody = zod.object({
  "token": zod.string(),
  "password": zod.string(),
  "passwordConfirm": zod.string()
})

export const PostCollectionsAdminsConfirmPasswordResetResponse = zod.object({
  "success": zod.boolean().optional()
})

/**
 * @summary Request Admins Collection email change
 */
export const PostCollectionsAdminsRequestEmailChangeBody = zod.object({
  "newEmail": zod.email()
})

export const PostCollectionsAdminsRequestEmailChangeResponse = zod.object({
  "success": zod.boolean().optional()
})

/**
 * @summary Confirm Admins Collection email change
 */
export const PostCollectionsAdminsConfirmEmailChangeBody = zod.object({
  "token": zod.string(),
  "password": zod.string()
})

export const PostCollectionsAdminsConfirmEmailChangeResponse = zod.object({
  "success": zod.boolean().optional()
})

/**
 * @summary Refresh Admins Collection authentication token
 */
export const postCollectionsAdminsAuthRefreshResponseRecordPasswordMin = 8;

export const postCollectionsAdminsAuthRefreshResponseRecordTokenKeyMin = 30;
export const postCollectionsAdminsAuthRefreshResponseRecordTokenKeyMax = 60;



export const PostCollectionsAdminsAuthRefreshResponse = zod.object({
  "token": zod.string().optional(),
  "record": zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "password": zod.string().min(postCollectionsAdminsAuthRefreshResponseRecordPasswordMin),
  "tokenKey": zod.string().min(postCollectionsAdminsAuthRefreshResponseRecordTokenKeyMin).max(postCollectionsAdminsAuthRefreshResponseRecordTokenKeyMax),
  "email": zod.email(),
  "emailVisibility": zod.boolean().optional(),
  "verified": zod.boolean().optional(),
  "name": zod.string(),
  "role": zod.enum(['superadmin', 'staff']),
  "is_active": zod.boolean(),
  "last_login_at": zod.iso.datetime({"offset":true}).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
}).optional()
})

/**
 * @summary Authenticate Admins Collection with OAuth2
 */
export const PostCollectionsAdminsAuthWithOauth2Body = zod.object({
  "provider": zod.string(),
  "code": zod.string(),
  "codeVerifier": zod.string().optional(),
  "redirectUrl": zod.string().optional()
})

export const postCollectionsAdminsAuthWithOauth2ResponseRecordPasswordMin = 8;

export const postCollectionsAdminsAuthWithOauth2ResponseRecordTokenKeyMin = 30;
export const postCollectionsAdminsAuthWithOauth2ResponseRecordTokenKeyMax = 60;



export const PostCollectionsAdminsAuthWithOauth2Response = zod.object({
  "token": zod.string().optional(),
  "record": zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "password": zod.string().min(postCollectionsAdminsAuthWithOauth2ResponseRecordPasswordMin),
  "tokenKey": zod.string().min(postCollectionsAdminsAuthWithOauth2ResponseRecordTokenKeyMin).max(postCollectionsAdminsAuthWithOauth2ResponseRecordTokenKeyMax),
  "email": zod.email(),
  "emailVisibility": zod.boolean().optional(),
  "verified": zod.boolean().optional(),
  "name": zod.string(),
  "role": zod.enum(['superadmin', 'staff']),
  "is_active": zod.boolean(),
  "last_login_at": zod.iso.datetime({"offset":true}).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
}).optional()
})

