/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetCollectionsTournamentDraftsRecords200,
  GetCollectionsTournamentDraftsRecordsIdParams,
  GetCollectionsTournamentDraftsRecordsParams,
  TournamentDraftsRecord
} from '../model';

import { customInstance } from '../../../lib/api/mutator/custom-instance.ts';
import type { ErrorType , BodyType } from '../../../lib/api/mutator/custom-instance.ts';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getCollectionsTournamentDraftsRecordsResponse200 = {
  data: GetCollectionsTournamentDraftsRecords200
  status: 200
}

export type getCollectionsTournamentDraftsRecordsResponseSuccess = (getCollectionsTournamentDraftsRecordsResponse200) & {
  headers: Headers;
};
;

export type getCollectionsTournamentDraftsRecordsResponse = (getCollectionsTournamentDraftsRecordsResponseSuccess)

export const getGetCollectionsTournamentDraftsRecordsUrl = (params?: GetCollectionsTournamentDraftsRecordsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collections/tournament_drafts/records?${stringifiedParams}` : `/collections/tournament_drafts/records`
}

/**
 * Retrieves a paginated list of Tournament_drafts Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Tournament_drafts Collection
 */
export const getCollectionsTournamentDraftsRecords = async (params?: GetCollectionsTournamentDraftsRecordsParams, options?: RequestInit): Promise<getCollectionsTournamentDraftsRecordsResponse> => {

  return customInstance<getCollectionsTournamentDraftsRecordsResponse>(getGetCollectionsTournamentDraftsRecordsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsTournamentDraftsRecordsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTournamentDraftsRecords>>, TError,{params?: GetCollectionsTournamentDraftsRecordsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTournamentDraftsRecords>>, TError,{params?: GetCollectionsTournamentDraftsRecordsParams}, TContext> => {

const mutationKey = ['getCollectionsTournamentDraftsRecords'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsTournamentDraftsRecords>>, {params?: GetCollectionsTournamentDraftsRecordsParams}> = (props) => {
          const {params} = props ?? {};

          return  getCollectionsTournamentDraftsRecords(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsTournamentDraftsRecordsMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsTournamentDraftsRecords>>>

    export type GetCollectionsTournamentDraftsRecordsMutationError = ErrorType<unknown>

    /**
 * @summary List Tournament_drafts Collection
 */
export const useGetCollectionsTournamentDraftsRecords = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTournamentDraftsRecords>>, TError,{params?: GetCollectionsTournamentDraftsRecordsParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsTournamentDraftsRecords>>,
        TError,
        {params?: GetCollectionsTournamentDraftsRecordsParams},
        TContext
      > => {
      return useMutation(getGetCollectionsTournamentDraftsRecordsMutationOptions(options), queryClient);
    }
    export type postCollectionsTournamentDraftsRecordsResponse200 = {
  data: TournamentDraftsRecord
  status: 200
}

export type postCollectionsTournamentDraftsRecordsResponseSuccess = (postCollectionsTournamentDraftsRecordsResponse200) & {
  headers: Headers;
};
;

export type postCollectionsTournamentDraftsRecordsResponse = (postCollectionsTournamentDraftsRecordsResponseSuccess)

export const getPostCollectionsTournamentDraftsRecordsUrl = () => {




  return `/collections/tournament_drafts/records`
}

/**
 * @summary Create Tournament_drafts Collection Record
 */
export const postCollectionsTournamentDraftsRecords = async (tournamentDraftsRecord?: TournamentDraftsRecord, options?: RequestInit): Promise<postCollectionsTournamentDraftsRecordsResponse> => {

  return customInstance<postCollectionsTournamentDraftsRecordsResponse>(getPostCollectionsTournamentDraftsRecordsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(tournamentDraftsRecord)
  }
);}





export const getPostCollectionsTournamentDraftsRecordsQueryKey = (tournamentDraftsRecord?: BodyType<TournamentDraftsRecord>,) => {
    return [
    'POST', `/collections/tournament_drafts/records`, tournamentDraftsRecord
    ] as const;
    }


export const getPostCollectionsTournamentDraftsRecordsQueryOptions = <TData = Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>, TError = ErrorType<unknown>>(tournamentDraftsRecord?: BodyType<TournamentDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPostCollectionsTournamentDraftsRecordsQueryKey(tournamentDraftsRecord);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>> = ({ signal }) => postCollectionsTournamentDraftsRecords(tournamentDraftsRecord, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PostCollectionsTournamentDraftsRecordsQueryResult = NonNullable<Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>>
export type PostCollectionsTournamentDraftsRecordsQueryError = ErrorType<unknown>


export function usePostCollectionsTournamentDraftsRecords<TData = Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>, TError = ErrorType<unknown>>(
 tournamentDraftsRecord: undefined |  BodyType<TournamentDraftsRecord>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsTournamentDraftsRecords<TData = Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>, TError = ErrorType<unknown>>(
 tournamentDraftsRecord?: BodyType<TournamentDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>,
          TError,
          Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePostCollectionsTournamentDraftsRecords<TData = Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>, TError = ErrorType<unknown>>(
 tournamentDraftsRecord?: BodyType<TournamentDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Create Tournament_drafts Collection Record
 */

export function usePostCollectionsTournamentDraftsRecords<TData = Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>, TError = ErrorType<unknown>>(
 tournamentDraftsRecord?: BodyType<TournamentDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof postCollectionsTournamentDraftsRecords>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPostCollectionsTournamentDraftsRecordsQueryOptions(tournamentDraftsRecord,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getCollectionsTournamentDraftsRecordsIdResponse200 = {
  data: TournamentDraftsRecord
  status: 200
}

export type getCollectionsTournamentDraftsRecordsIdResponseSuccess = (getCollectionsTournamentDraftsRecordsIdResponse200) & {
  headers: Headers;
};
;

export type getCollectionsTournamentDraftsRecordsIdResponse = (getCollectionsTournamentDraftsRecordsIdResponseSuccess)

export const getGetCollectionsTournamentDraftsRecordsIdUrl = (id: string,
    params?: GetCollectionsTournamentDraftsRecordsIdParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/collections/tournament_drafts/records/${id}?${stringifiedParams}` : `/collections/tournament_drafts/records/${id}`
}

/**
 * @summary Get Tournament_drafts Collection by ID
 */
export const getCollectionsTournamentDraftsRecordsId = async (id: string,
    params?: GetCollectionsTournamentDraftsRecordsIdParams, options?: RequestInit): Promise<getCollectionsTournamentDraftsRecordsIdResponse> => {

  return customInstance<getCollectionsTournamentDraftsRecordsIdResponse>(getGetCollectionsTournamentDraftsRecordsIdUrl(id,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCollectionsTournamentDraftsRecordsIdMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTournamentDraftsRecordsId>>, TError,{id: string;params?: GetCollectionsTournamentDraftsRecordsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTournamentDraftsRecordsId>>, TError,{id: string;params?: GetCollectionsTournamentDraftsRecordsIdParams}, TContext> => {

const mutationKey = ['getCollectionsTournamentDraftsRecordsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCollectionsTournamentDraftsRecordsId>>, {id: string;params?: GetCollectionsTournamentDraftsRecordsIdParams}> = (props) => {
          const {id,params} = props ?? {};

          return  getCollectionsTournamentDraftsRecordsId(id,params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetCollectionsTournamentDraftsRecordsIdMutationResult = NonNullable<Awaited<ReturnType<typeof getCollectionsTournamentDraftsRecordsId>>>

    export type GetCollectionsTournamentDraftsRecordsIdMutationError = ErrorType<unknown>

    /**
 * @summary Get Tournament_drafts Collection by ID
 */
export const useGetCollectionsTournamentDraftsRecordsId = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCollectionsTournamentDraftsRecordsId>>, TError,{id: string;params?: GetCollectionsTournamentDraftsRecordsIdParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCollectionsTournamentDraftsRecordsId>>,
        TError,
        {id: string;params?: GetCollectionsTournamentDraftsRecordsIdParams},
        TContext
      > => {
      return useMutation(getGetCollectionsTournamentDraftsRecordsIdMutationOptions(options), queryClient);
    }
    export type patchCollectionsTournamentDraftsRecordsIdResponse200 = {
  data: TournamentDraftsRecord
  status: 200
}

export type patchCollectionsTournamentDraftsRecordsIdResponseSuccess = (patchCollectionsTournamentDraftsRecordsIdResponse200) & {
  headers: Headers;
};
;

export type patchCollectionsTournamentDraftsRecordsIdResponse = (patchCollectionsTournamentDraftsRecordsIdResponseSuccess)

export const getPatchCollectionsTournamentDraftsRecordsIdUrl = (id: string,) => {




  return `/collections/tournament_drafts/records/${id}`
}

/**
 * @summary Update Tournament_drafts Collection Record
 */
export const patchCollectionsTournamentDraftsRecordsId = async (id: string,
    tournamentDraftsRecord?: TournamentDraftsRecord, options?: RequestInit): Promise<patchCollectionsTournamentDraftsRecordsIdResponse> => {

  return customInstance<patchCollectionsTournamentDraftsRecordsIdResponse>(getPatchCollectionsTournamentDraftsRecordsIdUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(tournamentDraftsRecord)
  }
);}





export const getPatchCollectionsTournamentDraftsRecordsIdQueryKey = (id: string,
    tournamentDraftsRecord?: BodyType<TournamentDraftsRecord>,) => {
    return [
    'PATCH', `/collections/tournament_drafts/records/${id}`, tournamentDraftsRecord
    ] as const;
    }


export const getPatchCollectionsTournamentDraftsRecordsIdQueryOptions = <TData = Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>, TError = ErrorType<unknown>>(id: string,
    tournamentDraftsRecord?: BodyType<TournamentDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPatchCollectionsTournamentDraftsRecordsIdQueryKey(id,tournamentDraftsRecord);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>> = ({ signal }) => patchCollectionsTournamentDraftsRecordsId(id,tournamentDraftsRecord, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PatchCollectionsTournamentDraftsRecordsIdQueryResult = NonNullable<Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>>
export type PatchCollectionsTournamentDraftsRecordsIdQueryError = ErrorType<unknown>


export function usePatchCollectionsTournamentDraftsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    tournamentDraftsRecord: undefined |  BodyType<TournamentDraftsRecord>, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatchCollectionsTournamentDraftsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    tournamentDraftsRecord?: BodyType<TournamentDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePatchCollectionsTournamentDraftsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    tournamentDraftsRecord?: BodyType<TournamentDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Update Tournament_drafts Collection Record
 */

export function usePatchCollectionsTournamentDraftsRecordsId<TData = Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string,
    tournamentDraftsRecord?: BodyType<TournamentDraftsRecord>, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof patchCollectionsTournamentDraftsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPatchCollectionsTournamentDraftsRecordsIdQueryOptions(id,tournamentDraftsRecord,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deleteCollectionsTournamentDraftsRecordsIdResponse204 = {
  data: void
  status: 204
}

export type deleteCollectionsTournamentDraftsRecordsIdResponseSuccess = (deleteCollectionsTournamentDraftsRecordsIdResponse204) & {
  headers: Headers;
};
;

export type deleteCollectionsTournamentDraftsRecordsIdResponse = (deleteCollectionsTournamentDraftsRecordsIdResponseSuccess)

export const getDeleteCollectionsTournamentDraftsRecordsIdUrl = (id: string,) => {




  return `/collections/tournament_drafts/records/${id}`
}

/**
 * @summary Delete Tournament_drafts Collection Record
 */
export const deleteCollectionsTournamentDraftsRecordsId = async (id: string, options?: RequestInit): Promise<deleteCollectionsTournamentDraftsRecordsIdResponse> => {

  return customInstance<deleteCollectionsTournamentDraftsRecordsIdResponse>(getDeleteCollectionsTournamentDraftsRecordsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteCollectionsTournamentDraftsRecordsIdQueryKey = (id: string,) => {
    return [
    'DELETE', `/collections/tournament_drafts/records/${id}`
    ] as const;
    }


export const getDeleteCollectionsTournamentDraftsRecordsIdQueryOptions = <TData = Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>, TError = ErrorType<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDeleteCollectionsTournamentDraftsRecordsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>> = ({ signal }) => deleteCollectionsTournamentDraftsRecordsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DeleteCollectionsTournamentDraftsRecordsIdQueryResult = NonNullable<Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>>
export type DeleteCollectionsTournamentDraftsRecordsIdQueryError = ErrorType<unknown>


export function useDeleteCollectionsTournamentDraftsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteCollectionsTournamentDraftsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>,
          TError,
          Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDeleteCollectionsTournamentDraftsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Delete Tournament_drafts Collection Record
 */

export function useDeleteCollectionsTournamentDraftsRecordsId<TData = Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>, TError = ErrorType<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof deleteCollectionsTournamentDraftsRecordsId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDeleteCollectionsTournamentDraftsRecordsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






