/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Retrieves a paginated list of Match_drafts Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Match_drafts Collection
 */
export const getCollectionsMatchDraftsRecordsQueryPageDefault = 1;

export const getCollectionsMatchDraftsRecordsQueryPerPageDefault = 30;
export const getCollectionsMatchDraftsRecordsQueryPerPageMax = 500;

export const getCollectionsMatchDraftsRecordsQuerySkipTotalDefault = false;

export const GetCollectionsMatchDraftsRecordsQueryParams = zod.object({
  "filter": zod.string().optional().describe('Filtering expression (e.g., \'created > \"2022-01-01\"\')'),
  "sort": zod.string().optional().describe('Comma-separated list of fields to sort by. Prefix with \'-\' for descending order.'),
  "page": zod.number().min(1).default(getCollectionsMatchDraftsRecordsQueryPageDefault).describe('Page number (starting from 1)'),
  "perPage": zod.number().min(1).max(getCollectionsMatchDraftsRecordsQueryPerPageMax).default(getCollectionsMatchDraftsRecordsQueryPerPageDefault).describe('Number of records per page (max 500)'),
  "skipTotal": zod.boolean().default(getCollectionsMatchDraftsRecordsQuerySkipTotalDefault).describe('Set to true to skip the total count (improves performance for large collections)'),
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsMatchDraftsRecordsResponse = zod.object({
  "page": zod.number().optional(),
  "perPage": zod.number().optional(),
  "totalItems": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "items": zod.array(zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_a": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_b": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "match_label": zod.string().optional(),
  "game_number": zod.number().optional(),
  "first_pick_team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "bans": zod.record(zod.string(), zod.unknown()).optional(),
  "picks": zod.record(zod.string(), zod.unknown()).optional(),
  "status": zod.enum(['pending', 'active', 'completed']),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})).optional()
})

/**
 * @summary Create Match_drafts Collection Record
 */
export const PostCollectionsMatchDraftsRecordsBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_a": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_b": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "match_label": zod.string().optional(),
  "game_number": zod.number().optional(),
  "first_pick_team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "bans": zod.record(zod.string(), zod.unknown()).optional(),
  "picks": zod.record(zod.string(), zod.unknown()).optional(),
  "status": zod.enum(['pending', 'active', 'completed']),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const PostCollectionsMatchDraftsRecordsResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_a": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_b": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "match_label": zod.string().optional(),
  "game_number": zod.number().optional(),
  "first_pick_team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "bans": zod.record(zod.string(), zod.unknown()).optional(),
  "picks": zod.record(zod.string(), zod.unknown()).optional(),
  "status": zod.enum(['pending', 'active', 'completed']),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Get Match_drafts Collection by ID
 */
export const GetCollectionsMatchDraftsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const GetCollectionsMatchDraftsRecordsIdQueryParams = zod.object({
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsMatchDraftsRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_a": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_b": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "match_label": zod.string().optional(),
  "game_number": zod.number().optional(),
  "first_pick_team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "bans": zod.record(zod.string(), zod.unknown()).optional(),
  "picks": zod.record(zod.string(), zod.unknown()).optional(),
  "status": zod.enum(['pending', 'active', 'completed']),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Update Match_drafts Collection Record
 */
export const PatchCollectionsMatchDraftsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const PatchCollectionsMatchDraftsRecordsIdBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_a": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_b": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "match_label": zod.string().optional(),
  "game_number": zod.number().optional(),
  "first_pick_team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "bans": zod.record(zod.string(), zod.unknown()).optional(),
  "picks": zod.record(zod.string(), zod.unknown()).optional(),
  "status": zod.enum(['pending', 'active', 'completed']),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const PatchCollectionsMatchDraftsRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_a": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_b": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "match_label": zod.string().optional(),
  "game_number": zod.number().optional(),
  "first_pick_team": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "bans": zod.record(zod.string(), zod.unknown()).optional(),
  "picks": zod.record(zod.string(), zod.unknown()).optional(),
  "status": zod.enum(['pending', 'active', 'completed']),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Delete Match_drafts Collection Record
 */
export const DeleteCollectionsMatchDraftsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const DeleteCollectionsMatchDraftsRecordsIdResponse = zod.void()

