/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Retrieves a paginated list of Team_suggestions Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Team_suggestions Collection
 */
export const getCollectionsTeamSuggestionsRecordsQueryPageDefault = 1;

export const getCollectionsTeamSuggestionsRecordsQueryPerPageDefault = 30;
export const getCollectionsTeamSuggestionsRecordsQueryPerPageMax = 500;

export const getCollectionsTeamSuggestionsRecordsQuerySkipTotalDefault = false;

export const GetCollectionsTeamSuggestionsRecordsQueryParams = zod.object({
  "filter": zod.string().optional().describe('Filtering expression (e.g., \'created > \"2022-01-01\"\')'),
  "sort": zod.string().optional().describe('Comma-separated list of fields to sort by. Prefix with \'-\' for descending order.'),
  "page": zod.number().min(1).default(getCollectionsTeamSuggestionsRecordsQueryPageDefault).describe('Page number (starting from 1)'),
  "perPage": zod.number().min(1).max(getCollectionsTeamSuggestionsRecordsQueryPerPageMax).default(getCollectionsTeamSuggestionsRecordsQueryPerPageDefault).describe('Number of records per page (max 500)'),
  "skipTotal": zod.boolean().default(getCollectionsTeamSuggestionsRecordsQuerySkipTotalDefault).describe('Set to true to skip the total count (improves performance for large collections)'),
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsTeamSuggestionsRecordsResponse = zod.object({
  "page": zod.number().optional(),
  "perPage": zod.number().optional(),
  "totalItems": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "items": zod.array(zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "participant_id": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "participant_game_id": zod.string(),
  "participant_status": zod.enum(['unassigned', 'suggested', 'assigned', 'inactive']),
  "participant_has_team": zod.record(zod.string(), zod.unknown()).optional(),
  "suggested_team_id": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "suggested_team_name": zod.string(),
  "suggested_team_status": zod.enum(['forming', 'ready', 'incomplete', 'inactive']),
  "role_fit": zod.enum(['mid', 'gold', 'exp', 'support', 'jungle']),
  "preferred_role_1": zod.enum(['mid', 'gold', 'exp', 'support', 'jungle']),
  "preferred_role_2": zod.record(zod.string(), zod.unknown()).optional(),
  "preferred_role_3": zod.record(zod.string(), zod.unknown()).optional(),
  "role_data_quality": zod.record(zod.string(), zod.unknown()).optional(),
  "role_match_score": zod.record(zod.string(), zod.unknown()).optional(),
  "role_match_level": zod.record(zod.string(), zod.unknown()).optional(),
  "ranking_basis": zod.record(zod.string(), zod.unknown()).optional(),
  "game_performance_rating": zod.record(zod.string(), zod.unknown()).optional(),
  "kda": zod.record(zod.string(), zod.unknown()).optional(),
  "accumulated_gold": zod.record(zod.string(), zod.unknown()).optional(),
  "team_member_count": zod.record(zod.string(), zod.unknown()).optional(),
  "team_slots_left": zod.record(zod.string(), zod.unknown()).optional(),
  "suggestion_priority": zod.record(zod.string(), zod.unknown()).optional(),
  "sort_score": zod.record(zod.string(), zod.unknown()).optional(),
  "reason": zod.record(zod.string(), zod.unknown()).optional(),
  "status": zod.record(zod.string(), zod.unknown()).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})).optional()
})

/**
 * @summary Get Team_suggestions Collection by ID
 */
export const GetCollectionsTeamSuggestionsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const GetCollectionsTeamSuggestionsRecordsIdQueryParams = zod.object({
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsTeamSuggestionsRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "participant_id": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "participant_game_id": zod.string(),
  "participant_status": zod.enum(['unassigned', 'suggested', 'assigned', 'inactive']),
  "participant_has_team": zod.record(zod.string(), zod.unknown()).optional(),
  "suggested_team_id": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "suggested_team_name": zod.string(),
  "suggested_team_status": zod.enum(['forming', 'ready', 'incomplete', 'inactive']),
  "role_fit": zod.enum(['mid', 'gold', 'exp', 'support', 'jungle']),
  "preferred_role_1": zod.enum(['mid', 'gold', 'exp', 'support', 'jungle']),
  "preferred_role_2": zod.record(zod.string(), zod.unknown()).optional(),
  "preferred_role_3": zod.record(zod.string(), zod.unknown()).optional(),
  "role_data_quality": zod.record(zod.string(), zod.unknown()).optional(),
  "role_match_score": zod.record(zod.string(), zod.unknown()).optional(),
  "role_match_level": zod.record(zod.string(), zod.unknown()).optional(),
  "ranking_basis": zod.record(zod.string(), zod.unknown()).optional(),
  "game_performance_rating": zod.record(zod.string(), zod.unknown()).optional(),
  "kda": zod.record(zod.string(), zod.unknown()).optional(),
  "accumulated_gold": zod.record(zod.string(), zod.unknown()).optional(),
  "team_member_count": zod.record(zod.string(), zod.unknown()).optional(),
  "team_slots_left": zod.record(zod.string(), zod.unknown()).optional(),
  "suggestion_priority": zod.record(zod.string(), zod.unknown()).optional(),
  "sort_score": zod.record(zod.string(), zod.unknown()).optional(),
  "reason": zod.record(zod.string(), zod.unknown()).optional(),
  "status": zod.record(zod.string(), zod.unknown()).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

