/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIdRouteRouteImport } from './routes/app/$id/route'
import { Route as AppIdIndexRouteImport } from './routes/app/$id/index'
import { Route as AppAuthLoginRouteImport } from './routes/app/auth/login'
import { Route as AppAuthCheckRouteImport } from './routes/app/auth/check'
import { Route as AppIdAuditLogsRouteImport } from './routes/app/$id/audit-logs'
import { Route as AppIdAdminsRouteImport } from './routes/app/$id/admins'
import { Route as AppIdTournamentIndexRouteImport } from './routes/app/$id/tournament/index'
import { Route as AppIdTeamsIndexRouteImport } from './routes/app/$id/teams/index'
import { Route as AppIdParticipantsIndexRouteImport } from './routes/app/$id/participants/index'
import { Route as AppIdMatchesIndexRouteImport } from './routes/app/$id/matches/index'
import { Route as AppIdTournamentArchivedRouteImport } from './routes/app/$id/tournament/archived'
import { Route as AppIdTeamsArchivedRouteImport } from './routes/app/$id/teams/archived'
import { Route as AppIdParticipantsArchivedRouteImport } from './routes/app/$id/participants/archived'
import { Route as AppIdMatchesArchivedRouteImport } from './routes/app/$id/matches/archived'

const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIdRouteRoute = AppIdRouteRouteImport.update({
  id: '/app/$id',
  path: '/app/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIdIndexRoute = AppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppAuthLoginRoute = AppAuthLoginRouteImport.update({
  id: '/app/auth/login',
  path: '/app/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthCheckRoute = AppAuthCheckRouteImport.update({
  id: '/app/auth/check',
  path: '/app/auth/check',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIdAuditLogsRoute = AppIdAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppIdAdminsRoute = AppIdAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppIdTournamentIndexRoute = AppIdTournamentIndexRouteImport.update({
  id: '/tournament/',
  path: '/tournament/',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppIdTeamsIndexRoute = AppIdTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppIdParticipantsIndexRoute = AppIdParticipantsIndexRouteImport.update({
  id: '/participants/',
  path: '/participants/',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppIdMatchesIndexRoute = AppIdMatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppIdTournamentArchivedRoute = AppIdTournamentArchivedRouteImport.update({
  id: '/tournament/archived',
  path: '/tournament/archived',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppIdTeamsArchivedRoute = AppIdTeamsArchivedRouteImport.update({
  id: '/teams/archived',
  path: '/teams/archived',
  getParentRoute: () => AppIdRouteRoute,
} as any)
const AppIdParticipantsArchivedRoute =
  AppIdParticipantsArchivedRouteImport.update({
    id: '/participants/archived',
    path: '/participants/archived',
    getParentRoute: () => AppIdRouteRoute,
  } as any)
const AppIdMatchesArchivedRoute = AppIdMatchesArchivedRouteImport.update({
  id: '/matches/archived',
  path: '/matches/archived',
  getParentRoute: () => AppIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/app/$id': typeof AppIdRouteRouteWithChildren
  '/app/$id/admins': typeof AppIdAdminsRoute
  '/app/$id/audit-logs': typeof AppIdAuditLogsRoute
  '/app/auth/check': typeof AppAuthCheckRoute
  '/app/auth/login': typeof AppAuthLoginRoute
  '/app/$id/': typeof AppIdIndexRoute
  '/app/$id/matches/archived': typeof AppIdMatchesArchivedRoute
  '/app/$id/participants/archived': typeof AppIdParticipantsArchivedRoute
  '/app/$id/teams/archived': typeof AppIdTeamsArchivedRoute
  '/app/$id/tournament/archived': typeof AppIdTournamentArchivedRoute
  '/app/$id/matches/': typeof AppIdMatchesIndexRoute
  '/app/$id/participants/': typeof AppIdParticipantsIndexRoute
  '/app/$id/teams/': typeof AppIdTeamsIndexRoute
  '/app/$id/tournament/': typeof AppIdTournamentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/app/$id/admins': typeof AppIdAdminsRoute
  '/app/$id/audit-logs': typeof AppIdAuditLogsRoute
  '/app/auth/check': typeof AppAuthCheckRoute
  '/app/auth/login': typeof AppAuthLoginRoute
  '/app/$id': typeof AppIdIndexRoute
  '/app/$id/matches/archived': typeof AppIdMatchesArchivedRoute
  '/app/$id/participants/archived': typeof AppIdParticipantsArchivedRoute
  '/app/$id/teams/archived': typeof AppIdTeamsArchivedRoute
  '/app/$id/tournament/archived': typeof AppIdTournamentArchivedRoute
  '/app/$id/matches': typeof AppIdMatchesIndexRoute
  '/app/$id/participants': typeof AppIdParticipantsIndexRoute
  '/app/$id/teams': typeof AppIdTeamsIndexRoute
  '/app/$id/tournament': typeof AppIdTournamentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components': typeof ComponentsRoute
  '/app/$id': typeof AppIdRouteRouteWithChildren
  '/app/$id/admins': typeof AppIdAdminsRoute
  '/app/$id/audit-logs': typeof AppIdAuditLogsRoute
  '/app/auth/check': typeof AppAuthCheckRoute
  '/app/auth/login': typeof AppAuthLoginRoute
  '/app/$id/': typeof AppIdIndexRoute
  '/app/$id/matches/archived': typeof AppIdMatchesArchivedRoute
  '/app/$id/participants/archived': typeof AppIdParticipantsArchivedRoute
  '/app/$id/teams/archived': typeof AppIdTeamsArchivedRoute
  '/app/$id/tournament/archived': typeof AppIdTournamentArchivedRoute
  '/app/$id/matches/': typeof AppIdMatchesIndexRoute
  '/app/$id/participants/': typeof AppIdParticipantsIndexRoute
  '/app/$id/teams/': typeof AppIdTeamsIndexRoute
  '/app/$id/tournament/': typeof AppIdTournamentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/app/$id'
    | '/app/$id/admins'
    | '/app/$id/audit-logs'
    | '/app/auth/check'
    | '/app/auth/login'
    | '/app/$id/'
    | '/app/$id/matches/archived'
    | '/app/$id/participants/archived'
    | '/app/$id/teams/archived'
    | '/app/$id/tournament/archived'
    | '/app/$id/matches/'
    | '/app/$id/participants/'
    | '/app/$id/teams/'
    | '/app/$id/tournament/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/app/$id/admins'
    | '/app/$id/audit-logs'
    | '/app/auth/check'
    | '/app/auth/login'
    | '/app/$id'
    | '/app/$id/matches/archived'
    | '/app/$id/participants/archived'
    | '/app/$id/teams/archived'
    | '/app/$id/tournament/archived'
    | '/app/$id/matches'
    | '/app/$id/participants'
    | '/app/$id/teams'
    | '/app/$id/tournament'
  id:
    | '__root__'
    | '/'
    | '/components'
    | '/app/$id'
    | '/app/$id/admins'
    | '/app/$id/audit-logs'
    | '/app/auth/check'
    | '/app/auth/login'
    | '/app/$id/'
    | '/app/$id/matches/archived'
    | '/app/$id/participants/archived'
    | '/app/$id/teams/archived'
    | '/app/$id/tournament/archived'
    | '/app/$id/matches/'
    | '/app/$id/participants/'
    | '/app/$id/teams/'
    | '/app/$id/tournament/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsRoute: typeof ComponentsRoute
  AppIdRouteRoute: typeof AppIdRouteRouteWithChildren
  AppAuthCheckRoute: typeof AppAuthCheckRoute
  AppAuthLoginRoute: typeof AppAuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$id': {
      id: '/app/$id'
      path: '/app/$id'
      fullPath: '/app/$id'
      preLoaderRoute: typeof AppIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$id/': {
      id: '/app/$id/'
      path: '/'
      fullPath: '/app/$id/'
      preLoaderRoute: typeof AppIdIndexRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/app/auth/login': {
      id: '/app/auth/login'
      path: '/app/auth/login'
      fullPath: '/app/auth/login'
      preLoaderRoute: typeof AppAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/auth/check': {
      id: '/app/auth/check'
      path: '/app/auth/check'
      fullPath: '/app/auth/check'
      preLoaderRoute: typeof AppAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$id/audit-logs': {
      id: '/app/$id/audit-logs'
      path: '/audit-logs'
      fullPath: '/app/$id/audit-logs'
      preLoaderRoute: typeof AppIdAuditLogsRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/app/$id/admins': {
      id: '/app/$id/admins'
      path: '/admins'
      fullPath: '/app/$id/admins'
      preLoaderRoute: typeof AppIdAdminsRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/app/$id/tournament/': {
      id: '/app/$id/tournament/'
      path: '/tournament'
      fullPath: '/app/$id/tournament/'
      preLoaderRoute: typeof AppIdTournamentIndexRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/app/$id/teams/': {
      id: '/app/$id/teams/'
      path: '/teams'
      fullPath: '/app/$id/teams/'
      preLoaderRoute: typeof AppIdTeamsIndexRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/app/$id/participants/': {
      id: '/app/$id/participants/'
      path: '/participants'
      fullPath: '/app/$id/participants/'
      preLoaderRoute: typeof AppIdParticipantsIndexRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/app/$id/matches/': {
      id: '/app/$id/matches/'
      path: '/matches'
      fullPath: '/app/$id/matches/'
      preLoaderRoute: typeof AppIdMatchesIndexRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/app/$id/tournament/archived': {
      id: '/app/$id/tournament/archived'
      path: '/tournament/archived'
      fullPath: '/app/$id/tournament/archived'
      preLoaderRoute: typeof AppIdTournamentArchivedRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/app/$id/teams/archived': {
      id: '/app/$id/teams/archived'
      path: '/teams/archived'
      fullPath: '/app/$id/teams/archived'
      preLoaderRoute: typeof AppIdTeamsArchivedRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/app/$id/participants/archived': {
      id: '/app/$id/participants/archived'
      path: '/participants/archived'
      fullPath: '/app/$id/participants/archived'
      preLoaderRoute: typeof AppIdParticipantsArchivedRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
    '/app/$id/matches/archived': {
      id: '/app/$id/matches/archived'
      path: '/matches/archived'
      fullPath: '/app/$id/matches/archived'
      preLoaderRoute: typeof AppIdMatchesArchivedRouteImport
      parentRoute: typeof AppIdRouteRoute
    }
  }
}

interface AppIdRouteRouteChildren {
  AppIdAdminsRoute: typeof AppIdAdminsRoute
  AppIdAuditLogsRoute: typeof AppIdAuditLogsRoute
  AppIdIndexRoute: typeof AppIdIndexRoute
  AppIdMatchesArchivedRoute: typeof AppIdMatchesArchivedRoute
  AppIdParticipantsArchivedRoute: typeof AppIdParticipantsArchivedRoute
  AppIdTeamsArchivedRoute: typeof AppIdTeamsArchivedRoute
  AppIdTournamentArchivedRoute: typeof AppIdTournamentArchivedRoute
  AppIdMatchesIndexRoute: typeof AppIdMatchesIndexRoute
  AppIdParticipantsIndexRoute: typeof AppIdParticipantsIndexRoute
  AppIdTeamsIndexRoute: typeof AppIdTeamsIndexRoute
  AppIdTournamentIndexRoute: typeof AppIdTournamentIndexRoute
}

const AppIdRouteRouteChildren: AppIdRouteRouteChildren = {
  AppIdAdminsRoute: AppIdAdminsRoute,
  AppIdAuditLogsRoute: AppIdAuditLogsRoute,
  AppIdIndexRoute: AppIdIndexRoute,
  AppIdMatchesArchivedRoute: AppIdMatchesArchivedRoute,
  AppIdParticipantsArchivedRoute: AppIdParticipantsArchivedRoute,
  AppIdTeamsArchivedRoute: AppIdTeamsArchivedRoute,
  AppIdTournamentArchivedRoute: AppIdTournamentArchivedRoute,
  AppIdMatchesIndexRoute: AppIdMatchesIndexRoute,
  AppIdParticipantsIndexRoute: AppIdParticipantsIndexRoute,
  AppIdTeamsIndexRoute: AppIdTeamsIndexRoute,
  AppIdTournamentIndexRoute: AppIdTournamentIndexRoute,
}

const AppIdRouteRouteWithChildren = AppIdRouteRoute._addFileChildren(
  AppIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRoute,
  AppIdRouteRoute: AppIdRouteRouteWithChildren,
  AppAuthCheckRoute: AppAuthCheckRoute,
  AppAuthLoginRoute: AppAuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
