/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegacyIndexRouteImport } from './routes/legacy/index'
import { Route as LegacyComponentsRouteImport } from './routes/legacy/components'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as LegacyPRouteRouteImport } from './routes/legacy/p/route'
import { Route as AppAuthRouteRouteImport } from './routes/app/auth/route'
import { Route as AppAuthedRouteRouteImport } from './routes/app/_authed/route'
import { Route as LegacyPIndexRouteImport } from './routes/legacy/p/index'
import { Route as AppAuthedIndexRouteImport } from './routes/app/_authed/index'
import { Route as LegacyPTeamsRouteImport } from './routes/legacy/p/teams'
import { Route as LegacyPStandingRouteImport } from './routes/legacy/p/standing'
import { Route as LegacyPParticipantsRouteImport } from './routes/legacy/p/participants'
import { Route as LegacyPNotAvailableRouteImport } from './routes/legacy/p/not-available'
import { Route as AppAuthLoginRouteImport } from './routes/app/auth/login'
import { Route as AppAuthedAuditLogsRouteImport } from './routes/app/_authed/audit-logs'
import { Route as AppAuthedAdminsRouteImport } from './routes/app/_authed/admins'
import { Route as LegacyAppIdRouteRouteImport } from './routes/legacy/app/$id/route'
import { Route as LegacyPTournamentsIndexRouteImport } from './routes/legacy/p/tournaments/index'
import { Route as LegacyAppIdIndexRouteImport } from './routes/legacy/app/$id/index'
import { Route as AppAuthedTournamentsIndexRouteImport } from './routes/app/_authed/tournaments/index'
import { Route as LegacyPTournamentsIdRouteImport } from './routes/legacy/p/tournaments/$id'
import { Route as LegacyAppAuthLoginRouteImport } from './routes/legacy/app/auth/login'
import { Route as LegacyAppAuthCheckRouteImport } from './routes/legacy/app/auth/check'
import { Route as LegacyAppIdTeamStandingRouteImport } from './routes/legacy/app/$id/team-standing'
import { Route as LegacyAppIdAuditLogsRouteImport } from './routes/legacy/app/$id/audit-logs'
import { Route as LegacyAppIdAdminsRouteImport } from './routes/legacy/app/$id/admins'
import { Route as AppAuthedTournamentsTournamentIdRouteRouteImport } from './routes/app/_authed/tournaments/$tournamentId/route'
import { Route as LegacyAppIdTournamentIndexRouteImport } from './routes/legacy/app/$id/tournament/index'
import { Route as LegacyAppIdTeamsIndexRouteImport } from './routes/legacy/app/$id/teams/index'
import { Route as LegacyAppIdParticipantsIndexRouteImport } from './routes/legacy/app/$id/participants/index'
import { Route as LegacyAppIdMatchesIndexRouteImport } from './routes/legacy/app/$id/matches/index'
import { Route as AppAuthedTournamentsTournamentIdIndexRouteImport } from './routes/app/_authed/tournaments/$tournamentId/index'
import { Route as LegacyAppIdTournamentArchivedRouteImport } from './routes/legacy/app/$id/tournament/archived'
import { Route as LegacyAppIdTeamsArchivedRouteImport } from './routes/legacy/app/$id/teams/archived'
import { Route as LegacyAppIdParticipantsArchivedRouteImport } from './routes/legacy/app/$id/participants/archived'
import { Route as LegacyAppIdMatchesArchivedRouteImport } from './routes/legacy/app/$id/matches/archived'
import { Route as AppAuthedTournamentsTournamentIdTeamsRouteImport } from './routes/app/_authed/tournaments/$tournamentId/teams'
import { Route as AppAuthedTournamentsTournamentIdTeamStandingRouteImport } from './routes/app/_authed/tournaments/$tournamentId/team-standing'
import { Route as AppAuthedTournamentsTournamentIdParticipantsRouteImport } from './routes/app/_authed/tournaments/$tournamentId/participants'
import { Route as AppAuthedTournamentsTournamentIdMatchesRouteImport } from './routes/app/_authed/tournaments/$tournamentId/matches'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyIndexRoute = LegacyIndexRouteImport.update({
  id: '/legacy/',
  path: '/legacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyComponentsRoute = LegacyComponentsRouteImport.update({
  id: '/legacy/components',
  path: '/legacy/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/app/login',
  path: '/app/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyPRouteRoute = LegacyPRouteRouteImport.update({
  id: '/legacy/p',
  path: '/legacy/p',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthRouteRoute = AppAuthRouteRouteImport.update({
  id: '/app/auth',
  path: '/app/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedRouteRoute = AppAuthedRouteRouteImport.update({
  id: '/app/_authed',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyPIndexRoute = LegacyPIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegacyPRouteRoute,
} as any)
const AppAuthedIndexRoute = AppAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const LegacyPTeamsRoute = LegacyPTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => LegacyPRouteRoute,
} as any)
const LegacyPStandingRoute = LegacyPStandingRouteImport.update({
  id: '/standing',
  path: '/standing',
  getParentRoute: () => LegacyPRouteRoute,
} as any)
const LegacyPParticipantsRoute = LegacyPParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => LegacyPRouteRoute,
} as any)
const LegacyPNotAvailableRoute = LegacyPNotAvailableRouteImport.update({
  id: '/not-available',
  path: '/not-available',
  getParentRoute: () => LegacyPRouteRoute,
} as any)
const AppAuthLoginRoute = AppAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthedAuditLogsRoute = AppAuthedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const AppAuthedAdminsRoute = AppAuthedAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AppAuthedRouteRoute,
} as any)
const LegacyAppIdRouteRoute = LegacyAppIdRouteRouteImport.update({
  id: '/legacy/app/$id',
  path: '/legacy/app/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyPTournamentsIndexRoute = LegacyPTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => LegacyPRouteRoute,
} as any)
const LegacyAppIdIndexRoute = LegacyAppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegacyAppIdRouteRoute,
} as any)
const AppAuthedTournamentsIndexRoute =
  AppAuthedTournamentsIndexRouteImport.update({
    id: '/tournaments/',
    path: '/tournaments/',
    getParentRoute: () => AppAuthedRouteRoute,
  } as any)
const LegacyPTournamentsIdRoute = LegacyPTournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => LegacyPRouteRoute,
} as any)
const LegacyAppAuthLoginRoute = LegacyAppAuthLoginRouteImport.update({
  id: '/legacy/app/auth/login',
  path: '/legacy/app/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyAppAuthCheckRoute = LegacyAppAuthCheckRouteImport.update({
  id: '/legacy/app/auth/check',
  path: '/legacy/app/auth/check',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyAppIdTeamStandingRoute = LegacyAppIdTeamStandingRouteImport.update({
  id: '/team-standing',
  path: '/team-standing',
  getParentRoute: () => LegacyAppIdRouteRoute,
} as any)
const LegacyAppIdAuditLogsRoute = LegacyAppIdAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => LegacyAppIdRouteRoute,
} as any)
const LegacyAppIdAdminsRoute = LegacyAppIdAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => LegacyAppIdRouteRoute,
} as any)
const AppAuthedTournamentsTournamentIdRouteRoute =
  AppAuthedTournamentsTournamentIdRouteRouteImport.update({
    id: '/tournaments/$tournamentId',
    path: '/tournaments/$tournamentId',
    getParentRoute: () => AppAuthedRouteRoute,
  } as any)
const LegacyAppIdTournamentIndexRoute =
  LegacyAppIdTournamentIndexRouteImport.update({
    id: '/tournament/',
    path: '/tournament/',
    getParentRoute: () => LegacyAppIdRouteRoute,
  } as any)
const LegacyAppIdTeamsIndexRoute = LegacyAppIdTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => LegacyAppIdRouteRoute,
} as any)
const LegacyAppIdParticipantsIndexRoute =
  LegacyAppIdParticipantsIndexRouteImport.update({
    id: '/participants/',
    path: '/participants/',
    getParentRoute: () => LegacyAppIdRouteRoute,
  } as any)
const LegacyAppIdMatchesIndexRoute = LegacyAppIdMatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => LegacyAppIdRouteRoute,
} as any)
const AppAuthedTournamentsTournamentIdIndexRoute =
  AppAuthedTournamentsTournamentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppAuthedTournamentsTournamentIdRouteRoute,
  } as any)
const LegacyAppIdTournamentArchivedRoute =
  LegacyAppIdTournamentArchivedRouteImport.update({
    id: '/tournament/archived',
    path: '/tournament/archived',
    getParentRoute: () => LegacyAppIdRouteRoute,
  } as any)
const LegacyAppIdTeamsArchivedRoute =
  LegacyAppIdTeamsArchivedRouteImport.update({
    id: '/teams/archived',
    path: '/teams/archived',
    getParentRoute: () => LegacyAppIdRouteRoute,
  } as any)
const LegacyAppIdParticipantsArchivedRoute =
  LegacyAppIdParticipantsArchivedRouteImport.update({
    id: '/participants/archived',
    path: '/participants/archived',
    getParentRoute: () => LegacyAppIdRouteRoute,
  } as any)
const LegacyAppIdMatchesArchivedRoute =
  LegacyAppIdMatchesArchivedRouteImport.update({
    id: '/matches/archived',
    path: '/matches/archived',
    getParentRoute: () => LegacyAppIdRouteRoute,
  } as any)
const AppAuthedTournamentsTournamentIdTeamsRoute =
  AppAuthedTournamentsTournamentIdTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => AppAuthedTournamentsTournamentIdRouteRoute,
  } as any)
const AppAuthedTournamentsTournamentIdTeamStandingRoute =
  AppAuthedTournamentsTournamentIdTeamStandingRouteImport.update({
    id: '/team-standing',
    path: '/team-standing',
    getParentRoute: () => AppAuthedTournamentsTournamentIdRouteRoute,
  } as any)
const AppAuthedTournamentsTournamentIdParticipantsRoute =
  AppAuthedTournamentsTournamentIdParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => AppAuthedTournamentsTournamentIdRouteRoute,
  } as any)
const AppAuthedTournamentsTournamentIdMatchesRoute =
  AppAuthedTournamentsTournamentIdMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AppAuthedTournamentsTournamentIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/app': typeof AppAuthedRouteRouteWithChildren
  '/app/auth': typeof AppAuthRouteRouteWithChildren
  '/legacy/p': typeof LegacyPRouteRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/legacy/components': typeof LegacyComponentsRoute
  '/legacy/': typeof LegacyIndexRoute
  '/legacy/app/$id': typeof LegacyAppIdRouteRouteWithChildren
  '/app/admins': typeof AppAuthedAdminsRoute
  '/app/audit-logs': typeof AppAuthedAuditLogsRoute
  '/app/auth/login': typeof AppAuthLoginRoute
  '/legacy/p/not-available': typeof LegacyPNotAvailableRoute
  '/legacy/p/participants': typeof LegacyPParticipantsRoute
  '/legacy/p/standing': typeof LegacyPStandingRoute
  '/legacy/p/teams': typeof LegacyPTeamsRoute
  '/app/': typeof AppAuthedIndexRoute
  '/legacy/p/': typeof LegacyPIndexRoute
  '/app/tournaments/$tournamentId': typeof AppAuthedTournamentsTournamentIdRouteRouteWithChildren
  '/legacy/app/$id/admins': typeof LegacyAppIdAdminsRoute
  '/legacy/app/$id/audit-logs': typeof LegacyAppIdAuditLogsRoute
  '/legacy/app/$id/team-standing': typeof LegacyAppIdTeamStandingRoute
  '/legacy/app/auth/check': typeof LegacyAppAuthCheckRoute
  '/legacy/app/auth/login': typeof LegacyAppAuthLoginRoute
  '/legacy/p/tournaments/$id': typeof LegacyPTournamentsIdRoute
  '/app/tournaments/': typeof AppAuthedTournamentsIndexRoute
  '/legacy/app/$id/': typeof LegacyAppIdIndexRoute
  '/legacy/p/tournaments/': typeof LegacyPTournamentsIndexRoute
  '/app/tournaments/$tournamentId/matches': typeof AppAuthedTournamentsTournamentIdMatchesRoute
  '/app/tournaments/$tournamentId/participants': typeof AppAuthedTournamentsTournamentIdParticipantsRoute
  '/app/tournaments/$tournamentId/team-standing': typeof AppAuthedTournamentsTournamentIdTeamStandingRoute
  '/app/tournaments/$tournamentId/teams': typeof AppAuthedTournamentsTournamentIdTeamsRoute
  '/legacy/app/$id/matches/archived': typeof LegacyAppIdMatchesArchivedRoute
  '/legacy/app/$id/participants/archived': typeof LegacyAppIdParticipantsArchivedRoute
  '/legacy/app/$id/teams/archived': typeof LegacyAppIdTeamsArchivedRoute
  '/legacy/app/$id/tournament/archived': typeof LegacyAppIdTournamentArchivedRoute
  '/app/tournaments/$tournamentId/': typeof AppAuthedTournamentsTournamentIdIndexRoute
  '/legacy/app/$id/matches/': typeof LegacyAppIdMatchesIndexRoute
  '/legacy/app/$id/participants/': typeof LegacyAppIdParticipantsIndexRoute
  '/legacy/app/$id/teams/': typeof LegacyAppIdTeamsIndexRoute
  '/legacy/app/$id/tournament/': typeof LegacyAppIdTournamentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/app/auth': typeof AppAuthRouteRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/legacy/components': typeof LegacyComponentsRoute
  '/legacy': typeof LegacyIndexRoute
  '/app/admins': typeof AppAuthedAdminsRoute
  '/app/audit-logs': typeof AppAuthedAuditLogsRoute
  '/app/auth/login': typeof AppAuthLoginRoute
  '/legacy/p/not-available': typeof LegacyPNotAvailableRoute
  '/legacy/p/participants': typeof LegacyPParticipantsRoute
  '/legacy/p/standing': typeof LegacyPStandingRoute
  '/legacy/p/teams': typeof LegacyPTeamsRoute
  '/app': typeof AppAuthedIndexRoute
  '/legacy/p': typeof LegacyPIndexRoute
  '/legacy/app/$id/admins': typeof LegacyAppIdAdminsRoute
  '/legacy/app/$id/audit-logs': typeof LegacyAppIdAuditLogsRoute
  '/legacy/app/$id/team-standing': typeof LegacyAppIdTeamStandingRoute
  '/legacy/app/auth/check': typeof LegacyAppAuthCheckRoute
  '/legacy/app/auth/login': typeof LegacyAppAuthLoginRoute
  '/legacy/p/tournaments/$id': typeof LegacyPTournamentsIdRoute
  '/app/tournaments': typeof AppAuthedTournamentsIndexRoute
  '/legacy/app/$id': typeof LegacyAppIdIndexRoute
  '/legacy/p/tournaments': typeof LegacyPTournamentsIndexRoute
  '/app/tournaments/$tournamentId/matches': typeof AppAuthedTournamentsTournamentIdMatchesRoute
  '/app/tournaments/$tournamentId/participants': typeof AppAuthedTournamentsTournamentIdParticipantsRoute
  '/app/tournaments/$tournamentId/team-standing': typeof AppAuthedTournamentsTournamentIdTeamStandingRoute
  '/app/tournaments/$tournamentId/teams': typeof AppAuthedTournamentsTournamentIdTeamsRoute
  '/legacy/app/$id/matches/archived': typeof LegacyAppIdMatchesArchivedRoute
  '/legacy/app/$id/participants/archived': typeof LegacyAppIdParticipantsArchivedRoute
  '/legacy/app/$id/teams/archived': typeof LegacyAppIdTeamsArchivedRoute
  '/legacy/app/$id/tournament/archived': typeof LegacyAppIdTournamentArchivedRoute
  '/app/tournaments/$tournamentId': typeof AppAuthedTournamentsTournamentIdIndexRoute
  '/legacy/app/$id/matches': typeof LegacyAppIdMatchesIndexRoute
  '/legacy/app/$id/participants': typeof LegacyAppIdParticipantsIndexRoute
  '/legacy/app/$id/teams': typeof LegacyAppIdTeamsIndexRoute
  '/legacy/app/$id/tournament': typeof LegacyAppIdTournamentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/app/_authed': typeof AppAuthedRouteRouteWithChildren
  '/app/auth': typeof AppAuthRouteRouteWithChildren
  '/legacy/p': typeof LegacyPRouteRouteWithChildren
  '/app/login': typeof AppLoginRoute
  '/legacy/components': typeof LegacyComponentsRoute
  '/legacy/': typeof LegacyIndexRoute
  '/legacy/app/$id': typeof LegacyAppIdRouteRouteWithChildren
  '/app/_authed/admins': typeof AppAuthedAdminsRoute
  '/app/_authed/audit-logs': typeof AppAuthedAuditLogsRoute
  '/app/auth/login': typeof AppAuthLoginRoute
  '/legacy/p/not-available': typeof LegacyPNotAvailableRoute
  '/legacy/p/participants': typeof LegacyPParticipantsRoute
  '/legacy/p/standing': typeof LegacyPStandingRoute
  '/legacy/p/teams': typeof LegacyPTeamsRoute
  '/app/_authed/': typeof AppAuthedIndexRoute
  '/legacy/p/': typeof LegacyPIndexRoute
  '/app/_authed/tournaments/$tournamentId': typeof AppAuthedTournamentsTournamentIdRouteRouteWithChildren
  '/legacy/app/$id/admins': typeof LegacyAppIdAdminsRoute
  '/legacy/app/$id/audit-logs': typeof LegacyAppIdAuditLogsRoute
  '/legacy/app/$id/team-standing': typeof LegacyAppIdTeamStandingRoute
  '/legacy/app/auth/check': typeof LegacyAppAuthCheckRoute
  '/legacy/app/auth/login': typeof LegacyAppAuthLoginRoute
  '/legacy/p/tournaments/$id': typeof LegacyPTournamentsIdRoute
  '/app/_authed/tournaments/': typeof AppAuthedTournamentsIndexRoute
  '/legacy/app/$id/': typeof LegacyAppIdIndexRoute
  '/legacy/p/tournaments/': typeof LegacyPTournamentsIndexRoute
  '/app/_authed/tournaments/$tournamentId/matches': typeof AppAuthedTournamentsTournamentIdMatchesRoute
  '/app/_authed/tournaments/$tournamentId/participants': typeof AppAuthedTournamentsTournamentIdParticipantsRoute
  '/app/_authed/tournaments/$tournamentId/team-standing': typeof AppAuthedTournamentsTournamentIdTeamStandingRoute
  '/app/_authed/tournaments/$tournamentId/teams': typeof AppAuthedTournamentsTournamentIdTeamsRoute
  '/legacy/app/$id/matches/archived': typeof LegacyAppIdMatchesArchivedRoute
  '/legacy/app/$id/participants/archived': typeof LegacyAppIdParticipantsArchivedRoute
  '/legacy/app/$id/teams/archived': typeof LegacyAppIdTeamsArchivedRoute
  '/legacy/app/$id/tournament/archived': typeof LegacyAppIdTournamentArchivedRoute
  '/app/_authed/tournaments/$tournamentId/': typeof AppAuthedTournamentsTournamentIdIndexRoute
  '/legacy/app/$id/matches/': typeof LegacyAppIdMatchesIndexRoute
  '/legacy/app/$id/participants/': typeof LegacyAppIdParticipantsIndexRoute
  '/legacy/app/$id/teams/': typeof LegacyAppIdTeamsIndexRoute
  '/legacy/app/$id/tournament/': typeof LegacyAppIdTournamentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/app'
    | '/app/auth'
    | '/legacy/p'
    | '/app/login'
    | '/legacy/components'
    | '/legacy/'
    | '/legacy/app/$id'
    | '/app/admins'
    | '/app/audit-logs'
    | '/app/auth/login'
    | '/legacy/p/not-available'
    | '/legacy/p/participants'
    | '/legacy/p/standing'
    | '/legacy/p/teams'
    | '/app/'
    | '/legacy/p/'
    | '/app/tournaments/$tournamentId'
    | '/legacy/app/$id/admins'
    | '/legacy/app/$id/audit-logs'
    | '/legacy/app/$id/team-standing'
    | '/legacy/app/auth/check'
    | '/legacy/app/auth/login'
    | '/legacy/p/tournaments/$id'
    | '/app/tournaments/'
    | '/legacy/app/$id/'
    | '/legacy/p/tournaments/'
    | '/app/tournaments/$tournamentId/matches'
    | '/app/tournaments/$tournamentId/participants'
    | '/app/tournaments/$tournamentId/team-standing'
    | '/app/tournaments/$tournamentId/teams'
    | '/legacy/app/$id/matches/archived'
    | '/legacy/app/$id/participants/archived'
    | '/legacy/app/$id/teams/archived'
    | '/legacy/app/$id/tournament/archived'
    | '/app/tournaments/$tournamentId/'
    | '/legacy/app/$id/matches/'
    | '/legacy/app/$id/participants/'
    | '/legacy/app/$id/teams/'
    | '/legacy/app/$id/tournament/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/app/auth'
    | '/app/login'
    | '/legacy/components'
    | '/legacy'
    | '/app/admins'
    | '/app/audit-logs'
    | '/app/auth/login'
    | '/legacy/p/not-available'
    | '/legacy/p/participants'
    | '/legacy/p/standing'
    | '/legacy/p/teams'
    | '/app'
    | '/legacy/p'
    | '/legacy/app/$id/admins'
    | '/legacy/app/$id/audit-logs'
    | '/legacy/app/$id/team-standing'
    | '/legacy/app/auth/check'
    | '/legacy/app/auth/login'
    | '/legacy/p/tournaments/$id'
    | '/app/tournaments'
    | '/legacy/app/$id'
    | '/legacy/p/tournaments'
    | '/app/tournaments/$tournamentId/matches'
    | '/app/tournaments/$tournamentId/participants'
    | '/app/tournaments/$tournamentId/team-standing'
    | '/app/tournaments/$tournamentId/teams'
    | '/legacy/app/$id/matches/archived'
    | '/legacy/app/$id/participants/archived'
    | '/legacy/app/$id/teams/archived'
    | '/legacy/app/$id/tournament/archived'
    | '/app/tournaments/$tournamentId'
    | '/legacy/app/$id/matches'
    | '/legacy/app/$id/participants'
    | '/legacy/app/$id/teams'
    | '/legacy/app/$id/tournament'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/app/_authed'
    | '/app/auth'
    | '/legacy/p'
    | '/app/login'
    | '/legacy/components'
    | '/legacy/'
    | '/legacy/app/$id'
    | '/app/_authed/admins'
    | '/app/_authed/audit-logs'
    | '/app/auth/login'
    | '/legacy/p/not-available'
    | '/legacy/p/participants'
    | '/legacy/p/standing'
    | '/legacy/p/teams'
    | '/app/_authed/'
    | '/legacy/p/'
    | '/app/_authed/tournaments/$tournamentId'
    | '/legacy/app/$id/admins'
    | '/legacy/app/$id/audit-logs'
    | '/legacy/app/$id/team-standing'
    | '/legacy/app/auth/check'
    | '/legacy/app/auth/login'
    | '/legacy/p/tournaments/$id'
    | '/app/_authed/tournaments/'
    | '/legacy/app/$id/'
    | '/legacy/p/tournaments/'
    | '/app/_authed/tournaments/$tournamentId/matches'
    | '/app/_authed/tournaments/$tournamentId/participants'
    | '/app/_authed/tournaments/$tournamentId/team-standing'
    | '/app/_authed/tournaments/$tournamentId/teams'
    | '/legacy/app/$id/matches/archived'
    | '/legacy/app/$id/participants/archived'
    | '/legacy/app/$id/teams/archived'
    | '/legacy/app/$id/tournament/archived'
    | '/app/_authed/tournaments/$tournamentId/'
    | '/legacy/app/$id/matches/'
    | '/legacy/app/$id/participants/'
    | '/legacy/app/$id/teams/'
    | '/legacy/app/$id/tournament/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  AppAuthedRouteRoute: typeof AppAuthedRouteRouteWithChildren
  AppAuthRouteRoute: typeof AppAuthRouteRouteWithChildren
  LegacyPRouteRoute: typeof LegacyPRouteRouteWithChildren
  AppLoginRoute: typeof AppLoginRoute
  LegacyComponentsRoute: typeof LegacyComponentsRoute
  LegacyIndexRoute: typeof LegacyIndexRoute
  LegacyAppIdRouteRoute: typeof LegacyAppIdRouteRouteWithChildren
  LegacyAppAuthCheckRoute: typeof LegacyAppAuthCheckRoute
  LegacyAppAuthLoginRoute: typeof LegacyAppAuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/': {
      id: '/legacy/'
      path: '/legacy'
      fullPath: '/legacy/'
      preLoaderRoute: typeof LegacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/components': {
      id: '/legacy/components'
      path: '/legacy/components'
      fullPath: '/legacy/components'
      preLoaderRoute: typeof LegacyComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/login': {
      id: '/app/login'
      path: '/app/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/p': {
      id: '/legacy/p'
      path: '/legacy/p'
      fullPath: '/legacy/p'
      preLoaderRoute: typeof LegacyPRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/auth': {
      id: '/app/auth'
      path: '/app/auth'
      fullPath: '/app/auth'
      preLoaderRoute: typeof AppAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_authed': {
      id: '/app/_authed'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/p/': {
      id: '/legacy/p/'
      path: '/'
      fullPath: '/legacy/p/'
      preLoaderRoute: typeof LegacyPIndexRouteImport
      parentRoute: typeof LegacyPRouteRoute
    }
    '/app/_authed/': {
      id: '/app/_authed/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAuthedIndexRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/legacy/p/teams': {
      id: '/legacy/p/teams'
      path: '/teams'
      fullPath: '/legacy/p/teams'
      preLoaderRoute: typeof LegacyPTeamsRouteImport
      parentRoute: typeof LegacyPRouteRoute
    }
    '/legacy/p/standing': {
      id: '/legacy/p/standing'
      path: '/standing'
      fullPath: '/legacy/p/standing'
      preLoaderRoute: typeof LegacyPStandingRouteImport
      parentRoute: typeof LegacyPRouteRoute
    }
    '/legacy/p/participants': {
      id: '/legacy/p/participants'
      path: '/participants'
      fullPath: '/legacy/p/participants'
      preLoaderRoute: typeof LegacyPParticipantsRouteImport
      parentRoute: typeof LegacyPRouteRoute
    }
    '/legacy/p/not-available': {
      id: '/legacy/p/not-available'
      path: '/not-available'
      fullPath: '/legacy/p/not-available'
      preLoaderRoute: typeof LegacyPNotAvailableRouteImport
      parentRoute: typeof LegacyPRouteRoute
    }
    '/app/auth/login': {
      id: '/app/auth/login'
      path: '/login'
      fullPath: '/app/auth/login'
      preLoaderRoute: typeof AppAuthLoginRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/app/_authed/audit-logs': {
      id: '/app/_authed/audit-logs'
      path: '/audit-logs'
      fullPath: '/app/audit-logs'
      preLoaderRoute: typeof AppAuthedAuditLogsRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/app/_authed/admins': {
      id: '/app/_authed/admins'
      path: '/admins'
      fullPath: '/app/admins'
      preLoaderRoute: typeof AppAuthedAdminsRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/legacy/app/$id': {
      id: '/legacy/app/$id'
      path: '/legacy/app/$id'
      fullPath: '/legacy/app/$id'
      preLoaderRoute: typeof LegacyAppIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/p/tournaments/': {
      id: '/legacy/p/tournaments/'
      path: '/tournaments'
      fullPath: '/legacy/p/tournaments/'
      preLoaderRoute: typeof LegacyPTournamentsIndexRouteImport
      parentRoute: typeof LegacyPRouteRoute
    }
    '/legacy/app/$id/': {
      id: '/legacy/app/$id/'
      path: '/'
      fullPath: '/legacy/app/$id/'
      preLoaderRoute: typeof LegacyAppIdIndexRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/app/_authed/tournaments/': {
      id: '/app/_authed/tournaments/'
      path: '/tournaments'
      fullPath: '/app/tournaments/'
      preLoaderRoute: typeof AppAuthedTournamentsIndexRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/legacy/p/tournaments/$id': {
      id: '/legacy/p/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/legacy/p/tournaments/$id'
      preLoaderRoute: typeof LegacyPTournamentsIdRouteImport
      parentRoute: typeof LegacyPRouteRoute
    }
    '/legacy/app/auth/login': {
      id: '/legacy/app/auth/login'
      path: '/legacy/app/auth/login'
      fullPath: '/legacy/app/auth/login'
      preLoaderRoute: typeof LegacyAppAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/app/auth/check': {
      id: '/legacy/app/auth/check'
      path: '/legacy/app/auth/check'
      fullPath: '/legacy/app/auth/check'
      preLoaderRoute: typeof LegacyAppAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/app/$id/team-standing': {
      id: '/legacy/app/$id/team-standing'
      path: '/team-standing'
      fullPath: '/legacy/app/$id/team-standing'
      preLoaderRoute: typeof LegacyAppIdTeamStandingRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/audit-logs': {
      id: '/legacy/app/$id/audit-logs'
      path: '/audit-logs'
      fullPath: '/legacy/app/$id/audit-logs'
      preLoaderRoute: typeof LegacyAppIdAuditLogsRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/admins': {
      id: '/legacy/app/$id/admins'
      path: '/admins'
      fullPath: '/legacy/app/$id/admins'
      preLoaderRoute: typeof LegacyAppIdAdminsRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/app/_authed/tournaments/$tournamentId': {
      id: '/app/_authed/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/app/tournaments/$tournamentId'
      preLoaderRoute: typeof AppAuthedTournamentsTournamentIdRouteRouteImport
      parentRoute: typeof AppAuthedRouteRoute
    }
    '/legacy/app/$id/tournament/': {
      id: '/legacy/app/$id/tournament/'
      path: '/tournament'
      fullPath: '/legacy/app/$id/tournament/'
      preLoaderRoute: typeof LegacyAppIdTournamentIndexRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/teams/': {
      id: '/legacy/app/$id/teams/'
      path: '/teams'
      fullPath: '/legacy/app/$id/teams/'
      preLoaderRoute: typeof LegacyAppIdTeamsIndexRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/participants/': {
      id: '/legacy/app/$id/participants/'
      path: '/participants'
      fullPath: '/legacy/app/$id/participants/'
      preLoaderRoute: typeof LegacyAppIdParticipantsIndexRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/matches/': {
      id: '/legacy/app/$id/matches/'
      path: '/matches'
      fullPath: '/legacy/app/$id/matches/'
      preLoaderRoute: typeof LegacyAppIdMatchesIndexRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/app/_authed/tournaments/$tournamentId/': {
      id: '/app/_authed/tournaments/$tournamentId/'
      path: '/'
      fullPath: '/app/tournaments/$tournamentId/'
      preLoaderRoute: typeof AppAuthedTournamentsTournamentIdIndexRouteImport
      parentRoute: typeof AppAuthedTournamentsTournamentIdRouteRoute
    }
    '/legacy/app/$id/tournament/archived': {
      id: '/legacy/app/$id/tournament/archived'
      path: '/tournament/archived'
      fullPath: '/legacy/app/$id/tournament/archived'
      preLoaderRoute: typeof LegacyAppIdTournamentArchivedRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/teams/archived': {
      id: '/legacy/app/$id/teams/archived'
      path: '/teams/archived'
      fullPath: '/legacy/app/$id/teams/archived'
      preLoaderRoute: typeof LegacyAppIdTeamsArchivedRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/participants/archived': {
      id: '/legacy/app/$id/participants/archived'
      path: '/participants/archived'
      fullPath: '/legacy/app/$id/participants/archived'
      preLoaderRoute: typeof LegacyAppIdParticipantsArchivedRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/matches/archived': {
      id: '/legacy/app/$id/matches/archived'
      path: '/matches/archived'
      fullPath: '/legacy/app/$id/matches/archived'
      preLoaderRoute: typeof LegacyAppIdMatchesArchivedRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/app/_authed/tournaments/$tournamentId/teams': {
      id: '/app/_authed/tournaments/$tournamentId/teams'
      path: '/teams'
      fullPath: '/app/tournaments/$tournamentId/teams'
      preLoaderRoute: typeof AppAuthedTournamentsTournamentIdTeamsRouteImport
      parentRoute: typeof AppAuthedTournamentsTournamentIdRouteRoute
    }
    '/app/_authed/tournaments/$tournamentId/team-standing': {
      id: '/app/_authed/tournaments/$tournamentId/team-standing'
      path: '/team-standing'
      fullPath: '/app/tournaments/$tournamentId/team-standing'
      preLoaderRoute: typeof AppAuthedTournamentsTournamentIdTeamStandingRouteImport
      parentRoute: typeof AppAuthedTournamentsTournamentIdRouteRoute
    }
    '/app/_authed/tournaments/$tournamentId/participants': {
      id: '/app/_authed/tournaments/$tournamentId/participants'
      path: '/participants'
      fullPath: '/app/tournaments/$tournamentId/participants'
      preLoaderRoute: typeof AppAuthedTournamentsTournamentIdParticipantsRouteImport
      parentRoute: typeof AppAuthedTournamentsTournamentIdRouteRoute
    }
    '/app/_authed/tournaments/$tournamentId/matches': {
      id: '/app/_authed/tournaments/$tournamentId/matches'
      path: '/matches'
      fullPath: '/app/tournaments/$tournamentId/matches'
      preLoaderRoute: typeof AppAuthedTournamentsTournamentIdMatchesRouteImport
      parentRoute: typeof AppAuthedTournamentsTournamentIdRouteRoute
    }
  }
}

interface AppAuthedTournamentsTournamentIdRouteRouteChildren {
  AppAuthedTournamentsTournamentIdMatchesRoute: typeof AppAuthedTournamentsTournamentIdMatchesRoute
  AppAuthedTournamentsTournamentIdParticipantsRoute: typeof AppAuthedTournamentsTournamentIdParticipantsRoute
  AppAuthedTournamentsTournamentIdTeamStandingRoute: typeof AppAuthedTournamentsTournamentIdTeamStandingRoute
  AppAuthedTournamentsTournamentIdTeamsRoute: typeof AppAuthedTournamentsTournamentIdTeamsRoute
  AppAuthedTournamentsTournamentIdIndexRoute: typeof AppAuthedTournamentsTournamentIdIndexRoute
}

const AppAuthedTournamentsTournamentIdRouteRouteChildren: AppAuthedTournamentsTournamentIdRouteRouteChildren =
  {
    AppAuthedTournamentsTournamentIdMatchesRoute:
      AppAuthedTournamentsTournamentIdMatchesRoute,
    AppAuthedTournamentsTournamentIdParticipantsRoute:
      AppAuthedTournamentsTournamentIdParticipantsRoute,
    AppAuthedTournamentsTournamentIdTeamStandingRoute:
      AppAuthedTournamentsTournamentIdTeamStandingRoute,
    AppAuthedTournamentsTournamentIdTeamsRoute:
      AppAuthedTournamentsTournamentIdTeamsRoute,
    AppAuthedTournamentsTournamentIdIndexRoute:
      AppAuthedTournamentsTournamentIdIndexRoute,
  }

const AppAuthedTournamentsTournamentIdRouteRouteWithChildren =
  AppAuthedTournamentsTournamentIdRouteRoute._addFileChildren(
    AppAuthedTournamentsTournamentIdRouteRouteChildren,
  )

interface AppAuthedRouteRouteChildren {
  AppAuthedAdminsRoute: typeof AppAuthedAdminsRoute
  AppAuthedAuditLogsRoute: typeof AppAuthedAuditLogsRoute
  AppAuthedIndexRoute: typeof AppAuthedIndexRoute
  AppAuthedTournamentsTournamentIdRouteRoute: typeof AppAuthedTournamentsTournamentIdRouteRouteWithChildren
  AppAuthedTournamentsIndexRoute: typeof AppAuthedTournamentsIndexRoute
}

const AppAuthedRouteRouteChildren: AppAuthedRouteRouteChildren = {
  AppAuthedAdminsRoute: AppAuthedAdminsRoute,
  AppAuthedAuditLogsRoute: AppAuthedAuditLogsRoute,
  AppAuthedIndexRoute: AppAuthedIndexRoute,
  AppAuthedTournamentsTournamentIdRouteRoute:
    AppAuthedTournamentsTournamentIdRouteRouteWithChildren,
  AppAuthedTournamentsIndexRoute: AppAuthedTournamentsIndexRoute,
}

const AppAuthedRouteRouteWithChildren = AppAuthedRouteRoute._addFileChildren(
  AppAuthedRouteRouteChildren,
)

interface AppAuthRouteRouteChildren {
  AppAuthLoginRoute: typeof AppAuthLoginRoute
}

const AppAuthRouteRouteChildren: AppAuthRouteRouteChildren = {
  AppAuthLoginRoute: AppAuthLoginRoute,
}

const AppAuthRouteRouteWithChildren = AppAuthRouteRoute._addFileChildren(
  AppAuthRouteRouteChildren,
)

interface LegacyPRouteRouteChildren {
  LegacyPNotAvailableRoute: typeof LegacyPNotAvailableRoute
  LegacyPParticipantsRoute: typeof LegacyPParticipantsRoute
  LegacyPStandingRoute: typeof LegacyPStandingRoute
  LegacyPTeamsRoute: typeof LegacyPTeamsRoute
  LegacyPIndexRoute: typeof LegacyPIndexRoute
  LegacyPTournamentsIdRoute: typeof LegacyPTournamentsIdRoute
  LegacyPTournamentsIndexRoute: typeof LegacyPTournamentsIndexRoute
}

const LegacyPRouteRouteChildren: LegacyPRouteRouteChildren = {
  LegacyPNotAvailableRoute: LegacyPNotAvailableRoute,
  LegacyPParticipantsRoute: LegacyPParticipantsRoute,
  LegacyPStandingRoute: LegacyPStandingRoute,
  LegacyPTeamsRoute: LegacyPTeamsRoute,
  LegacyPIndexRoute: LegacyPIndexRoute,
  LegacyPTournamentsIdRoute: LegacyPTournamentsIdRoute,
  LegacyPTournamentsIndexRoute: LegacyPTournamentsIndexRoute,
}

const LegacyPRouteRouteWithChildren = LegacyPRouteRoute._addFileChildren(
  LegacyPRouteRouteChildren,
)

interface LegacyAppIdRouteRouteChildren {
  LegacyAppIdAdminsRoute: typeof LegacyAppIdAdminsRoute
  LegacyAppIdAuditLogsRoute: typeof LegacyAppIdAuditLogsRoute
  LegacyAppIdTeamStandingRoute: typeof LegacyAppIdTeamStandingRoute
  LegacyAppIdIndexRoute: typeof LegacyAppIdIndexRoute
  LegacyAppIdMatchesArchivedRoute: typeof LegacyAppIdMatchesArchivedRoute
  LegacyAppIdParticipantsArchivedRoute: typeof LegacyAppIdParticipantsArchivedRoute
  LegacyAppIdTeamsArchivedRoute: typeof LegacyAppIdTeamsArchivedRoute
  LegacyAppIdTournamentArchivedRoute: typeof LegacyAppIdTournamentArchivedRoute
  LegacyAppIdMatchesIndexRoute: typeof LegacyAppIdMatchesIndexRoute
  LegacyAppIdParticipantsIndexRoute: typeof LegacyAppIdParticipantsIndexRoute
  LegacyAppIdTeamsIndexRoute: typeof LegacyAppIdTeamsIndexRoute
  LegacyAppIdTournamentIndexRoute: typeof LegacyAppIdTournamentIndexRoute
}

const LegacyAppIdRouteRouteChildren: LegacyAppIdRouteRouteChildren = {
  LegacyAppIdAdminsRoute: LegacyAppIdAdminsRoute,
  LegacyAppIdAuditLogsRoute: LegacyAppIdAuditLogsRoute,
  LegacyAppIdTeamStandingRoute: LegacyAppIdTeamStandingRoute,
  LegacyAppIdIndexRoute: LegacyAppIdIndexRoute,
  LegacyAppIdMatchesArchivedRoute: LegacyAppIdMatchesArchivedRoute,
  LegacyAppIdParticipantsArchivedRoute: LegacyAppIdParticipantsArchivedRoute,
  LegacyAppIdTeamsArchivedRoute: LegacyAppIdTeamsArchivedRoute,
  LegacyAppIdTournamentArchivedRoute: LegacyAppIdTournamentArchivedRoute,
  LegacyAppIdMatchesIndexRoute: LegacyAppIdMatchesIndexRoute,
  LegacyAppIdParticipantsIndexRoute: LegacyAppIdParticipantsIndexRoute,
  LegacyAppIdTeamsIndexRoute: LegacyAppIdTeamsIndexRoute,
  LegacyAppIdTournamentIndexRoute: LegacyAppIdTournamentIndexRoute,
}

const LegacyAppIdRouteRouteWithChildren =
  LegacyAppIdRouteRoute._addFileChildren(LegacyAppIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  AppAuthedRouteRoute: AppAuthedRouteRouteWithChildren,
  AppAuthRouteRoute: AppAuthRouteRouteWithChildren,
  LegacyPRouteRoute: LegacyPRouteRouteWithChildren,
  AppLoginRoute: AppLoginRoute,
  LegacyComponentsRoute: LegacyComponentsRoute,
  LegacyIndexRoute: LegacyIndexRoute,
  LegacyAppIdRouteRoute: LegacyAppIdRouteRouteWithChildren,
  LegacyAppAuthCheckRoute: LegacyAppAuthCheckRoute,
  LegacyAppAuthLoginRoute: LegacyAppAuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
