/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegacyIndexRouteImport } from './routes/legacy/index'
import { Route as LegacyComponentsRouteImport } from './routes/legacy/components'
import { Route as LegacyPRouteRouteImport } from './routes/legacy/p/route'
import { Route as LegacyPIndexRouteImport } from './routes/legacy/p/index'
import { Route as LegacyPTeamsRouteImport } from './routes/legacy/p/teams'
import { Route as LegacyPStandingRouteImport } from './routes/legacy/p/standing'
import { Route as LegacyPParticipantsRouteImport } from './routes/legacy/p/participants'
import { Route as LegacyPNotAvailableRouteImport } from './routes/legacy/p/not-available'
import { Route as LegacyAppIdRouteRouteImport } from './routes/legacy/app/$id/route'
import { Route as LegacyPTournamentsIndexRouteImport } from './routes/legacy/p/tournaments/index'
import { Route as LegacyAppIdIndexRouteImport } from './routes/legacy/app/$id/index'
import { Route as LegacyPTournamentsIdRouteImport } from './routes/legacy/p/tournaments/$id'
import { Route as LegacyAppAuthLoginRouteImport } from './routes/legacy/app/auth/login'
import { Route as LegacyAppAuthCheckRouteImport } from './routes/legacy/app/auth/check'
import { Route as LegacyAppIdTeamStandingRouteImport } from './routes/legacy/app/$id/team-standing'
import { Route as LegacyAppIdAuditLogsRouteImport } from './routes/legacy/app/$id/audit-logs'
import { Route as LegacyAppIdAdminsRouteImport } from './routes/legacy/app/$id/admins'
import { Route as LegacyAppIdTournamentIndexRouteImport } from './routes/legacy/app/$id/tournament/index'
import { Route as LegacyAppIdTeamsIndexRouteImport } from './routes/legacy/app/$id/teams/index'
import { Route as LegacyAppIdParticipantsIndexRouteImport } from './routes/legacy/app/$id/participants/index'
import { Route as LegacyAppIdMatchesIndexRouteImport } from './routes/legacy/app/$id/matches/index'
import { Route as LegacyAppIdTournamentArchivedRouteImport } from './routes/legacy/app/$id/tournament/archived'
import { Route as LegacyAppIdTeamsArchivedRouteImport } from './routes/legacy/app/$id/teams/archived'
import { Route as LegacyAppIdParticipantsArchivedRouteImport } from './routes/legacy/app/$id/participants/archived'
import { Route as LegacyAppIdMatchesArchivedRouteImport } from './routes/legacy/app/$id/matches/archived'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyIndexRoute = LegacyIndexRouteImport.update({
  id: '/legacy/',
  path: '/legacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyComponentsRoute = LegacyComponentsRouteImport.update({
  id: '/legacy/components',
  path: '/legacy/components',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyPRouteRoute = LegacyPRouteRouteImport.update({
  id: '/legacy/p',
  path: '/legacy/p',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyPIndexRoute = LegacyPIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegacyPRouteRoute,
} as any)
const LegacyPTeamsRoute = LegacyPTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => LegacyPRouteRoute,
} as any)
const LegacyPStandingRoute = LegacyPStandingRouteImport.update({
  id: '/standing',
  path: '/standing',
  getParentRoute: () => LegacyPRouteRoute,
} as any)
const LegacyPParticipantsRoute = LegacyPParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => LegacyPRouteRoute,
} as any)
const LegacyPNotAvailableRoute = LegacyPNotAvailableRouteImport.update({
  id: '/not-available',
  path: '/not-available',
  getParentRoute: () => LegacyPRouteRoute,
} as any)
const LegacyAppIdRouteRoute = LegacyAppIdRouteRouteImport.update({
  id: '/legacy/app/$id',
  path: '/legacy/app/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyPTournamentsIndexRoute = LegacyPTournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => LegacyPRouteRoute,
} as any)
const LegacyAppIdIndexRoute = LegacyAppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegacyAppIdRouteRoute,
} as any)
const LegacyPTournamentsIdRoute = LegacyPTournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => LegacyPRouteRoute,
} as any)
const LegacyAppAuthLoginRoute = LegacyAppAuthLoginRouteImport.update({
  id: '/legacy/app/auth/login',
  path: '/legacy/app/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyAppAuthCheckRoute = LegacyAppAuthCheckRouteImport.update({
  id: '/legacy/app/auth/check',
  path: '/legacy/app/auth/check',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyAppIdTeamStandingRoute = LegacyAppIdTeamStandingRouteImport.update({
  id: '/team-standing',
  path: '/team-standing',
  getParentRoute: () => LegacyAppIdRouteRoute,
} as any)
const LegacyAppIdAuditLogsRoute = LegacyAppIdAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => LegacyAppIdRouteRoute,
} as any)
const LegacyAppIdAdminsRoute = LegacyAppIdAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => LegacyAppIdRouteRoute,
} as any)
const LegacyAppIdTournamentIndexRoute =
  LegacyAppIdTournamentIndexRouteImport.update({
    id: '/tournament/',
    path: '/tournament/',
    getParentRoute: () => LegacyAppIdRouteRoute,
  } as any)
const LegacyAppIdTeamsIndexRoute = LegacyAppIdTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => LegacyAppIdRouteRoute,
} as any)
const LegacyAppIdParticipantsIndexRoute =
  LegacyAppIdParticipantsIndexRouteImport.update({
    id: '/participants/',
    path: '/participants/',
    getParentRoute: () => LegacyAppIdRouteRoute,
  } as any)
const LegacyAppIdMatchesIndexRoute = LegacyAppIdMatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => LegacyAppIdRouteRoute,
} as any)
const LegacyAppIdTournamentArchivedRoute =
  LegacyAppIdTournamentArchivedRouteImport.update({
    id: '/tournament/archived',
    path: '/tournament/archived',
    getParentRoute: () => LegacyAppIdRouteRoute,
  } as any)
const LegacyAppIdTeamsArchivedRoute =
  LegacyAppIdTeamsArchivedRouteImport.update({
    id: '/teams/archived',
    path: '/teams/archived',
    getParentRoute: () => LegacyAppIdRouteRoute,
  } as any)
const LegacyAppIdParticipantsArchivedRoute =
  LegacyAppIdParticipantsArchivedRouteImport.update({
    id: '/participants/archived',
    path: '/participants/archived',
    getParentRoute: () => LegacyAppIdRouteRoute,
  } as any)
const LegacyAppIdMatchesArchivedRoute =
  LegacyAppIdMatchesArchivedRouteImport.update({
    id: '/matches/archived',
    path: '/matches/archived',
    getParentRoute: () => LegacyAppIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legacy/p': typeof LegacyPRouteRouteWithChildren
  '/legacy/components': typeof LegacyComponentsRoute
  '/legacy/': typeof LegacyIndexRoute
  '/legacy/app/$id': typeof LegacyAppIdRouteRouteWithChildren
  '/legacy/p/not-available': typeof LegacyPNotAvailableRoute
  '/legacy/p/participants': typeof LegacyPParticipantsRoute
  '/legacy/p/standing': typeof LegacyPStandingRoute
  '/legacy/p/teams': typeof LegacyPTeamsRoute
  '/legacy/p/': typeof LegacyPIndexRoute
  '/legacy/app/$id/admins': typeof LegacyAppIdAdminsRoute
  '/legacy/app/$id/audit-logs': typeof LegacyAppIdAuditLogsRoute
  '/legacy/app/$id/team-standing': typeof LegacyAppIdTeamStandingRoute
  '/legacy/app/auth/check': typeof LegacyAppAuthCheckRoute
  '/legacy/app/auth/login': typeof LegacyAppAuthLoginRoute
  '/legacy/p/tournaments/$id': typeof LegacyPTournamentsIdRoute
  '/legacy/app/$id/': typeof LegacyAppIdIndexRoute
  '/legacy/p/tournaments/': typeof LegacyPTournamentsIndexRoute
  '/legacy/app/$id/matches/archived': typeof LegacyAppIdMatchesArchivedRoute
  '/legacy/app/$id/participants/archived': typeof LegacyAppIdParticipantsArchivedRoute
  '/legacy/app/$id/teams/archived': typeof LegacyAppIdTeamsArchivedRoute
  '/legacy/app/$id/tournament/archived': typeof LegacyAppIdTournamentArchivedRoute
  '/legacy/app/$id/matches/': typeof LegacyAppIdMatchesIndexRoute
  '/legacy/app/$id/participants/': typeof LegacyAppIdParticipantsIndexRoute
  '/legacy/app/$id/teams/': typeof LegacyAppIdTeamsIndexRoute
  '/legacy/app/$id/tournament/': typeof LegacyAppIdTournamentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legacy/components': typeof LegacyComponentsRoute
  '/legacy': typeof LegacyIndexRoute
  '/legacy/p/not-available': typeof LegacyPNotAvailableRoute
  '/legacy/p/participants': typeof LegacyPParticipantsRoute
  '/legacy/p/standing': typeof LegacyPStandingRoute
  '/legacy/p/teams': typeof LegacyPTeamsRoute
  '/legacy/p': typeof LegacyPIndexRoute
  '/legacy/app/$id/admins': typeof LegacyAppIdAdminsRoute
  '/legacy/app/$id/audit-logs': typeof LegacyAppIdAuditLogsRoute
  '/legacy/app/$id/team-standing': typeof LegacyAppIdTeamStandingRoute
  '/legacy/app/auth/check': typeof LegacyAppAuthCheckRoute
  '/legacy/app/auth/login': typeof LegacyAppAuthLoginRoute
  '/legacy/p/tournaments/$id': typeof LegacyPTournamentsIdRoute
  '/legacy/app/$id': typeof LegacyAppIdIndexRoute
  '/legacy/p/tournaments': typeof LegacyPTournamentsIndexRoute
  '/legacy/app/$id/matches/archived': typeof LegacyAppIdMatchesArchivedRoute
  '/legacy/app/$id/participants/archived': typeof LegacyAppIdParticipantsArchivedRoute
  '/legacy/app/$id/teams/archived': typeof LegacyAppIdTeamsArchivedRoute
  '/legacy/app/$id/tournament/archived': typeof LegacyAppIdTournamentArchivedRoute
  '/legacy/app/$id/matches': typeof LegacyAppIdMatchesIndexRoute
  '/legacy/app/$id/participants': typeof LegacyAppIdParticipantsIndexRoute
  '/legacy/app/$id/teams': typeof LegacyAppIdTeamsIndexRoute
  '/legacy/app/$id/tournament': typeof LegacyAppIdTournamentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legacy/p': typeof LegacyPRouteRouteWithChildren
  '/legacy/components': typeof LegacyComponentsRoute
  '/legacy/': typeof LegacyIndexRoute
  '/legacy/app/$id': typeof LegacyAppIdRouteRouteWithChildren
  '/legacy/p/not-available': typeof LegacyPNotAvailableRoute
  '/legacy/p/participants': typeof LegacyPParticipantsRoute
  '/legacy/p/standing': typeof LegacyPStandingRoute
  '/legacy/p/teams': typeof LegacyPTeamsRoute
  '/legacy/p/': typeof LegacyPIndexRoute
  '/legacy/app/$id/admins': typeof LegacyAppIdAdminsRoute
  '/legacy/app/$id/audit-logs': typeof LegacyAppIdAuditLogsRoute
  '/legacy/app/$id/team-standing': typeof LegacyAppIdTeamStandingRoute
  '/legacy/app/auth/check': typeof LegacyAppAuthCheckRoute
  '/legacy/app/auth/login': typeof LegacyAppAuthLoginRoute
  '/legacy/p/tournaments/$id': typeof LegacyPTournamentsIdRoute
  '/legacy/app/$id/': typeof LegacyAppIdIndexRoute
  '/legacy/p/tournaments/': typeof LegacyPTournamentsIndexRoute
  '/legacy/app/$id/matches/archived': typeof LegacyAppIdMatchesArchivedRoute
  '/legacy/app/$id/participants/archived': typeof LegacyAppIdParticipantsArchivedRoute
  '/legacy/app/$id/teams/archived': typeof LegacyAppIdTeamsArchivedRoute
  '/legacy/app/$id/tournament/archived': typeof LegacyAppIdTournamentArchivedRoute
  '/legacy/app/$id/matches/': typeof LegacyAppIdMatchesIndexRoute
  '/legacy/app/$id/participants/': typeof LegacyAppIdParticipantsIndexRoute
  '/legacy/app/$id/teams/': typeof LegacyAppIdTeamsIndexRoute
  '/legacy/app/$id/tournament/': typeof LegacyAppIdTournamentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legacy/p'
    | '/legacy/components'
    | '/legacy/'
    | '/legacy/app/$id'
    | '/legacy/p/not-available'
    | '/legacy/p/participants'
    | '/legacy/p/standing'
    | '/legacy/p/teams'
    | '/legacy/p/'
    | '/legacy/app/$id/admins'
    | '/legacy/app/$id/audit-logs'
    | '/legacy/app/$id/team-standing'
    | '/legacy/app/auth/check'
    | '/legacy/app/auth/login'
    | '/legacy/p/tournaments/$id'
    | '/legacy/app/$id/'
    | '/legacy/p/tournaments/'
    | '/legacy/app/$id/matches/archived'
    | '/legacy/app/$id/participants/archived'
    | '/legacy/app/$id/teams/archived'
    | '/legacy/app/$id/tournament/archived'
    | '/legacy/app/$id/matches/'
    | '/legacy/app/$id/participants/'
    | '/legacy/app/$id/teams/'
    | '/legacy/app/$id/tournament/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legacy/components'
    | '/legacy'
    | '/legacy/p/not-available'
    | '/legacy/p/participants'
    | '/legacy/p/standing'
    | '/legacy/p/teams'
    | '/legacy/p'
    | '/legacy/app/$id/admins'
    | '/legacy/app/$id/audit-logs'
    | '/legacy/app/$id/team-standing'
    | '/legacy/app/auth/check'
    | '/legacy/app/auth/login'
    | '/legacy/p/tournaments/$id'
    | '/legacy/app/$id'
    | '/legacy/p/tournaments'
    | '/legacy/app/$id/matches/archived'
    | '/legacy/app/$id/participants/archived'
    | '/legacy/app/$id/teams/archived'
    | '/legacy/app/$id/tournament/archived'
    | '/legacy/app/$id/matches'
    | '/legacy/app/$id/participants'
    | '/legacy/app/$id/teams'
    | '/legacy/app/$id/tournament'
  id:
    | '__root__'
    | '/'
    | '/legacy/p'
    | '/legacy/components'
    | '/legacy/'
    | '/legacy/app/$id'
    | '/legacy/p/not-available'
    | '/legacy/p/participants'
    | '/legacy/p/standing'
    | '/legacy/p/teams'
    | '/legacy/p/'
    | '/legacy/app/$id/admins'
    | '/legacy/app/$id/audit-logs'
    | '/legacy/app/$id/team-standing'
    | '/legacy/app/auth/check'
    | '/legacy/app/auth/login'
    | '/legacy/p/tournaments/$id'
    | '/legacy/app/$id/'
    | '/legacy/p/tournaments/'
    | '/legacy/app/$id/matches/archived'
    | '/legacy/app/$id/participants/archived'
    | '/legacy/app/$id/teams/archived'
    | '/legacy/app/$id/tournament/archived'
    | '/legacy/app/$id/matches/'
    | '/legacy/app/$id/participants/'
    | '/legacy/app/$id/teams/'
    | '/legacy/app/$id/tournament/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegacyPRouteRoute: typeof LegacyPRouteRouteWithChildren
  LegacyComponentsRoute: typeof LegacyComponentsRoute
  LegacyIndexRoute: typeof LegacyIndexRoute
  LegacyAppIdRouteRoute: typeof LegacyAppIdRouteRouteWithChildren
  LegacyAppAuthCheckRoute: typeof LegacyAppAuthCheckRoute
  LegacyAppAuthLoginRoute: typeof LegacyAppAuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/': {
      id: '/legacy/'
      path: '/legacy'
      fullPath: '/legacy/'
      preLoaderRoute: typeof LegacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/components': {
      id: '/legacy/components'
      path: '/legacy/components'
      fullPath: '/legacy/components'
      preLoaderRoute: typeof LegacyComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/p': {
      id: '/legacy/p'
      path: '/legacy/p'
      fullPath: '/legacy/p'
      preLoaderRoute: typeof LegacyPRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/p/': {
      id: '/legacy/p/'
      path: '/'
      fullPath: '/legacy/p/'
      preLoaderRoute: typeof LegacyPIndexRouteImport
      parentRoute: typeof LegacyPRouteRoute
    }
    '/legacy/p/teams': {
      id: '/legacy/p/teams'
      path: '/teams'
      fullPath: '/legacy/p/teams'
      preLoaderRoute: typeof LegacyPTeamsRouteImport
      parentRoute: typeof LegacyPRouteRoute
    }
    '/legacy/p/standing': {
      id: '/legacy/p/standing'
      path: '/standing'
      fullPath: '/legacy/p/standing'
      preLoaderRoute: typeof LegacyPStandingRouteImport
      parentRoute: typeof LegacyPRouteRoute
    }
    '/legacy/p/participants': {
      id: '/legacy/p/participants'
      path: '/participants'
      fullPath: '/legacy/p/participants'
      preLoaderRoute: typeof LegacyPParticipantsRouteImport
      parentRoute: typeof LegacyPRouteRoute
    }
    '/legacy/p/not-available': {
      id: '/legacy/p/not-available'
      path: '/not-available'
      fullPath: '/legacy/p/not-available'
      preLoaderRoute: typeof LegacyPNotAvailableRouteImport
      parentRoute: typeof LegacyPRouteRoute
    }
    '/legacy/app/$id': {
      id: '/legacy/app/$id'
      path: '/legacy/app/$id'
      fullPath: '/legacy/app/$id'
      preLoaderRoute: typeof LegacyAppIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/p/tournaments/': {
      id: '/legacy/p/tournaments/'
      path: '/tournaments'
      fullPath: '/legacy/p/tournaments/'
      preLoaderRoute: typeof LegacyPTournamentsIndexRouteImport
      parentRoute: typeof LegacyPRouteRoute
    }
    '/legacy/app/$id/': {
      id: '/legacy/app/$id/'
      path: '/'
      fullPath: '/legacy/app/$id/'
      preLoaderRoute: typeof LegacyAppIdIndexRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/p/tournaments/$id': {
      id: '/legacy/p/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/legacy/p/tournaments/$id'
      preLoaderRoute: typeof LegacyPTournamentsIdRouteImport
      parentRoute: typeof LegacyPRouteRoute
    }
    '/legacy/app/auth/login': {
      id: '/legacy/app/auth/login'
      path: '/legacy/app/auth/login'
      fullPath: '/legacy/app/auth/login'
      preLoaderRoute: typeof LegacyAppAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/app/auth/check': {
      id: '/legacy/app/auth/check'
      path: '/legacy/app/auth/check'
      fullPath: '/legacy/app/auth/check'
      preLoaderRoute: typeof LegacyAppAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/app/$id/team-standing': {
      id: '/legacy/app/$id/team-standing'
      path: '/team-standing'
      fullPath: '/legacy/app/$id/team-standing'
      preLoaderRoute: typeof LegacyAppIdTeamStandingRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/audit-logs': {
      id: '/legacy/app/$id/audit-logs'
      path: '/audit-logs'
      fullPath: '/legacy/app/$id/audit-logs'
      preLoaderRoute: typeof LegacyAppIdAuditLogsRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/admins': {
      id: '/legacy/app/$id/admins'
      path: '/admins'
      fullPath: '/legacy/app/$id/admins'
      preLoaderRoute: typeof LegacyAppIdAdminsRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/tournament/': {
      id: '/legacy/app/$id/tournament/'
      path: '/tournament'
      fullPath: '/legacy/app/$id/tournament/'
      preLoaderRoute: typeof LegacyAppIdTournamentIndexRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/teams/': {
      id: '/legacy/app/$id/teams/'
      path: '/teams'
      fullPath: '/legacy/app/$id/teams/'
      preLoaderRoute: typeof LegacyAppIdTeamsIndexRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/participants/': {
      id: '/legacy/app/$id/participants/'
      path: '/participants'
      fullPath: '/legacy/app/$id/participants/'
      preLoaderRoute: typeof LegacyAppIdParticipantsIndexRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/matches/': {
      id: '/legacy/app/$id/matches/'
      path: '/matches'
      fullPath: '/legacy/app/$id/matches/'
      preLoaderRoute: typeof LegacyAppIdMatchesIndexRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/tournament/archived': {
      id: '/legacy/app/$id/tournament/archived'
      path: '/tournament/archived'
      fullPath: '/legacy/app/$id/tournament/archived'
      preLoaderRoute: typeof LegacyAppIdTournamentArchivedRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/teams/archived': {
      id: '/legacy/app/$id/teams/archived'
      path: '/teams/archived'
      fullPath: '/legacy/app/$id/teams/archived'
      preLoaderRoute: typeof LegacyAppIdTeamsArchivedRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/participants/archived': {
      id: '/legacy/app/$id/participants/archived'
      path: '/participants/archived'
      fullPath: '/legacy/app/$id/participants/archived'
      preLoaderRoute: typeof LegacyAppIdParticipantsArchivedRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
    '/legacy/app/$id/matches/archived': {
      id: '/legacy/app/$id/matches/archived'
      path: '/matches/archived'
      fullPath: '/legacy/app/$id/matches/archived'
      preLoaderRoute: typeof LegacyAppIdMatchesArchivedRouteImport
      parentRoute: typeof LegacyAppIdRouteRoute
    }
  }
}

interface LegacyPRouteRouteChildren {
  LegacyPNotAvailableRoute: typeof LegacyPNotAvailableRoute
  LegacyPParticipantsRoute: typeof LegacyPParticipantsRoute
  LegacyPStandingRoute: typeof LegacyPStandingRoute
  LegacyPTeamsRoute: typeof LegacyPTeamsRoute
  LegacyPIndexRoute: typeof LegacyPIndexRoute
  LegacyPTournamentsIdRoute: typeof LegacyPTournamentsIdRoute
  LegacyPTournamentsIndexRoute: typeof LegacyPTournamentsIndexRoute
}

const LegacyPRouteRouteChildren: LegacyPRouteRouteChildren = {
  LegacyPNotAvailableRoute: LegacyPNotAvailableRoute,
  LegacyPParticipantsRoute: LegacyPParticipantsRoute,
  LegacyPStandingRoute: LegacyPStandingRoute,
  LegacyPTeamsRoute: LegacyPTeamsRoute,
  LegacyPIndexRoute: LegacyPIndexRoute,
  LegacyPTournamentsIdRoute: LegacyPTournamentsIdRoute,
  LegacyPTournamentsIndexRoute: LegacyPTournamentsIndexRoute,
}

const LegacyPRouteRouteWithChildren = LegacyPRouteRoute._addFileChildren(
  LegacyPRouteRouteChildren,
)

interface LegacyAppIdRouteRouteChildren {
  LegacyAppIdAdminsRoute: typeof LegacyAppIdAdminsRoute
  LegacyAppIdAuditLogsRoute: typeof LegacyAppIdAuditLogsRoute
  LegacyAppIdTeamStandingRoute: typeof LegacyAppIdTeamStandingRoute
  LegacyAppIdIndexRoute: typeof LegacyAppIdIndexRoute
  LegacyAppIdMatchesArchivedRoute: typeof LegacyAppIdMatchesArchivedRoute
  LegacyAppIdParticipantsArchivedRoute: typeof LegacyAppIdParticipantsArchivedRoute
  LegacyAppIdTeamsArchivedRoute: typeof LegacyAppIdTeamsArchivedRoute
  LegacyAppIdTournamentArchivedRoute: typeof LegacyAppIdTournamentArchivedRoute
  LegacyAppIdMatchesIndexRoute: typeof LegacyAppIdMatchesIndexRoute
  LegacyAppIdParticipantsIndexRoute: typeof LegacyAppIdParticipantsIndexRoute
  LegacyAppIdTeamsIndexRoute: typeof LegacyAppIdTeamsIndexRoute
  LegacyAppIdTournamentIndexRoute: typeof LegacyAppIdTournamentIndexRoute
}

const LegacyAppIdRouteRouteChildren: LegacyAppIdRouteRouteChildren = {
  LegacyAppIdAdminsRoute: LegacyAppIdAdminsRoute,
  LegacyAppIdAuditLogsRoute: LegacyAppIdAuditLogsRoute,
  LegacyAppIdTeamStandingRoute: LegacyAppIdTeamStandingRoute,
  LegacyAppIdIndexRoute: LegacyAppIdIndexRoute,
  LegacyAppIdMatchesArchivedRoute: LegacyAppIdMatchesArchivedRoute,
  LegacyAppIdParticipantsArchivedRoute: LegacyAppIdParticipantsArchivedRoute,
  LegacyAppIdTeamsArchivedRoute: LegacyAppIdTeamsArchivedRoute,
  LegacyAppIdTournamentArchivedRoute: LegacyAppIdTournamentArchivedRoute,
  LegacyAppIdMatchesIndexRoute: LegacyAppIdMatchesIndexRoute,
  LegacyAppIdParticipantsIndexRoute: LegacyAppIdParticipantsIndexRoute,
  LegacyAppIdTeamsIndexRoute: LegacyAppIdTeamsIndexRoute,
  LegacyAppIdTournamentIndexRoute: LegacyAppIdTournamentIndexRoute,
}

const LegacyAppIdRouteRouteWithChildren =
  LegacyAppIdRouteRoute._addFileChildren(LegacyAppIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegacyPRouteRoute: LegacyPRouteRouteWithChildren,
  LegacyComponentsRoute: LegacyComponentsRoute,
  LegacyIndexRoute: LegacyIndexRoute,
  LegacyAppIdRouteRoute: LegacyAppIdRouteRouteWithChildren,
  LegacyAppAuthCheckRoute: LegacyAppAuthCheckRoute,
  LegacyAppAuthLoginRoute: LegacyAppAuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
