/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Retrieves a paginated list of Matches Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Matches Collection
 */
export const getCollectionsMatchesRecordsQueryPageDefault = 1;

export const getCollectionsMatchesRecordsQueryPerPageDefault = 30;
export const getCollectionsMatchesRecordsQueryPerPageMax = 500;

export const getCollectionsMatchesRecordsQuerySkipTotalDefault = false;

export const GetCollectionsMatchesRecordsQueryParams = zod.object({
  "filter": zod.string().optional().describe('Filtering expression (e.g., \'created > \"2022-01-01\"\')'),
  "sort": zod.string().optional().describe('Comma-separated list of fields to sort by. Prefix with \'-\' for descending order.'),
  "page": zod.number().min(1).default(getCollectionsMatchesRecordsQueryPageDefault).describe('Page number (starting from 1)'),
  "perPage": zod.number().min(1).max(getCollectionsMatchesRecordsQueryPerPageMax).default(getCollectionsMatchesRecordsQueryPerPageDefault).describe('Number of records per page (max 500)'),
  "skipTotal": zod.boolean().default(getCollectionsMatchesRecordsQuerySkipTotalDefault).describe('Set to true to skip the total count (improves performance for large collections)'),
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsMatchesRecordsResponse = zod.object({
  "page": zod.number().optional(),
  "perPage": zod.number().optional(),
  "totalItems": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "items": zod.array(zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_a": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_b": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "winner": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "bracket": zod.string().optional(),
  "round": zod.string().optional(),
  "order": zod.number().optional(),
  "best_of": zod.number(),
  "match_label": zod.string().optional(),
  "scheduled_at": zod.iso.datetime({"offset":true}).optional(),
  "status": zod.enum(['scheduled', 'live', 'completed', 'walkover', 'cancelled']),
  "score_a": zod.number().optional(),
  "score_b": zod.number().optional(),
  "notes": zod.string().optional(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})).optional()
})

/**
 * @summary Create Matches Collection Record
 */
export const PostCollectionsMatchesRecordsBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_a": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_b": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "winner": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "bracket": zod.string().optional(),
  "round": zod.string().optional(),
  "order": zod.number().optional(),
  "best_of": zod.number(),
  "match_label": zod.string().optional(),
  "scheduled_at": zod.iso.datetime({"offset":true}).optional(),
  "status": zod.enum(['scheduled', 'live', 'completed', 'walkover', 'cancelled']),
  "score_a": zod.number().optional(),
  "score_b": zod.number().optional(),
  "notes": zod.string().optional(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const PostCollectionsMatchesRecordsResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_a": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_b": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "winner": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "bracket": zod.string().optional(),
  "round": zod.string().optional(),
  "order": zod.number().optional(),
  "best_of": zod.number(),
  "match_label": zod.string().optional(),
  "scheduled_at": zod.iso.datetime({"offset":true}).optional(),
  "status": zod.enum(['scheduled', 'live', 'completed', 'walkover', 'cancelled']),
  "score_a": zod.number().optional(),
  "score_b": zod.number().optional(),
  "notes": zod.string().optional(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Get Matches Collection by ID
 */
export const GetCollectionsMatchesRecordsIdParams = zod.object({
  "id": zod.string()
})

export const GetCollectionsMatchesRecordsIdQueryParams = zod.object({
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsMatchesRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_a": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_b": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "winner": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "bracket": zod.string().optional(),
  "round": zod.string().optional(),
  "order": zod.number().optional(),
  "best_of": zod.number(),
  "match_label": zod.string().optional(),
  "scheduled_at": zod.iso.datetime({"offset":true}).optional(),
  "status": zod.enum(['scheduled', 'live', 'completed', 'walkover', 'cancelled']),
  "score_a": zod.number().optional(),
  "score_b": zod.number().optional(),
  "notes": zod.string().optional(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Update Matches Collection Record
 */
export const PatchCollectionsMatchesRecordsIdParams = zod.object({
  "id": zod.string()
})

export const PatchCollectionsMatchesRecordsIdBody = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_a": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_b": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "winner": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "bracket": zod.string().optional(),
  "round": zod.string().optional(),
  "order": zod.number().optional(),
  "best_of": zod.number(),
  "match_label": zod.string().optional(),
  "scheduled_at": zod.iso.datetime({"offset":true}).optional(),
  "status": zod.enum(['scheduled', 'live', 'completed', 'walkover', 'cancelled']),
  "score_a": zod.number().optional(),
  "score_b": zod.number().optional(),
  "notes": zod.string().optional(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

export const PatchCollectionsMatchesRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament": zod.string().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_a": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "team_b": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "winner": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "bracket": zod.string().optional(),
  "round": zod.string().optional(),
  "order": zod.number().optional(),
  "best_of": zod.number(),
  "match_label": zod.string().optional(),
  "scheduled_at": zod.iso.datetime({"offset":true}).optional(),
  "status": zod.enum(['scheduled', 'live', 'completed', 'walkover', 'cancelled']),
  "score_a": zod.number().optional(),
  "score_b": zod.number().optional(),
  "notes": zod.string().optional(),
  "created_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "updated_by": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "archived": zod.boolean(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

/**
 * @summary Delete Matches Collection Record
 */
export const DeleteCollectionsMatchesRecordsIdParams = zod.object({
  "id": zod.string()
})

export const DeleteCollectionsMatchesRecordsIdResponse = zod.void()

