/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * PocketBase API
 * API documentation generated from PocketBase schema with collection grouping
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * Retrieves a paginated list of Draft_suggestions Collection records. Supports filtering, sorting, and expanding relations.
 * @summary List Draft_suggestions Collection
 */
export const getCollectionsDraftSuggestionsRecordsQueryPageDefault = 1;

export const getCollectionsDraftSuggestionsRecordsQueryPerPageDefault = 30;
export const getCollectionsDraftSuggestionsRecordsQueryPerPageMax = 500;

export const getCollectionsDraftSuggestionsRecordsQuerySkipTotalDefault = false;

export const GetCollectionsDraftSuggestionsRecordsQueryParams = zod.object({
  "filter": zod.string().optional().describe('Filtering expression (e.g., \'created > \"2022-01-01\"\')'),
  "sort": zod.string().optional().describe('Comma-separated list of fields to sort by. Prefix with \'-\' for descending order.'),
  "page": zod.number().min(1).default(getCollectionsDraftSuggestionsRecordsQueryPageDefault).describe('Page number (starting from 1)'),
  "perPage": zod.number().min(1).max(getCollectionsDraftSuggestionsRecordsQueryPerPageMax).default(getCollectionsDraftSuggestionsRecordsQueryPerPageDefault).describe('Number of records per page (max 500)'),
  "skipTotal": zod.boolean().default(getCollectionsDraftSuggestionsRecordsQuerySkipTotalDefault).describe('Set to true to skip the total count (improves performance for large collections)'),
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsDraftSuggestionsRecordsResponse = zod.object({
  "page": zod.number().optional(),
  "perPage": zod.number().optional(),
  "totalItems": zod.number().optional(),
  "totalPages": zod.number().optional(),
  "items": zod.array(zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament_id": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "tournament_title": zod.string(),
  "match_label": zod.record(zod.string(), zod.unknown()).optional(),
  "suggested_bans": zod.record(zod.string(), zod.unknown()).optional(),
  "suggested_picks": zod.record(zod.string(), zod.unknown()).optional(),
  "notes": zod.record(zod.string(), zod.unknown()).optional(),
  "status": zod.record(zod.string(), zod.unknown()).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})).optional()
})

/**
 * @summary Get Draft_suggestions Collection by ID
 */
export const GetCollectionsDraftSuggestionsRecordsIdParams = zod.object({
  "id": zod.string()
})

export const GetCollectionsDraftSuggestionsRecordsIdQueryParams = zod.object({
  "expand": zod.string().optional().describe('Comma-separated list of relations to expand. Use dot notation for nested relations.')
})

export const GetCollectionsDraftSuggestionsRecordsIdResponse = zod.object({
  "id": zod.string().optional().describe('Unique record identifier'),
  "tournament_id": zod.string().optional().describe('Relation field. When expanded, this becomes the related record object. Use the \'expand\' query parameter to expand relations.'),
  "tournament_title": zod.string(),
  "match_label": zod.record(zod.string(), zod.unknown()).optional(),
  "suggested_bans": zod.record(zod.string(), zod.unknown()).optional(),
  "suggested_picks": zod.record(zod.string(), zod.unknown()).optional(),
  "notes": zod.record(zod.string(), zod.unknown()).optional(),
  "status": zod.record(zod.string(), zod.unknown()).optional(),
  "created": zod.iso.datetime({"offset":true}).optional(),
  "updated": zod.iso.datetime({"offset":true}).optional()
})

